# Generated by Django 5.2.12 on 2026-03-29 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_alter_role_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('academic_year', models.CharField(default='2025-2026', max_length=9, verbose_name='العام الدراسي')),
                ('leave_type', models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('emergency', 'إجازة طارئة'), ('unpaid', 'إجازة بدون راتب'), ('maternity', 'إجازة أمومة'), ('hajj', 'إجازة حج'), ('marriage', 'إجازة زواج'), ('iddah', 'إجازة عدّة'), ('bereavement', 'إجازة عزاء'), ('training', 'إجازة تدريب'), ('official', 'مهمة رسمية'), ('study', 'إجازة دراسية'), ('child_care', 'رعاية طفل'), ('work_injury', 'إصابة عمل'), ('patient_companion', 'مرافقة مريض'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الإجازة')),
                ('total_days', models.PositiveSmallIntegerField(default=0, verbose_name='إجمالي الأيام')),
                ('used_days', models.PositiveSmallIntegerField(default=0, verbose_name='الأيام المستخدمة')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.school', verbose_name='المدرسة')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'رصيد إجازات',
                'verbose_name_plural': 'أرصدة الإجازات',
                'ordering': ['leave_type'],
                'indexes': [models.Index(fields=['school', 'staff', 'academic_year'], name='staff_affai_school__ee5ff2_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'staff', 'academic_year', 'leave_type'), name='unique_leave_balance')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('leave_type', models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('emergency', 'إجازة طارئة'), ('unpaid', 'إجازة بدون راتب'), ('maternity', 'إجازة أمومة'), ('hajj', 'إجازة حج'), ('marriage', 'إجازة زواج'), ('iddah', 'إجازة عدّة'), ('bereavement', 'إجازة عزاء'), ('training', 'إجازة تدريب'), ('official', 'مهمة رسمية'), ('study', 'إجازة دراسية'), ('child_care', 'رعاية طفل'), ('work_injury', 'إصابة عمل'), ('patient_companion', 'مرافقة مريض'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('days_count', models.PositiveSmallIntegerField(verbose_name='عدد الأيام')),
                ('reason', models.TextField(max_length=1000, verbose_name='السبب')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/%Y/%m/', verbose_name='مرفق')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة'), ('cancelled', 'ملغاة')], db_index=True, default='pending', max_length=15, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('academic_year', models.CharField(default='2025-2026', max_length=9, verbose_name='العام الدراسي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='راجعها')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_leave_requests', to='core.school', verbose_name='المدرسة')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عدّله')),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'staff', 'status'], name='staff_affai_school__a43f00_idx'), models.Index(fields=['school', 'start_date', 'end_date'], name='staff_affai_school__ad72ba_idx')],
            },
        ),
    ]
