# Generated by Django 5.2.17 on 2026-09-14 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

#: هجرةٌ حُذف ملفُّها من الفرع (644e2880) وقد طُبّقت في قواعد جلساتٍ شقيقة: أنشأت
#: الجدولين نفسيهما بمخطّطٍ آخر (مفتاح BigAutoField) ولم تصل إلى main ولا إلى الإنتاج.
ORPHAN_MIGRATION = "0003_wave3g_staff_attendance_permits"
ORPHAN_TABLES = ("staff_affairs_permitrequest", "staff_affairs_staffattendance")


def clear_orphan(connection, name=ORPHAN_MIGRATION, tables=ORPHAN_TABLES):
    """يُزيل أثرَ الهجرة اليتيمة قبل إنشاء الجدولين — وإلّا سقط migrate بـ«already exists».

    لا يفعل شيئاً ما لم يُسجَّل اسمُها في ``django_migrations``. ولا يحذف جدولاً فيه
    صفّ: يتوقّف ويسمّي العلاج (نسخُ القاعدة من جديد بـ``scripts/session-db.sh``)، فلا
    تُفقد بياناتٌ بصمت.
    """
    quote = connection.ops.quote_name
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM django_migrations WHERE app = %s AND name = %s",
            ["staff_affairs", name],
        )
        if cursor.fetchone() is None:
            return
        present = [t for t in tables if t in connection.introspection.table_names(cursor)]
        for table in present:
            cursor.execute(f"SELECT EXISTS (SELECT 1 FROM {quote(table)})")
            if cursor.fetchone()[0]:
                raise RuntimeError(
                    f"الهجرةُ اليتيمة staff_affairs.{name} تركت {table} وفيه بيانات — لا يُحذف "
                    "آليّاً. انسخ قاعدةَ الجلسة من جديد: bash scripts/session-db.sh"
                )
        for table in present:
            cursor.execute(f"DROP TABLE {quote(table)} CASCADE")
        cursor.execute(
            "DELETE FROM django_migrations WHERE app = %s AND name = %s",
            ["staff_affairs", name],
        )


def _clear_orphan(apps, schema_editor):
    clear_orphan(schema_editor.connection)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auditlog_failed_login_actions'),
        ('staff_affairs', '0002_alter_leavebalance_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_clear_orphan, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PermitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('permit_type', models.CharField(choices=[('late_arrival', 'تأخير صباحي'), ('during_day', 'استئذان أثناء الدوام'), ('early_departure', 'خروج مبكر')], max_length=20, verbose_name='نوع الطلب')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('start_time', models.TimeField(verbose_name='من الساعة')),
                ('end_time', models.TimeField(verbose_name='إلى الساعة')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='المدة بالدقائق')),
                ('reason', models.CharField(max_length=500, verbose_name='سبب الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], default='pending', max_length=10, verbose_name='الحالة')),
                ('stage', models.CharField(choices=[('supervisor', 'المسؤول المباشر'), ('secretary', 'السكرتارية'), ('principal', 'مدير المدرسة'), ('closed', 'مغلق')], default='supervisor', max_length=10, verbose_name='المرحلة')),
                ('supervisor_role', models.CharField(max_length=30, verbose_name='دور المسؤول المباشر')),
                ('supervisor_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت موافقة المسؤول')),
                ('secretary_at', models.DateTimeField(blank=True, null=True, verbose_name='توقيت تسجيل الرصيد')),
                ('recorded_balance_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='رصيد الساعات المسجّل (دقائق)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('rejection_reason', models.CharField(blank=True, max_length=300, verbose_name='سبب الرفض')),
                ('rejected_stage', models.CharField(blank=True, choices=[('supervisor', 'المسؤول المباشر'), ('secretary', 'السكرتارية'), ('principal', 'مدير المدرسة'), ('closed', 'مغلق')], max_length=10, verbose_name='مرحلة الرفض')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_permit_requests', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_permit_requests', to='core.school', verbose_name='المدرسة')),
                ('secretary_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_permit_requests', to=settings.AUTH_USER_MODEL, verbose_name='موظف السكرتارية')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_requests', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('supervisor_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_permit_requests', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول المباشر')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عدّله')),
            ],
            options={
                'verbose_name': 'طلب إذن',
                'verbose_name_plural': 'طلبات الأذونات',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['school', 'staff', 'date'], name='staff_affai_school__034335_idx'), models.Index(fields=['school', 'status', 'stage'], name='staff_affai_school__50637d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('school', 'staff', 'date'), name='one_approved_permit_per_day'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='permit_end_after_start'), models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0), ('duration_minutes__lte', 120)), name='permit_duration_within_two_hours')],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخّر'), ('absent', 'غائب'), ('permitted', 'مستأذن')], max_length=10, verbose_name='الحالة')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('late_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='دقائق التأخّر')),
                ('permit_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='دقائق الإذن المعتمد')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_records', to='core.school', verbose_name='المدرسة')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عدّله')),
            ],
            options={
                'verbose_name': 'حضور موظف',
                'verbose_name_plural': 'حضور الموظفين',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['school', 'date', 'status'], name='staff_affai_school__0e4009_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'staff', 'date'), name='unique_staff_attendance_day')],
            },
        ),
    ]
