# Generated by Django 5.2.17 on 2026-09-14 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_auditlog_failed_login_actions"),
        ("staff_affairs", "0002_alter_leavebalance_academic_year_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermitRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل")),
                (
                    "permit_type",
                    models.CharField(
                        choices=[
                            ("late_arrival", "تأخير صباحي"),
                            ("during_day", "استئذان أثناء الدوام"),
                            ("early_departure", "خروج مبكر"),
                        ],
                        max_length=20,
                        verbose_name="نوع الطلب",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                ("start_time", models.TimeField(verbose_name="من الساعة")),
                ("end_time", models.TimeField(verbose_name="إلى الساعة")),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(verbose_name="المدة بالدقائق"),
                ),
                ("reason", models.CharField(max_length=500, verbose_name="سبب الطلب")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                            ("cancelled", "ملغى"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ المراجعة"),
                ),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=300, verbose_name="سبب الرفض"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_permit_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمده",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_permit_requests",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permit_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب إذن",
                "verbose_name_plural": "طلبات الأذونات",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "staff", "date"], name="staff_affai_school__034335_idx"
                    ),
                    models.Index(
                        fields=["school", "status"], name="staff_affai_school__e0173d_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "approved")),
                        fields=("school", "staff", "date"),
                        name="one_approved_permit_per_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="permit_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("duration_minutes__gt", 0), ("duration_minutes__lte", 120)
                        ),
                        name="permit_duration_within_two_hours",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل")),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("late", "متأخّر"),
                            ("absent", "غائب"),
                            ("permitted", "مستأذن"),
                        ],
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("check_in", models.TimeField(blank=True, null=True, verbose_name="وقت الحضور")),
                ("check_out", models.TimeField(blank=True, null=True, verbose_name="وقت الانصراف")),
                (
                    "late_minutes",
                    models.PositiveSmallIntegerField(default=0, verbose_name="دقائق التأخّر"),
                ),
                (
                    "permit_minutes",
                    models.PositiveSmallIntegerField(default=0, verbose_name="دقائق الإذن المعتمد"),
                ),
                ("notes", models.CharField(blank=True, max_length=300, verbose_name="ملاحظات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_attendance_records",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_attendance_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور موظف",
                "verbose_name_plural": "حضور الموظفين",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["school", "date", "status"], name="staff_affai_school__0e4009_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "staff", "date"), name="unique_staff_attendance_day"
                    )
                ],
            },
        ),
    ]
