# Generated by Django 5.2.17 on 2026-09-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_affairs", "0004_rls_staff_attendance_and_permits"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffattendance",
            name="absence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("casual", "عارضة"),
                    ("unpaid", "بدون راتب"),
                    ("sick", "مرضية"),
                    ("official_mission", "مهمة رسمية"),
                    ("experience_exchange", "تبادل خبرات"),
                    ("external_training", "تدريب خارجي"),
                ],
                max_length=20,
                verbose_name="نوع الغياب",
            ),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="accepted_excuse",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="العذر المقبول (البند 2.4)"
            ),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="early_leave_minutes",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="دقائق الانصراف المبكر بلا إذن"
            ),
        ),
    ]
