# Generated by Django 5.2.17 on 2026-10-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_affairs", "0004_staff_attendance_exemption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavebalance",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("annual", "إجازة سنوية"),
                    ("sick", "إجازة مرضية"),
                    ("emergency", "إجازة عارضة"),
                    ("unpaid", "إجازة بدون راتب"),
                    ("maternity", "إجازة أمومة"),
                    ("hajj", "إجازة حج"),
                    ("marriage", "إجازة زواج"),
                    ("iddah", "إجازة عدّة"),
                    ("bereavement", "إجازة عزاء"),
                    ("training", "إجازة تدريب"),
                    ("official", "مهمة رسمية"),
                    ("study", "إجازة دراسية"),
                    ("child_care", "رعاية طفل"),
                    ("work_injury", "إصابة عمل"),
                    ("patient_companion", "مرافقة مريض"),
                    ("spouse_companion", "إجازة مرافقة الزوج"),
                    ("mahram", "إجازة محرم"),
                    ("exceptional", "إجازة تفرغ استثنائية"),
                    ("exams", "إجازة امتحانات"),
                    ("other", "أخرى"),
                ],
                max_length=20,
                verbose_name="نوع الإجازة",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("annual", "إجازة سنوية"),
                    ("sick", "إجازة مرضية"),
                    ("emergency", "إجازة عارضة"),
                    ("unpaid", "إجازة بدون راتب"),
                    ("maternity", "إجازة أمومة"),
                    ("hajj", "إجازة حج"),
                    ("marriage", "إجازة زواج"),
                    ("iddah", "إجازة عدّة"),
                    ("bereavement", "إجازة عزاء"),
                    ("training", "إجازة تدريب"),
                    ("official", "مهمة رسمية"),
                    ("study", "إجازة دراسية"),
                    ("child_care", "رعاية طفل"),
                    ("work_injury", "إصابة عمل"),
                    ("patient_companion", "مرافقة مريض"),
                    ("spouse_companion", "إجازة مرافقة الزوج"),
                    ("mahram", "إجازة محرم"),
                    ("exceptional", "إجازة تفرغ استثنائية"),
                    ("exams", "إجازة امتحانات"),
                    ("other", "أخرى"),
                ],
                max_length=20,
                verbose_name="نوع الإجازة",
            ),
        ),
    ]
