# Generated by Django 5.2.17 on 2026-10-04 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def close_decided_requests(apps, schema_editor):
    """طلباتٌ فُصل فيها قبل المراحل: تُغلق مرحلتُها (الافتراضيّ «المسؤول» لا يصحّ لها)."""
    LeaveRequest = apps.get_model("staff_affairs", "LeaveRequest")
    LeaveRequest.objects.exclude(status="pending").update(stage="closed")


class Migration(migrations.Migration):

    dependencies = [
        ("staff_affairs", "0005_leave_types_align_m61"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="decided_on_behalf",
            field=models.BooleanField(default=False, verbose_name="قُرّر بالإنابة"),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="deputy_role",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="دور النائب المسؤول"
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="recorded_balance_days",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="الرصيد المسجّل (أيام)"
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="rejected_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("supervisor", "المسؤول المباشر والنائب المسؤول"),
                    ("secretary", "السكرتارية"),
                    ("principal", "مدير المدرسة"),
                    ("closed", "مغلق"),
                ],
                max_length=12,
                verbose_name="مرحلة الرفض",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="secretary_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="توقيت تسجيل الرصيد"
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="secretary_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_leave_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="موظف السكرتارية",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="stage",
            field=models.CharField(
                choices=[
                    ("supervisor", "المسؤول المباشر والنائب المسؤول"),
                    ("secretary", "السكرتارية"),
                    ("principal", "مدير المدرسة"),
                    ("closed", "مغلق"),
                ],
                default="supervisor",
                max_length=12,
                verbose_name="المرحلة",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="supervisor_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت موافقة المسؤول"
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="supervisor_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_leave_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المسؤول المباشر والنائب",
            ),
        ),
        migrations.RunPython(close_decided_requests, migrations.RunPython.noop),
    ]
