# Generated by Django 5.2.17 on 2026-09-15 01:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _vice_box_is_its_own_stage(apps, schema_editor):
    """ما كان معلَّقاً في «المسؤول المباشر» كان بانتظار النائب — فمرحلتُه الآن «النائب المسؤول»."""
    PermitRequest = apps.get_model("staff_affairs", "PermitRequest")
    PermitRequest.objects.filter(stage="supervisor", line_manager__isnull=True).update(
        stage="deputy"
    )
    PermitRequest.objects.filter(rejected_stage="supervisor").update(rejected_stage="deputy")


def _back_to_one_box(apps, schema_editor):
    PermitRequest = apps.get_model("staff_affairs", "PermitRequest")
    PermitRequest.objects.filter(stage="deputy").update(stage="supervisor")
    PermitRequest.objects.filter(rejected_stage="deputy").update(rejected_stage="supervisor")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_auditlog_failed_login_actions"),
        ("staff_affairs", "0005_staff_attendance_absence_excuse_early_leave"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # «دور المسؤول المباشر» كان دورَ النائب — فالعمودُ نفسُه يُسمّى باسمه، وقيمُه باقية.
        migrations.RenameField(
            model_name="permitrequest",
            old_name="supervisor_role",
            new_name="deputy_role",
        ),
        migrations.AddField(
            model_name="permitrequest",
            name="deputy_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="وقت موافقة النائب"),
        ),
        migrations.AddField(
            model_name="permitrequest",
            name="deputy_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deputy_permit_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="النائب المسؤول",
            ),
        ),
        migrations.AlterField(
            model_name="permitrequest",
            name="deputy_role",
            field=models.CharField(blank=True, max_length=30, verbose_name="دور النائب المسؤول"),
        ),
        migrations.AddField(
            model_name="permitrequest",
            name="external_reference",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="مرجع اعتماد رئيس المدير"
            ),
        ),
        migrations.AddField(
            model_name="permitrequest",
            name="line_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="line_managed_permit_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المسؤول المباشر المسمّى",
            ),
        ),
        migrations.AlterField(
            model_name="permitrequest",
            name="rejected_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("supervisor", "المسؤول المباشر"),
                    ("deputy", "النائب المسؤول"),
                    ("secretary", "السكرتارية"),
                    ("principal", "مدير المدرسة"),
                    ("external", "اعتماد رئيس المدير"),
                    ("closed", "مغلق"),
                ],
                max_length=10,
                verbose_name="مرحلة الرفض",
            ),
        ),
        migrations.AlterField(
            model_name="permitrequest",
            name="stage",
            field=models.CharField(
                choices=[
                    ("supervisor", "المسؤول المباشر"),
                    ("deputy", "النائب المسؤول"),
                    ("secretary", "السكرتارية"),
                    ("principal", "مدير المدرسة"),
                    ("external", "اعتماد رئيس المدير"),
                    ("closed", "مغلق"),
                ],
                default="supervisor",
                max_length=10,
                verbose_name="المرحلة",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل")),
                (
                    "exception_type",
                    models.CharField(
                        choices=[("late_arrival", "تأخير صباحي"), ("early_departure", "خروج مبكر")],
                        max_length=20,
                        verbose_name="نوع الاستثناء",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="من تاريخ")),
                ("end_date", models.DateField(verbose_name="إلى تاريخ")),
                ("boundary_time", models.TimeField(verbose_name="الساعة")),
                ("content", models.CharField(max_length=1000, verbose_name="محتوى الطلب")),
                ("evidence", models.CharField(max_length=300, verbose_name="ما يثبت الحاجة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "feedback",
                    models.CharField(blank=True, max_length=500, verbose_name="التغذية الراجعة"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التغذية الراجعة"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_attendance_exceptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="قرّره",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_attendance_exceptions",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_exceptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "استثناء حضور (نموذج 03)",
                "verbose_name_plural": "استثناءات الحضور (نموذج 03)",
                "ordering": ["-start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "staff", "status", "start_date"],
                        name="staff_affai_school__384f77_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="attendance_exception_dates_ordered",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrincipalDelegation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل")),
                ("date", models.DateField(verbose_name="اليوم")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="principal_delegations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="النائب المُناب",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="principal_delegations",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "إنابة عن المدير",
                "verbose_name_plural": "الإنابات عن المدير",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "date"), name="one_delegation_per_day"
                    )
                ],
            },
        ),
        migrations.RunPython(_vice_box_is_its_own_stage, _back_to_one_box),
    ]
