# Generated by Django 5.2.17 on 2026-09-16 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _drop_revoked(apps, schema_editor):
    """التراجعُ إلى قيد «إنابةٌ واحدةٌ لليوم»: ما رُفع لا مكانَ له في البنية القديمة.

    البنيةُ القديمة كانت تحذف الإنابةَ عند رفعها، فالتراجعُ يعيدها إلى ذلك؛ وأثرُها
    باقٍ في سجلّ التدقيق (معرّفُ النائب مع كلّ إنشاءٍ ورفع).
    """
    apps.get_model("staff_affairs", "PrincipalDelegation").objects.filter(
        revoked_at__isnull=False
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_auditlog_failed_login_actions"),
        ("staff_affairs", "0008_permit_paper_order_and_coverage_deadline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="principaldelegation",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "إنابة عن المدير",
                "verbose_name_plural": "الإنابات عن المدير",
            },
        ),
        migrations.RemoveConstraint(
            model_name="principaldelegation",
            name="one_delegation_per_day",
        ),
        migrations.AddField(
            model_name="principaldelegation",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="رُفعت في"),
        ),
        migrations.AddField(
            model_name="principaldelegation",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_principal_delegations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رفعها",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, _drop_revoked),
        migrations.AddConstraint(
            model_name="principaldelegation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("school", "date"),
                name="one_active_delegation_per_day",
            ),
        ),
    ]
