# Generated by Django 5.2.17 on 2026-09-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_affairs", "0009_principal_delegation_kept_on_revoke"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffattendance",
            name="absence_disputed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="اعتراض المدير على رصد غيابه"
            ),
        ),
    ]
