# Generated by Django 5.2.17 on 2026-09-21 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدِّل"),
                ),
                (
                    "code",
                    models.CharField(max_length=32, unique=True, verbose_name="الرمز"),
                ),
                (
                    "src",
                    models.CharField(blank=True, max_length=255, verbose_name="المصدر"),
                ),
                ("text", models.TextField(verbose_name="النصّ")),
                ("done", models.BooleanField(default=False, verbose_name="أُنجز")),
                ("sort_order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "بندُ قائمة فحص",
                "verbose_name_plural": "قائمةُ فحص الجهاز",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدِّل"),
                ),
                (
                    "code",
                    models.CharField(max_length=32, unique=True, verbose_name="الرمز"),
                ),
                (
                    "src",
                    models.CharField(blank=True, max_length=16, verbose_name="المصدر"),
                ),
                ("title", models.TextField(verbose_name="القرار")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "مفتوح"),
                            ("decided", "محسوم"),
                            ("deferred", "مؤجَّل"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "decider",
                    models.CharField(blank=True, max_length=64, verbose_name="صاحبُ القرار"),
                ),
                (
                    "due",
                    models.CharField(blank=True, max_length=255, verbose_name="الموعد"),
                ),
                (
                    "decision_date",
                    models.DateField(blank=True, null=True, verbose_name="تاريخُ الحسم"),
                ),
                ("blocks", models.TextField(blank=True, verbose_name="يحجب")),
                ("options", models.TextField(blank=True, verbose_name="الخيارات")),
                (
                    "recommendation",
                    models.TextField(blank=True, verbose_name="التوصية"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "قرارُ خارطة",
                "verbose_name_plural": "قراراتُ الخارطة",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapKpi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدِّل"),
                ),
                (
                    "code",
                    models.CharField(max_length=32, unique=True, verbose_name="الرمز"),
                ),
                (
                    "lane",
                    models.CharField(db_index=True, max_length=32, verbose_name="المسار"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="المؤشّر")),
                (
                    "baseline",
                    models.FloatField(blank=True, null=True, verbose_name="الأساس"),
                ),
                (
                    "current",
                    models.FloatField(blank=True, null=True, verbose_name="الحاليّ"),
                ),
                (
                    "target",
                    models.FloatField(blank=True, null=True, verbose_name="الهدف"),
                ),
                (
                    "baseline_text",
                    models.CharField(blank=True, max_length=255, verbose_name="الأساس (نصّاً)"),
                ),
                (
                    "target_text",
                    models.CharField(blank=True, max_length=255, verbose_name="الهدف (نصّاً)"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("down", "الأقلُّ أفضل"),
                            ("up", "الأعلى أفضل"),
                            ("floor", "حدٌّ أدنى"),
                        ],
                        default="down",
                        max_length=8,
                        verbose_name="الاتّجاه",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=16, verbose_name="الوحدة"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=255, verbose_name="المصدر"),
                ),
                ("why", models.TextField(blank=True, verbose_name="سببُ غياب القياس")),
                (
                    "text_mode",
                    models.BooleanField(default=False, verbose_name="قيمٌ نصّيّة"),
                ),
                (
                    "measured_at",
                    models.DateField(blank=True, null=True, verbose_name="تاريخ القياس"),
                ),
                (
                    "history",
                    models.JSONField(blank=True, default=list, verbose_name="السجلّ"),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="أخرى"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "مؤشّرُ خارطة",
                "verbose_name_plural": "مؤشّراتُ الخارطة",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدِّل"),
                ),
                (
                    "key",
                    models.CharField(
                        default="roadmap",
                        max_length=32,
                        unique=True,
                        verbose_name="المفتاح",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="المحتوى"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "وثيقةُ الخارطة",
                "verbose_name_plural": "وثائقُ الخارطة",
            },
        ),
        migrations.CreateModel(
            name="RoadmapRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدِّل"),
                ),
                (
                    "code",
                    models.CharField(max_length=32, unique=True, verbose_name="الرمز"),
                ),
                (
                    "src",
                    models.CharField(blank=True, max_length=255, verbose_name="المصدر"),
                ),
                ("risk", models.TextField(verbose_name="المخاطرة")),
                (
                    "prob",
                    models.CharField(blank=True, max_length=32, verbose_name="الاحتمال"),
                ),
                (
                    "impact",
                    models.CharField(blank=True, max_length=32, verbose_name="الأثر"),
                ),
                ("mitigation", models.TextField(blank=True, verbose_name="التخفيف")),
                ("sort_order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "مخاطرةٌ في الخارطة",
                "verbose_name_plural": "مخاطرُ الخارطة",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدِّل"),
                ),
                (
                    "code",
                    models.CharField(max_length=32, unique=True, verbose_name="الرمز"),
                ),
                (
                    "src",
                    models.CharField(blank=True, max_length=16, verbose_name="المصدر"),
                ),
                (
                    "lane",
                    models.CharField(db_index=True, max_length=32, verbose_name="المسار"),
                ),
                ("title", models.TextField(verbose_name="العنوان")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "لم يبدأ"),
                            ("doing", "قيد التنفيذ"),
                            ("done", "مُغلَق"),
                            ("blocked", "محجوب"),
                            ("deferred", "مؤجّل"),
                        ],
                        default="todo",
                        max_length=16,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(default=0, verbose_name="التقدّم %"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="البداية"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="النهاية"),
                ),
                (
                    "date_basis",
                    models.CharField(blank=True, max_length=120, verbose_name="أساس التاريخ"),
                ),
                ("effort", models.FloatField(default=1, verbose_name="الجهد (أيّام)")),
                (
                    "deps",
                    models.CharField(blank=True, max_length=255, verbose_name="الاعتماديّات"),
                ),
                (
                    "criterion",
                    models.TextField(blank=True, verbose_name="معيار الإغلاق"),
                ),
                ("note", models.TextField(blank=True, verbose_name="ملاحظة")),
                (
                    "gate",
                    models.CharField(blank=True, max_length=32, verbose_name="البوّابة"),
                ),
                (
                    "ref",
                    models.CharField(blank=True, max_length=255, verbose_name="المرجع"),
                ),
                (
                    "pr",
                    models.CharField(blank=True, max_length=64, verbose_name="طلب الدمج"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "بندُ خارطة",
                "verbose_name_plural": "بنودُ الخارطة",
                "ordering": ["sort_order", "code"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("progress__gte", 0), ("progress__lte", 100)),
                        name="roadmap_item_progress_0_100",
                    )
                ],
            },
        ),
    ]
