# Generated by Django 5.0.6 on 2026-03-19 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_qatar_grading_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsubjectresult',
            options={'verbose_name': 'نتيجة فصل', 'verbose_name_plural': 'نتائج الفصول'},
        ),
        migrations.RenameIndex(
            model_name='annualsubjectresult',
            new_name='assessments_student_7473ca_idx',
            old_name='annual_result_student_idx',
        ),
        migrations.RenameIndex(
            model_name='annualsubjectresult',
            new_name='assessments_status_651c2e_idx',
            old_name='annual_result_status_idx',
        ),
        migrations.RenameIndex(
            model_name='studentassessmentgrade',
            new_name='assessments_student_e6b9d5_idx',
            old_name='assess_grade_student_idx',
        ),
        migrations.RenameIndex(
            model_name='studentassessmentgrade',
            new_name='assessments_assessm_2d92ae_idx',
            old_name='assess_grade_assess_idx',
        ),
        migrations.RenameIndex(
            model_name='studentsubjectresult',
            new_name='assessments_student_0b928a_idx',
            old_name='assess_result_student_idx',
        ),
        migrations.RenameIndex(
            model_name='studentsubjectresult',
            new_name='assessments_setup_i_74fa23_idx',
            old_name='assess_result_setup_idx',
        ),
        migrations.RemoveField(
            model_name='assessmentpackage',
            name='max_grade',
        ),
        migrations.AlterField(
            model_name='assessmentpackage',
            name='package_type',
            field=models.CharField(
                choices=[
                    ('P1', 'الباقة الأولى — أعمال مستمرة'),
                    ('P2', 'الباقة الثانية — اختبارات قصيرة'),
                    ('P3', 'الباقة الثالثة — اختبار منتصف الفصل'),
                    ('P4', 'الباقة الرابعة — اختبار نهائي'),
                ],
                max_length=2,
                verbose_name='نوع الباقة',
            ),
        ),
        migrations.AlterField(
            model_name='assessmentpackage',
            name='semester',
            field=models.CharField(
                choices=[('S1', 'الفصل الأول  (40 درجة)'), ('S2', 'الفصل الثاني (60 درجة)')],
                default='S1',
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name='studentassessmentgrade',
            name='grade',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='الدرجة الخام',
            ),
        ),
        migrations.AlterField(
            model_name='studentsubjectresult',
            name='p1_score',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة الباقة 1'
            ),
        ),
        migrations.AlterField(
            model_name='studentsubjectresult',
            name='p2_score',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة الباقة 2'
            ),
        ),
        migrations.AlterField(
            model_name='studentsubjectresult',
            name='p3_score',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة الباقة 3'
            ),
        ),
        migrations.AlterField(
            model_name='studentsubjectresult',
            name='p4_score',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة الباقة 4'
            ),
        ),
        migrations.AlterField(
            model_name='studentsubjectresult',
            name='semester',
            field=models.CharField(
                choices=[('S1', 'الفصل الأول  (40 درجة)'), ('S2', 'الفصل الثاني (60 درجة)')],
                default='S1',
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name='studentsubjectresult',
            name='total',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='مجموع الفصل'
            ),
        ),
    ]
