# Generated by Django 5.2.12 on 2026-03-26 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_studentsubjectresult_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclasssetup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_setups', to=settings.AUTH_USER_MODEL, verbose_name='المعلم المسؤول'),
        ),
    ]
