# Generated by Django 5.2.12 on 2026-03-30 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_pass_grade_50'),
        ('core', '0028_add_performance_indexes'),
        ('operations', '0010_staffevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subjectclasssetup',
            index=models.Index(fields=['school', 'teacher', 'academic_year'], name='idx_setup_school_teacher_year'),
        ),
    ]
