# Generated by Django 5.2.17 on 2026-08-28 08:05

import core.academic_calendar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0009_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="subjectclasssetup",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
    ]
