# Generated by Django 5.2.17 on 2026-09-15 01:11

import assessments.models
import core.academic_calendar
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_standing(apps, schema_editor):
    """موقفُ الطالب للصفوف القائمة بما كانت تعرضه الشهادةُ قبلُ — حتّى يُشغَّل الحكمُ.

    كانت `reports.views._set_final_status` تقول «راسب» لمن له مادّةٌ راسبة، و«ناجح» لمن
    لا راسبةَ له ونجح في شيء، وإلّا «غير مكتمل». فالصفوفُ القائمة تبقى تُعرض كما كانت
    إلى أن يُعاد حسابُها (`recalculate_grade_results --apply`) بالحكم الواحد.
    """
    Annual = apps.get_model("assessments", "AnnualSubjectResult")
    by_student: dict = {}
    for sid, year, status in Annual.objects.values_list("student_id", "academic_year", "status"):
        by_student.setdefault((sid, year), set()).add(status)
    for (sid, year), statuses in by_student.items():
        if "fail" in statuses:
            standing = "failed"
        elif "second_round" in statuses:
            standing = "second_round"
        elif "pass" in statuses:
            standing = "passed"
        else:
            continue
        Annual.objects.filter(student_id=sid, academic_year=year).update(standing=standing)


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_alter_annualsubjectresult_academic_year_and_more'),
        ('core', '0066_auditlog_failed_login_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annualsubjectresult',
            name='article',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='annualsubjectresult',
            name='mark',
            field=models.CharField(blank=True, choices=[('absent', 'غائب'), ('excused', 'معذور'), ('deprived', 'محروم')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='annualsubjectresult',
            name='second_round_absent',
            field=models.BooleanField(default=False, verbose_name='غائب في الدور الثاني'),
        ),
        migrations.AddField(
            model_name='annualsubjectresult',
            name='second_round_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درجة الدور الثاني'),
        ),
        migrations.AddField(
            model_name='annualsubjectresult',
            name='standing',
            field=models.CharField(choices=[('passed', 'ناجح'), ('promoted', 'ناجح بالترفيع'), ('second_round', 'دور ثانٍ'), ('failed', 'راسب'), ('incomplete', 'غير مكتمل')], db_index=True, default='incomplete', max_length=12),
        ),
        migrations.AlterField(
            model_name='annualsubjectresult',
            name='status',
            field=models.CharField(choices=[('pass', 'ناجح'), ('promoted', 'مُرفَّع'), ('fail', 'راسب'), ('second_round', 'راسب — دور ثانٍ'), ('excused', 'معذور — دور ثانٍ'), ('deprived', 'محروم — دور ثانٍ'), ('makeup', 'بانتظار الملحق'), ('incomplete', 'غير مكتمل')], db_index=True, default='incomplete', max_length=12),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('exam', 'اختبار'), ('quiz', 'اختبار قصير'), ('homework', 'واجب'), ('project', 'مشروع'), ('classwork', 'عمل صفي'), ('oral', 'شفهي'), ('practical', 'عملي'), ('participation', 'مشاركة صفية'), ('makeup', 'اختبار ملحق')], default='exam', max_length=15),
        ),
        migrations.CreateModel(
            name='ExamDeprivation',
            fields=[
                ('id', models.UUIDField(default=assessments.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(default=core.academic_calendar.default_academic_year, max_length=9)),
                ('gate', models.CharField(choices=[('s1_midterm', 'اختبار منتصف الفصل الأول'), ('s1_final', 'اختبار نهاية الفصل الأول'), ('s2_midterm', 'اختبار منتصف الفصل الثاني'), ('s2_final', 'اختبار نهاية الفصل الثاني (الدور الأول)')], max_length=12, verbose_name='الاختبار')),
                ('deprived', models.BooleanField(default=True, verbose_name='محروم')),
                ('decided_on', models.DateField(verbose_name='تاريخ القرار')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='سجّله')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_deprivations', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_deprivations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قرار أهليّة اختبار',
                'verbose_name_plural': 'قرارات أهليّة الاختبارات',
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year', 'gate'), name='unique_exam_deprivation')],
            },
        ),
        migrations.RunPython(backfill_standing, migrations.RunPython.noop),
    ]
