# Generated by Django 5.2.17 on 2026-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_rls_exam_deprivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualsubjectresult',
            name='review',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
