# Generated by Django 5.2.17 on 2026-09-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0013_verdict_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualsubjectresult",
            name="second_round_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="قصوى اختبار الدور الثاني",
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="mark",
            field=models.CharField(
                blank=True,
                choices=[
                    ("absent", "غائب"),
                    ("excused", "معذور"),
                    ("deprived", "محروم"),
                    ("cancelled", "ملغي"),
                ],
                default="", db_default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("pass", "ناجح"),
                    ("promoted", "مُرفَّع"),
                    ("fail", "راسب"),
                    ("cancelled", "ملغي"),
                    ("second_round", "راسب — دور ثانٍ"),
                    ("excused", "معذور — دور ثانٍ"),
                    ("deprived", "محروم — دور ثانٍ"),
                    ("makeup", "بانتظار الملحق"),
                    ("incomplete", "غير مكتمل"),
                ],
                db_index=True,
                default="incomplete",
                max_length=12,
            ),
        ),
    ]
