# Generated by Django 5.2.17 on 2026-09-16 19:39

import assessments.models
import core.academic_calendar
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0014_verdict_cancelled_second_round_max"),
        ("core", "0066_auditlog_failed_login_actions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # الصفوفُ القائمة كتبتها قواعدُ ما قبل الحكم الواحد (0)، فلا يُعاد حسابُها جزئيّاً حتّى
        # `recalculate_grade_results --apply`؛ وما يُكتب بعدها بالإصدار الجاري (1).
        migrations.AddField(
            model_name="annualsubjectresult",
            name="ruleset",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="إصدار قواعد الحكم"),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="ruleset",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="إصدار قواعد الحكم"),
        ),
        migrations.AddField(
            model_name="subjectclasssetup",
            name="has_pass_mark",
            field=models.BooleanField(
                blank=True,
                help_text="فارغ: من ملحق سياسة التقييم (الفنية للسابع–التاسع، والبدنية للثاني عشر، والبرامج الإثرائية ليست مواد نجاح ورسوب). يُصرَّح هنا لمادّةٍ لا يسمّيها الملحق.",
                null=True,
                verbose_name="مادة نجاح ورسوب",
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="mark",
            field=models.CharField(
                blank=True,
                choices=[
                    ("absent", "غائب"),
                    ("excused", "معذور"),
                    ("deprived", "محروم"),
                    ("cancelled", "ملغي"),
                    ("cheating", "غش"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("pass", "ناجح"),
                    ("promoted", "مُرفَّع"),
                    ("fail", "راسب"),
                    ("cancelled", "ملغي"),
                    ("second_round", "راسب — دور ثانٍ"),
                    ("excused", "معذور — دور ثانٍ"),
                    ("deprived", "محروم — دور ثانٍ"),
                    ("makeup", "بانتظار الملحق"),
                    ("incomplete", "غير مكتمل"),
                    ("no_pass_mark", "ليست مادة نجاح ورسوب"),
                ],
                db_index=True,
                default="incomplete",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="ExamMisconduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=assessments.models._uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        default=core.academic_calendar.default_academic_year,
                        max_length=9,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cheating", "غش في اختبار مادة"),
                            ("cancelled", "ملغي — كل المواد"),
                        ],
                        max_length=10,
                        verbose_name="الواقعة",
                    ),
                ),
                (
                    "exam",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("s1_midterm", "اختبار منتصف الفصل الأول"),
                            ("s1_final", "اختبار نهاية الفصل الأول أو الملحق"),
                            ("s2_midterm", "اختبار منتصف الفصل الثاني"),
                            ("s2_final", "اختبار نهاية الفصل الثاني"),
                            ("second_round", "اختبار الدور الثاني"),
                        ],
                        max_length=12,
                        verbose_name="الاختبار (للغش)",
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "policy",
                                "م45 / م32 — تكرارُ الغش أو الإخلال، أو إساءةٌ في ورقة الإجابة، أو اعتداءٌ بالقول",
                            ),
                            (
                                "dismissal",
                                "م46 / م34 — اعتداءٌ بالفعل على القائمين بأعمال الاختبارات",
                            ),
                            (
                                "decree30",
                                "م45 مكرر / م33 مكرر — حيازةُ هاتفٍ أو جهازٍ أو مشاركةٌ بقصد الغش (قرار 30/2018)",
                            ),
                            (
                                "decree30_1",
                                "م45 مكرر 1 / م33 مكرر 1 — تصويرُ أو نشرُ أسئلة أو أجوبة اختبار (قرار 30/2018)",
                            ),
                        ],
                        max_length=10,
                        verbose_name="السند (للإلغاء)",
                    ),
                ),
                (
                    "report_ref",
                    models.CharField(blank=True, max_length=60, verbose_name="رقم المحضر"),
                ),
                ("decided_on", models.DateField(verbose_name="تاريخ القرار")),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="ملاحظة"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سجّله",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_misconducts",
                        to="core.school",
                    ),
                ),
                (
                    "setup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misconducts",
                        to="assessments.subjectclasssetup",
                        verbose_name="المادة (للغش)",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_misconducts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "واقعة انضباط اختبار",
                "verbose_name_plural": "وقائع انضباط الاختبارات",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "cheating")),
                        fields=("student", "setup", "exam"),
                        name="unique_exam_cheating",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "cancelled")),
                        fields=("student", "academic_year"),
                        name="unique_exam_cancelled",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("basis", ""),
                                ("kind", "cheating"),
                                ("setup__isnull", False),
                                models.Q(("exam", ""), _negated=True),
                            ),
                            models.Q(
                                ("exam", ""),
                                ("kind", "cancelled"),
                                ("setup__isnull", True),
                                models.Q(("basis", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="exam_misconduct_shape",
                    ),
                ],
            },
        ),
    ]
