# Generated by Django 5.2.17 on 2026-09-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0016_rls_exam_misconduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="review",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
