# Generated by Django 5.2.17 on 2026-09-24 05:40

import core.academic_calendar
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0017_alter_annualsubjectresult_review"),
        ("core", "0071_arabic_field_labels"),
        ("operations", "0057_arabic_field_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="article",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=40,
                verbose_name="المادّة من السياسة",
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="mark",
            field=models.CharField(
                blank=True,
                choices=[
                    ("absent", "غائب"),
                    ("excused", "معذور"),
                    ("deprived", "محروم"),
                    ("cancelled", "ملغي"),
                    ("cheating", "غش"),
                ],
                db_default="",
                default="",
                max_length=10,
                verbose_name="بدل المجموع",
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="review",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=500,
                verbose_name="تنبيه للمراجعة",
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annual_results",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="setup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annual_results",
                to="assessments.subjectclasssetup",
                verbose_name="إعداد المادّة للشعبة",
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="standing",
            field=models.CharField(
                choices=[
                    ("passed", "ناجح"),
                    ("promoted", "ناجح بالترفيع"),
                    ("second_round", "دور ثانٍ"),
                    ("failed", "راسب"),
                    ("incomplete", "غير مكتمل"),
                ],
                db_default="incomplete",
                db_index=True,
                default="incomplete",
                max_length=12,
                verbose_name="الموقف",
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("pass", "ناجح"),
                    ("promoted", "مُرفَّع"),
                    ("fail", "راسب"),
                    ("cancelled", "ملغي"),
                    ("second_round", "راسب — دور ثانٍ"),
                    ("excused", "معذور — دور ثانٍ"),
                    ("deprived", "محروم — دور ثانٍ"),
                    ("makeup", "بانتظار الملحق"),
                    ("incomplete", "غير مكتمل"),
                    ("no_pass_mark", "ليست مادة نجاح ورسوب"),
                ],
                db_index=True,
                default="incomplete",
                max_length=12,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annual_results",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="annualsubjectresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("exam", "اختبار"),
                    ("quiz", "اختبار قصير"),
                    ("homework", "واجب"),
                    ("project", "مشروع"),
                    ("classwork", "عمل صفي"),
                    ("oral", "شفهي"),
                    ("practical", "عملي"),
                    ("participation", "مشاركة صفية"),
                    ("makeup", "اختبار ملحق"),
                ],
                default="exam",
                max_length=15,
                verbose_name="نوع التقييم",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assessments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأه",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="assessments.assessmentpackage",
                verbose_name="حزمة التقييم",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("published", "منشور"),
                    ("graded", "مصحَّح"),
                    ("closed", "مغلق"),
                ],
                db_index=True,
                default="draft",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentpackage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="assessmentpackage",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="assessmentpackage",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentpackage",
            name="semester",
            field=models.CharField(
                choices=[
                    ("S1", "الفصل الأول  (40 درجة)"),
                    ("S2", "الفصل الثاني (60 درجة)"),
                ],
                default="S1",
                max_length=2,
                verbose_name="الفصل الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentpackage",
            name="setup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="assessments.subjectclasssetup",
                verbose_name="إعداد المادّة للشعبة",
            ),
        ),
        migrations.AlterField(
            model_name="examdeprivation",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="examdeprivation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="examdeprivation",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_deprivations",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="examdeprivation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_deprivations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="exammisconduct",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="exammisconduct",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="exammisconduct",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_misconducts",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="exammisconduct",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_misconducts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="studentassessmentgrade",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="assessments.assessment",
                verbose_name="التقييم",
            ),
        ),
        migrations.AlterField(
            model_name="studentassessmentgrade",
            name="entered_at",
            field=models.DateTimeField(auto_now=True, verbose_name="وقت الرصد"),
        ),
        migrations.AlterField(
            model_name="studentassessmentgrade",
            name="entered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entered_grades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رصده",
            ),
        ),
        migrations.AlterField(
            model_name="studentassessmentgrade",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_grades",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="studentassessmentgrade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_grades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="studentsubjectresult",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_results",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="studentsubjectresult",
            name="semester",
            field=models.CharField(
                choices=[
                    ("S1", "الفصل الأول  (40 درجة)"),
                    ("S2", "الفصل الثاني (60 درجة)"),
                ],
                default="S1",
                max_length=2,
                verbose_name="الفصل الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="studentsubjectresult",
            name="setup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_results",
                to="assessments.subjectclasssetup",
                verbose_name="إعداد المادّة للشعبة",
            ),
        ),
        migrations.AlterField(
            model_name="studentsubjectresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_results",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="studentsubjectresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="subjectclasssetup",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="subjectclasssetup",
            name="class_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_setups",
                to="core.classgroup",
                verbose_name="الشعبة",
            ),
        ),
        migrations.AlterField(
            model_name="subjectclasssetup",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="subjectclasssetup",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_setups",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="subjectclasssetup",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_setups",
                to="operations.subject",
                verbose_name="المادّة",
            ),
        ),
    ]
