# Generated by Django 6.0.3 on 2026-03-18 19:48

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=core.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم المدرسة')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='الكود')),
                ('city', models.CharField(default='الشحانية', max_length=100, verbose_name='المدينة')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مدرسة',
                'verbose_name_plural': 'المدارس',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=core.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('national_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='الرقم الوطني')),
                ('full_name', models.CharField(db_index=True, max_length=200, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الجوال')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف شخصي',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=core.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('principal', 'مدير المدرسة'), ('vice_admin', 'النائب الإداري'), ('vice_academic', 'النائب الأكاديمي'), ('coordinator', 'منسق'), ('teacher', 'معلم'), ('specialist', 'أخصائي'), ('admin', 'إداري'), ('student', 'طالب'), ('parent', 'ولي أمر')], max_length=30)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.school')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=core.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='core.role')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.school')),
            ],
            options={
                'verbose_name': 'عضوية',
                'verbose_name_plural': 'العضويات',
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.UUIDField(default=core.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('G7', 'الصف السابع'), ('G8', 'الصف الثامن'), ('G9', 'الصف التاسع'), ('G10', 'الصف العاشر'), ('G11', 'الصف الحادي عشر'), ('G12', 'الصف الثاني عشر')], max_length=3)),
                ('section', models.CharField(max_length=10, verbose_name='الشعبة')),
                ('level_type', models.CharField(choices=[('prep', 'إعدادي'), ('sec', 'ثانوي')], default='prep', max_length=4)),
                ('academic_year', models.CharField(default='2025-2026', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_classes', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='core.school')),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=core.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateField(default=django.utils.timezone.now)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.classgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تسجيل طالب',
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_role_per_school'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['school', 'role'], name='core_member_school__091898_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'school', 'role'), name='unique_active_membership'),
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['school', 'grade', 'academic_year'], name='core_classg_school__59c906_idx'),
        ),
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.UniqueConstraint(fields=('school', 'grade', 'section', 'academic_year'), name='unique_class_per_year'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'class_group'), name='unique_active_enrollment'),
        ),
    ]
