# Generated by Django 5.0.6 on 2026-03-19 02:40

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parent_student_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentstudentlink',
            name='id',
            field=models.UUIDField(
                default=core.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(
                choices=[
                    ('principal', 'مدير المدرسة'),
                    ('vice_admin', 'النائب الإداري'),
                    ('vice_academic', 'النائب الأكاديمي'),
                    ('coordinator', 'منسق'),
                    ('teacher', 'معلم'),
                    ('specialist', 'أخصائي'),
                    ('nurse', 'ممرض/ة'),
                    ('librarian', 'أمين مكتبة'),
                    ('bus_supervisor', 'مشرف باص'),
                    ('admin', 'إداري'),
                    ('student', 'طالب'),
                    ('parent', 'ولي أمر'),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name='BehaviorInfraction',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=core.models._uuid, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('date', models.DateField(auto_now_add=True)),
                (
                    'level',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'الدرجة الأولى (بسيطة)'),
                            (2, 'الدرجة الثانية (متوسطة)'),
                            (3, 'الدرجة الثالثة (جسيمة)'),
                            (4, 'الدرجة الرابعة (شديدة الخطورة)'),
                        ],
                        default=1,
                    ),
                ),
                ('description', models.TextField(verbose_name='وصف المخالفة')),
                ('action_taken', models.TextField(blank=True, verbose_name='الإجراء المتخذ')),
                (
                    'points_deducted',
                    models.PositiveIntegerField(default=0, verbose_name='النقاط المخصومة'),
                ),
                ('is_resolved', models.BooleanField(default=False)),
                (
                    'reported_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reported_infractions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.school'
                    ),
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='behavior_infractions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'مخالفة سلوكية',
                'verbose_name_plural': 'المخالفات السلوكية',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorPointRecovery',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=core.models._uuid, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('reason', models.TextField(verbose_name='سبب استعادة النقاط (سلوك إيجابي)')),
                ('points_restored', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                (
                    'approved_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'infraction',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recovery',
                        to='core.behaviorinfraction',
                    ),
                ),
            ],
            options={
                'verbose_name': 'استعادة نقاط',
                'verbose_name_plural': 'استعادة النقاط',
            },
        ),
        migrations.CreateModel(
            name='ClinicVisit',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=core.models._uuid, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(verbose_name='سبب الزيارة')),
                ('symptoms', models.TextField(blank=True, verbose_name='الأعراض')),
                (
                    'temperature',
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                ('treatment', models.TextField(blank=True, verbose_name='الإجراء المتخذ')),
                (
                    'is_sent_home',
                    models.BooleanField(default=False, verbose_name='تم إرساله للمنزل'),
                ),
                (
                    'parent_notified',
                    models.BooleanField(default=False, verbose_name='تم إبلاغ ولي الأمر'),
                ),
                (
                    'nurse',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='nurse_visits',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.school'
                    ),
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clinic_visits',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'زيارة عيادة',
                'verbose_name_plural': 'زيارات العيادة',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=core.models._uuid, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'blood_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('A+', 'A+'),
                            ('A-', 'A-'),
                            ('B+', 'B+'),
                            ('B-', 'B-'),
                            ('AB+', 'AB+'),
                            ('AB-', 'AB-'),
                            ('O+', 'O+'),
                            ('O-', 'O-'),
                        ],
                        max_length=3,
                    ),
                ),
                ('allergies', models.TextField(blank=True, verbose_name='الحساسية')),
                ('chronic_diseases', models.TextField(blank=True, verbose_name='الأمراض المزمنة')),
                ('medications', models.TextField(blank=True, verbose_name='الأدوية المستمرة')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'student',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='health_record',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'سجل صحي',
                'verbose_name_plural': 'السجلات الصحية',
            },
        ),
        migrations.CreateModel(
            name='LibraryActivity',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=core.models._uuid, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('title', models.CharField(max_length=200, verbose_name='اسم النشاط')),
                ('description', models.TextField(verbose_name='وصف النشاط')),
                ('date', models.DateField()),
                ('outcome', models.TextField(blank=True, verbose_name='مخرجات النشاط')),
                (
                    'participants',
                    models.ManyToManyField(
                        related_name='library_activities',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='المشاركون',
                    ),
                ),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.school'
                    ),
                ),
            ],
            options={
                'verbose_name': 'نشاط مكتبة',
                'verbose_name_plural': 'أنشطة المكتبة',
            },
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=core.models._uuid, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('title', models.CharField(max_length=500, verbose_name='عنوان الكتاب')),
                ('author', models.CharField(max_length=200, verbose_name='المؤلف')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                (
                    'category',
                    models.CharField(max_length=100, verbose_name='التصنيف (ديوي العشري)'),
                ),
                (
                    'book_type',
                    models.CharField(
                        choices=[
                            ('PRINT', 'مطبوع'),
                            ('DIGITAL', 'رقمي / PDF'),
                            ('PERIODICAL', 'دورية / مجلة'),
                        ],
                        default='PRINT',
                        max_length=20,
                    ),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(default=1, verbose_name='الكمية المتوفرة'),
                ),
                (
                    'available_qty',
                    models.PositiveIntegerField(default=1, verbose_name='الكمية المتاحة للإعارة'),
                ),
                (
                    'digital_file',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='library/digital/',
                        verbose_name='الملف الرقمي',
                    ),
                ),
                (
                    'location',
                    models.CharField(blank=True, max_length=100, verbose_name='موقع الكتاب (الرف)'),
                ),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='library_books',
                        to='core.school',
                    ),
                ),
            ],
            options={
                'verbose_name': 'كتاب مكتبة',
                'verbose_name_plural': 'كتب المكتبة',
            },
        ),
        migrations.CreateModel(
            name='BookBorrowing',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=core.models._uuid, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(verbose_name='تاريخ الإرجاع المتوقع')),
                (
                    'return_date',
                    models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع الفعلي'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('BORROWED', 'قيد الإعارة'),
                            ('RETURNED', 'تم الإرجاع'),
                            ('OVERDUE', 'متأخر'),
                            ('LOST', 'مفقود'),
                        ],
                        default='BORROWED',
                        max_length=20,
                    ),
                ),
                (
                    'librarian',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='processed_borrowings',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='أمين المكتبة',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='borrowed_books',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='المستعير',
                    ),
                ),
                (
                    'book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='borrowings',
                        to='core.librarybook',
                    ),
                ),
            ],
            options={
                'verbose_name': 'عملية إعارة',
                'verbose_name_plural': 'عمليات الإعارة',
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolBus',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=core.models._uuid, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('bus_number', models.CharField(max_length=20, verbose_name='رقم الحافلة')),
                ('driver_name', models.CharField(max_length=200, verbose_name='اسم السائق')),
                ('driver_phone', models.CharField(max_length=20, verbose_name='جوال السائق')),
                ('capacity', models.PositiveIntegerField(default=30)),
                (
                    'karwa_id',
                    models.CharField(blank=True, max_length=50, verbose_name='رقم كروة (Karwa ID)'),
                ),
                ('gps_link', models.URLField(blank=True, verbose_name='رابط التتبع (GPS)')),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='buses',
                        to='core.school',
                    ),
                ),
                (
                    'supervisor',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='supervised_buses',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='مشرف الباص',
                    ),
                ),
            ],
            options={
                'verbose_name': 'حافلة مدرسية',
                'verbose_name_plural': 'الحافلات المدرسية',
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=core.models._uuid, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('area_name', models.CharField(max_length=200, verbose_name='المنطقة')),
                (
                    'students',
                    models.ManyToManyField(
                        related_name='bus_routes',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='الطلاب',
                    ),
                ),
                (
                    'bus',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='routes',
                        to='core.schoolbus',
                    ),
                ),
            ],
            options={
                'verbose_name': 'خط سير',
                'verbose_name_plural': 'خطوط السير',
            },
        ),
    ]
