# Generated by Django 5.0.6 on 2026-03-19 19:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog_consentrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='behaviorinfraction',
            options={
                'ordering': ['-date', '-created_at'],
                'verbose_name': 'مخالفة سلوكية',
                'verbose_name_plural': 'المخالفات السلوكية',
            },
        ),
        migrations.AlterModelOptions(
            name='bookborrowing',
            options={
                'ordering': ['-borrow_date', '-id'],
                'verbose_name': 'عملية إعارة',
                'verbose_name_plural': 'عمليات الإعارة',
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_school__3d6e5f_idx',
            old_name='auditlog_school_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_model_n_3fb686_idx',
            old_name='auditlog_model_obj_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_id_7b678c_idx',
            old_name='auditlog_user_ts_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.UUIDField(
                default=core.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='id',
            field=models.UUIDField(
                default=core.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
