# Generated by Django 5.0.6 on 2026-03-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_consent_given_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إعطاء الموافقة'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_password_change',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='آخر تغيير لكلمة المرور'
            ),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مقفل حتى'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='يجب تغيير كلمة المرور'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA مفعّل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, verbose_name='مفتاح 2FA'),
        ),
    ]
