# Generated by Django 5.2.12 on 2026-03-21 11:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_breachreport'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='breachreport',
            new_name='core_breach_school__aa7243_idx',
            old_name='breach_school_status_idx',
        ),
        migrations.RenameIndex(
            model_name='breachreport',
            new_name='core_breach_discove_861576_idx',
            old_name='breach_discovered_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(
                choices=[
                    ('HealthRecord', 'سجل صحي'),
                    ('BehaviorInfraction', 'مخالفة سلوكية'),
                    ('StudentSubjectResult', 'درجة طالب'),
                    ('ClinicVisit', 'زيارة عيادة'),
                    ('CustomUser', 'مستخدم'),
                    ('ParentStudentLink', 'ربط ولي أمر'),
                    ('BookBorrowing', 'إعارة كتاب'),
                    ('ConsentRecord', 'سجل موافقة'),
                    ('StudentAssessmentGrade', 'درجة تقييم'),
                    ('other', 'أخرى'),
                ],
                default='other',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='breachreport',
            name='id',
            field=models.UUIDField(
                default=core.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
