# Generated by Django 5.2.12 on 2026-03-21 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_breach_school_status_idx_core_breach_school__aa7243_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم الوطني يجب أن يحتوي على أرقام فقط (5-20 رقم)', regex='^\\d{5,20}$')], verbose_name='الرقم الوطني'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الجوال غير صحيح — استخدم صيغة دولية مثل +97455xxxxxx', regex='^\\+?[\\d\\s\\-]{7,20}$')], verbose_name='الجوال'),
        ),
    ]
