# Generated by Django 5.2.12 on 2026-03-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_search_indexes_and_pg_trgm'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlog_school_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlog_user_action_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='user_full_name_gin_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='user_is_active_btree_idx',
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='membership_school_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='membership_user_school_idx',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('principal', 'مدير المدرسة'), ('vice_admin', 'النائب الإداري'), ('vice_academic', 'النائب الأكاديمي'), ('coordinator', 'منسق'), ('teacher', 'معلم'), ('specialist', 'أخصائي'), ('nurse', 'ممرض/ة'), ('librarian', 'أمين مكتبة'), ('bus_supervisor', 'مشرف باص'), ('admin', 'إداري'), ('student', 'طالب'), ('parent', 'ولي أمر'), ('platform_developer', 'مطور المنصة')], max_length=30),
        ),
    ]
