# Generated by Django 5.2.12 on 2026-03-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auditlog_immutable_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='مفتاح 2FA'),
        ),
    ]
