# Generated by Django 5.2.12 on 2026-03-22 11:49

import core.models.school
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fix_totp_secret_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErasureRequest',
            fields=[
                ('id', models.UUIDField(default=core.models.school._uuid, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='سبب الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('processing', 'جارٍ التنفيذ'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], default='pending', max_length=12)),
                ('review_note', models.TextField(blank=True, verbose_name='ملاحظات المراجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('anonymized_id', models.CharField(blank=True, help_text='مثل: ERASED-0001', max_length=20, verbose_name='المعرّف المجهّل')),
                ('summary', models.JSONField(blank=True, null=True, verbose_name='ملخص البيانات المحذوفة')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_reviewed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erasure_requests', to='core.school')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب حق المحو',
                'verbose_name_plural': 'طلبات حق المحو',
                'ordering': ['-created_at'],
            },
        ),
    ]
