# Generated by Django 5.2.12 on 2026-03-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_erasure_request_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='مثلاً: SHH', max_length=10, verbose_name='الاختصار'),
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان التفصيلي'),
        ),
        migrations.AddField(
            model_name='school',
            name='education_level',
            field=models.CharField(choices=[('primary', 'ابتدائي'), ('preparatory', 'إعدادي'), ('secondary', 'ثانوي'), ('prep_sec', 'إعدادي + ثانوي'), ('all', 'جميع المراحل')], default='prep_sec', max_length=15, verbose_name='المرحلة الدراسية'),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='school',
            name='established_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سنة التأسيس'),
        ),
        migrations.AddField(
            model_name='school',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='الفاكس'),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text='يُفضل PNG شفاف بحجم 200x200 بكسل على الأقل', null=True, upload_to='schools/logos/', verbose_name='شعار المدرسة'),
        ),
        migrations.AddField(
            model_name='school',
            name='ministry_code',
            field=models.CharField(blank=True, help_text='رمز المدرسة في وزارة التربية والتعليم', max_length=20, verbose_name='رمز الوزارة'),
        ),
        migrations.AddField(
            model_name='school',
            name='po_box',
            field=models.CharField(blank=True, max_length=20, verbose_name='صندوق البريد'),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم المدير'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('boys', 'بنين'), ('girls', 'بنات'), ('mixed', 'مختلط')], default='boys', max_length=10, verbose_name='نوع المدرسة'),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AddField(
            model_name='school',
            name='zone',
            field=models.CharField(blank=True, max_length=100, verbose_name='المنطقة / الحي'),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='كود المدرسة'),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='الهاتف'),
        ),
    ]
