# Generated by Django 5.2.12 on 2026-03-24 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_school_abbreviation_school_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='principal_name',
        ),
        migrations.AddField(
            model_name='school',
            name='principal',
            field=models.ForeignKey(blank=True, help_text='اختر المدير من قائمة المستخدمين', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_of', to=settings.AUTH_USER_MODEL, verbose_name='المدير'),
        ),
    ]
