# Generated by Django 5.2.12 on 2026-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_school_principal_name_school_principal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consentrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customuser',
            name='national_id_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='الرقم الوطني (مشفّر)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='national_id_hmac',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='HMAC الرقم الوطني'),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.UniqueConstraint(fields=('parent', 'student', 'data_type'), name='unique_consent_record'),
        ),
    ]
