# Generated by Django 5.2.12 on 2026-03-24 11:50
# Data migration: تشفير كل الـ national_id الموجودة بـ HMAC + Fernet

from django.db import migrations


def populate_hmac_encrypted(apps, schema_editor):
    """تعبئة الحقول المشفّرة لكل المستخدمين الحاليين."""
    from core.models._crypto import encrypt_field, hmac_field

    CustomUser = apps.get_model("core", "CustomUser")
    batch_size = 500
    users = CustomUser.objects.all()
    total = users.count()
    updated = 0

    for i in range(0, total, batch_size):
        batch = list(users[i : i + batch_size])
        for user in batch:
            if user.national_id:
                user.national_id_hmac = hmac_field(user.national_id)
                encrypted = encrypt_field(user.national_id)
                if encrypted:
                    user.national_id_encrypted = encrypted
        CustomUser.objects.bulk_update(
            batch, ["national_id_hmac", "national_id_encrypted"], batch_size=batch_size
        )
        updated += len(batch)

    if total:
        print(f"\n  [OK] Encrypted {updated}/{total} national_id fields (HMAC + Fernet)")


def reverse_noop(apps, schema_editor):
    """No-op reverse — الحقول تبقى لكن يمكن تجاهلها."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_add_national_id_hmac_encrypted"),
    ]

    operations = [
        migrations.RunPython(populate_hmac_encrypted, reverse_noop),
    ]
