# Generated by Django 5.2.12 on 2026-03-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_postgresql_rls_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='department',
            field=models.CharField(blank=True, db_index=True, default='', help_text='مثال: رياضيات، علوم، لغة عربية — يُستخدم لتقييد صلاحيات المنسق بتخصصه', max_length=60, verbose_name='القسم / التخصص'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('principal', 'مدير المدرسة'), ('vice_admin', 'النائب الإداري'), ('vice_academic', 'النائب الأكاديمي'), ('coordinator', 'منسق أكاديمي'), ('admin_supervisor', 'مشرف إداري'), ('teacher', 'معلم'), ('social_worker', 'أخصائي اجتماعي'), ('psychologist', 'أخصائي نفسي'), ('academic_advisor', 'مرشد أكاديمي'), ('ese_teacher', 'معلم تربية خاصة'), ('nurse', 'ممرض/ة'), ('librarian', 'أمين مصادر التعلم'), ('it_technician', 'فني تقنية معلومات'), ('bus_supervisor', 'مشرف نقل مدرسي'), ('admin', 'إداري'), ('secretary', 'سكرتير المدرسة'), ('specialist', 'أخصائي (قديم)'), ('student', 'طالب'), ('parent', 'ولي أمر'), ('platform_developer', 'مطور المنصة')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['department'], name='idx_active_dept'),
        ),
    ]
