# Generated by Django 5.2.12 on 2026-03-26 05:34

import core.models.school
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_membership_department_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='department',
            field=models.CharField(blank=True, db_index=True, default='', help_text='⚠ حقل قديم — سيُحذف بعد اكتمال الترحيل إلى department_obj', max_length=60, verbose_name='القسم / التخصص (نص — قديم)'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=core.models.school._uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='مثال: الرياضيات، اللغة العربية', max_length=60, verbose_name='اسم القسم')),
                ('code', models.CharField(help_text='كود ثابت للبرمجة — مثال: math, arabic, english', max_length=30, verbose_name='كود القسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='المنسق (رئيس القسم)')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'قسم أكاديمي',
                'verbose_name_plural': 'الأقسام الأكاديمية',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='department_obj',
            field=models.ForeignKey(blank=True, help_text='القسم من جدول الأقسام — يحل محل حقل department النصي', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.department', verbose_name='القسم الأكاديمي'),
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=core.models.school._uuid, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('role_assigned', 'تعيين دور'), ('role_removed', 'إزالة دور'), ('dept_changed', 'تغيير القسم'), ('dept_head_set', 'تعيين منسق'), ('dept_head_removed', 'إزالة منسق'), ('account_disabled', 'تعطيل حساب'), ('account_enabled', 'تفعيل حساب'), ('substitute_assigned', 'تعيين بديل'), ('swap_approved', 'موافقة تبديل'), ('swap_rejected', 'رفض تبديل'), ('compensatory_approved', 'موافقة تعويض')], max_length=30, verbose_name='نوع الإجراء')),
                ('details', models.JSONField(blank=True, default=dict, help_text='مثال: {"old_dept": "الرياضيات", "new_dept": "العلوم"}', verbose_name='تفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت التنفيذ')),
                ('actor', models.ForeignKey(help_text='من نفّذ التغيير', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_logs', to='core.school', verbose_name='المدرسة')),
                ('target', models.ForeignKey(help_text='على من تم التغيير', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perm_audit_targets', to=settings.AUTH_USER_MODEL, verbose_name='المستهدف')),
            ],
            options={
                'verbose_name': 'سجل تغيير صلاحيات',
                'verbose_name_plural': 'سجلات تغيير الصلاحيات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['school', 'is_active'], name='core_depart_school__6251b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_dept_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_dept_code_per_school'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['school', '-created_at'], name='core_permis_school__48a872_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['actor', '-created_at'], name='core_permis_actor_i_6c670e_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['target', '-created_at'], name='core_permis_target__908720_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['action'], name='core_permis_action_d78d0a_idx'),
        ),
    ]
