# Generated by Django 5.2.12 on 2026-03-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_department_and_permission_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='professional_license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الرخصة المهنية'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='professional_license_number',
            field=models.CharField(blank=True, default='', help_text='رقم الرخصة الصادرة من وزارة التعليم والتعليم العالي', max_length=50, verbose_name='رقم الرخصة المهنية'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(choices=[('HealthRecord', 'سجل صحي'), ('BehaviorInfraction', 'مخالفة سلوكية'), ('StudentSubjectResult', 'درجة طالب'), ('ClinicVisit', 'زيارة عيادة'), ('CustomUser', 'مستخدم'), ('ParentStudentLink', 'ربط ولي أمر'), ('BookBorrowing', 'إعارة كتاب'), ('ConsentRecord', 'سجل موافقة'), ('StudentAssessmentGrade', 'درجة تقييم'), ('StaffEvaluation', 'تقييم أداء موظف'), ('other', 'أخرى')], default='other', max_length=50),
        ),
    ]
