# Generated by Django 5.2.12 on 2026-03-27 09:27

import core.models.school
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customuser_professional_license_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=core.models.school._uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='مثال: 2025-2026', max_length=9, verbose_name='العام الدراسي')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_current', models.BooleanField(default=False, verbose_name='العام الحالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'عام دراسي',
                'verbose_name_plural': 'الأعوام الدراسية',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_academic_year_per_school'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('school',), name='unique_current_academic_year_per_school')],
            },
        ),
    ]
