# Generated by Django 5.2.12 on 2026-03-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_customuser_phone_encrypted_phone_hmac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('principal', 'مدير المدرسة'), ('vice_admin', 'النائب الإداري'), ('vice_academic', 'النائب الأكاديمي'), ('coordinator', 'منسق أكاديمي'), ('admin_supervisor', 'مشرف إداري'), ('teacher', 'معلم'), ('social_worker', 'أخصائي اجتماعي'), ('psychologist', 'أخصائي نفسي'), ('academic_advisor', 'مرشد أكاديمي'), ('ese_teacher', 'معلم تربية خاصة'), ('nurse', 'ممرض'), ('librarian', 'أمين مصادر التعلم'), ('it_technician', 'فني تقنية معلومات'), ('bus_supervisor', 'مشرف نقل مدرسي'), ('admin', 'إداري'), ('secretary', 'سكرتير المدرسة'), ('specialist', 'أخصائي (قديم)'), ('student', 'طالب'), ('parent', 'ولي أمر'), ('platform_developer', 'مطور المنصة')], max_length=30),
        ),
    ]
