# Generated by Django 5.2.12 on 2026-03-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_role_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['class_group', 'is_active'], name='idx_enrollment_class_active'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student', 'is_active'], name='idx_enrollment_student_active'),
        ),
    ]
