# Generated by Django 5.2.12 on 2026-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_teacher_exemption_and_double_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الجنسية'),
        ),
    ]
