# Generated by Django 5.2.13 on 2026-06-21 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rls_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentstudentlink',
            name='can_view_behavior',
            field=models.BooleanField(default=True, verbose_name='يرى السلوك'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم الشخصي يجب أن يحتوي على أرقام فقط (5-20 رقم)', regex='^\\d{5,20}$')], verbose_name='الرقم الشخصي'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='الرقم الشخصي (مشفّر)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id_hmac',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='HMAC الرقم الشخصي'),
        ),
    ]
