# Generated by Django 5.2.15 on 2026-06-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_parentstudentlink_can_view_behavior_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='المسار (مفتاح التخزين)')),
                ('content', models.BinaryField(verbose_name='المحتوى')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='الحجم (بايت)')),
                ('content_type', models.CharField(blank=True, max_length=200, verbose_name='نوع المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ملف مُخزَّن',
                'verbose_name_plural': 'الملفات المُخزَّنة',
                'ordering': ['-created_at'],
            },
        ),
    ]
