# Generated by Django 5.2.17 on 2026-08-27 19:22

import core.models.school
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_rls_parent_derived"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.models.school._uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("S1", "الفصل الدراسي الأول"),
                            ("S2", "الفصل الدراسي الثاني"),
                        ],
                        max_length=2,
                        verbose_name="الفصل",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                (
                    "max_grade",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="٤٠ للفصل الأول و٦٠ للثاني — وزن الفصل بياناتٌ لا ثابتٌ في الشيفرة",
                        max_digits=5,
                        verbose_name="الدرجة القصوى",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="core.academicyear",
                        verbose_name="العام الدراسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل دراسي",
                "verbose_name_plural": "الفصول الدراسية",
                "ordering": ["academic_year", "code"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.models.school._uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("staff_start", "بدء دوام الموظفين"),
                            ("students_start", "بدء دوام الطلبة"),
                            ("midterm_exam", "اختبارات منتصف الفصل"),
                            ("final_exam", "اختبارات نهاية الفصل"),
                            ("makeup_exam", "ملحق الاختبارات"),
                            ("second_round", "اختبارات الدور الثاني"),
                            ("break", "إجازة"),
                            ("resume", "استئناف الدوام"),
                        ],
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="البيان")),
                ("start_date", models.DateField(verbose_name="من")),
                ("end_date", models.DateField(verbose_name="إلى")),
                (
                    "grade_scope",
                    models.CharField(
                        choices=[
                            ("all", "جميع الصفوف"),
                            ("g1_9", "الصفوف ١–٩"),
                            ("g10_11", "الصفّان ١٠–١١"),
                            ("g12", "الصف ١٢"),
                        ],
                        default="all",
                        max_length=10,
                        verbose_name="نطاق الصفوف",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("both", "الجميع"),
                            ("staff", "الموظفون"),
                            ("students", "الطلبة"),
                        ],
                        default="both",
                        max_length=10,
                        verbose_name="الجمهور",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="core.academicyear",
                        verbose_name="العام الدراسي",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to="core.semester",
                        verbose_name="الفصل",
                    ),
                ),
            ],
            options={
                "verbose_name": "حدث تقويم",
                "verbose_name_plural": "أحداث التقويم",
                "ordering": ["start_date", "event_type"],
            },
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "code"), name="unique_semester_code_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="semester_ends_after_it_starts",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["academic_year", "start_date"],
                name="core_calend_academi_8cb447_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="calendar_event_ends_after_it_starts",
            ),
        ),
    ]
