# Generated by Django 5.2.17 on 2026-08-28 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_rls_academic_calendar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classgroup",
            options={
                "verbose_name": "شعبة دراسية",
                "verbose_name_plural": "الشُّعب الدراسية",
            },
        ),
    ]
