# Generated by Django 5.2.17 on 2026-08-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_alter_classgroup_academic_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="classgroup",
            name="track",
            field=models.CharField(
                blank=True,
                choices=[
                    ("science", "علمي"),
                    ("humanities", "آداب وإنسانيات"),
                    ("technology", "تكنولوجي"),
                ],
                max_length=12,
                verbose_name="المسار",
            ),
        ),
    ]
