# Generated by Django 5.2.17 on 2026-08-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0043_classgroup_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="employee_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="رقم الموظّف لدى وزارة التربية والتعليم والتعليم العالي",
                max_length=20,
                verbose_name="الرقم الوظيفي",
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("employee_number", ""), _negated=True),
                fields=("employee_number",),
                name="unique_employee_number",
            ),
        ),
    ]
