# Generated by Django 5.2.17 on 2026-08-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_customuser_employee_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="letterfoot",
            field=models.ImageField(
                blank=True,
                help_text="شريط عرضيّ يُذيّل كل صفحة — يُفضّل PNG بعرض 2400 بكسل",
                null=True,
                upload_to="schools/letterhead/",
                verbose_name="تذييل المطبوعات",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="letterhead",
            field=models.ImageField(
                blank=True,
                help_text="شريط عرضيّ يعلو كل صفحة — يُفضّل PNG بعرض 2400 بكسل",
                null=True,
                upload_to="schools/letterhead/",
                verbose_name="ترويسة المطبوعات",
            ),
        ),
    ]
