# Generated by Django 5.2.13 on 2026-09-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_school_letterfoot_school_letterhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='departure_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='ملاحظة'),
        ),
        migrations.AddField(
            model_name='membership',
            name='departure_reason',
            field=models.CharField(blank=True, choices=[('transfer', 'نقلٌ إلى مدرسةٍ أخرى'), ('end_of_service', 'انتهاءُ خدمة'), ('resignation', 'استقالة'), ('retirement', 'تقاعد'), ('other', 'أخرى')], max_length=16, verbose_name='سبب المغادرة'),
        ),
        migrations.AddField(
            model_name='membership',
            name='departure_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='مرجع قرار المغادرة'),
        ),
        migrations.AddField(
            model_name='membership',
            name='left_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المغادرة'),
        ),
    ]
