# Generated by Django 5.2.13 on 2026-09-01 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_membership_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='joined_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
