# Generated by Django 5.2.17 on 2026-09-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_role_e_projects_coordinator"),
    ]

    operations = [
        migrations.AddField(
            model_name="classgroup",
            name="has_own_timetable",
            field=models.BooleanField(
                default=False,
                help_text="شعبةٌ خارج الجدول العامّ — لا خطّةَ لها ولا إسنادَ ولا توليد",
                verbose_name="جدولٌ مستقلّ",
            ),
        ),
    ]
