# Generated by Django 5.2.17 on 2026-09-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_role_e_projects_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='specialty',
            field=models.CharField(blank=True, default='', help_text='اتركه فارغاً ما لم يكن للعضو تخصّصٌ يخالف اسم قسمه', max_length=60, verbose_name='تخصّص يُكتب بجانب القسم'),
        ),
    ]
