# Generated by Django 5.2.17 on 2026-09-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    # الرقمُ 0052 أخذته هجرةُ «جدولُ التربية الخاصّة مستقلّ» (الطلب #145)،
    # فرقمان لهجرتين مختلفتين يتركان في السلسلة ورقتين ويكسران الترحيل على
    # الإنتاج. فهذه 0054 وتالية لها لا موازية.
    dependencies = [
        ('core', '0053_ese_own_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='specialty',
            field=models.CharField(blank=True, default='', help_text='اتركه فارغاً ما لم يكن للعضو تخصّصٌ يخالف اسم قسمه', max_length=60, verbose_name='تخصّص يُكتب بجانب القسم'),
        ),
    ]
