# Generated by Django 5.2.17 on 2026-09-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_membership_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='appointment_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='ملاحظة التعيين'),
        ),
        migrations.AddField(
            model_name='membership',
            name='appointment_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='مرجع قرار التعيين'),
        ),
    ]
