# Generated by Django 5.2.17 on 2026-09-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_roles_school_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='المسمّى الوظيفيّ (كما في اللوائح)'),
        ),
    ]
