# Generated by Django 5.2.17 on 2026-09-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_membership_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(choices=[('HealthRecord', 'سجل صحي'), ('BehaviorInfraction', 'مخالفة سلوكية'), ('StudentSubjectResult', 'درجة طالب'), ('ClinicVisit', 'زيارة عيادة'), ('CustomUser', 'مستخدم'), ('Membership', 'عضويّة كادر'), ('ParentStudentLink', 'ربط ولي أمر'), ('BookBorrowing', 'إعارة كتاب'), ('ConsentRecord', 'سجل موافقة'), ('StudentAssessmentGrade', 'درجة تقييم'), ('StaffEvaluation', 'تقييم أداء موظف'), ('other', 'أخرى')], default='other', max_length=50),
        ),
    ]
