# Generated by Django 5.2.17 on 2026-09-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auditlog_allow_actor_detach'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='residence_area',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='منطقة السكن'),
        ),
    ]
