# Generated by Django 5.2.17 on 2026-09-12 06:17

import core.academic_calendar
import core.models.school
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_residence_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.UUIDField(default=core.models.school._uuid, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=20, verbose_name='الرمز')),
                ('name', models.CharField(max_length=60, verbose_name='الاسم')),
                ('floor', models.CharField(choices=[('ground', 'الطابق الأرضيّ'), ('first', 'الطابق الأوّل')], default='ground', max_length=6, verbose_name='الطابق')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('academic_year', models.CharField(default=core.academic_calendar.default_academic_year, max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wings', to='core.school')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_wings', to=settings.AUTH_USER_MODEL, verbose_name='المشرف الإداريّ')),
            ],
            options={
                'verbose_name': 'جناح',
                'verbose_name_plural': 'الأجنحة',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='wing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='core.wing', verbose_name='الجناح'),
        ),
        migrations.AddConstraint(
            model_name='wing',
            constraint=models.UniqueConstraint(fields=('school', 'code', 'academic_year'), name='unique_wing_code_per_year'),
        ),
        migrations.AddConstraint(
            model_name='wing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('supervisor__isnull', False)), fields=('school', 'supervisor', 'academic_year'), name='unique_wing_supervisor_per_year'),
        ),
    ]
