# Generated by Django 5.2.17 on 2026-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_auditlog_failed_login_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="vision",
            field=models.TextField(
                blank=True,
                default="متعلم ريادي لتنمية مستدامة",
                help_text="يظهر في فوتر المنصّة وذيل المطبوعات الرسميّة — رؤية الوزارة كما تعتمدها المدرسة",
                verbose_name="نصّ الرؤية",
            ),
        ),
    ]
