# Generated by Django 5.2.17 on 2026-09-18 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

TABLE = "core_exportjob"
PREDICATE = f"{TABLE}.school_id = public.app_rls_school()"
ENABLE = f"""
ALTER TABLE public.{TABLE} ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS school_isolation ON public.{TABLE};
CREATE POLICY school_isolation ON public.{TABLE} USING ({PREDICATE}) WITH CHECK ({PREDICATE});
"""
DISABLE = f"""
DROP POLICY IF EXISTS school_isolation ON public.{TABLE};
ALTER TABLE public.{TABLE} DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_school_vision"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "kind",
                    models.CharField(db_index=True, max_length=50, verbose_name="النوع"),
                ),
                (
                    "query_string",
                    models.TextField(blank=True, verbose_name="معاملات الطلب"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("running", "جارٍ التحضير"),
                            ("done", "جاهز"),
                            ("failed", "فشل"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "content",
                    models.BinaryField(blank=True, null=True, verbose_name="المحتوى"),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, verbose_name="نوع المحتوى"),
                ),
                (
                    "filename",
                    models.CharField(blank=True, max_length=255, verbose_name="اسم الملف"),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=2000, verbose_name="رسالة الخطأ"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="وقت الانتهاء"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="طلبه",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صفّ تصدير",
                "verbose_name_plural": "صفوف التصدير",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["school", "created_at"],
                        name="core_export_school__ae6f16_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="core_export_status_2ad959_idx",
                    ),
                ],
            },
        ),
        migrations.RunSQL(sql=ENABLE, reverse_sql=DISABLE),
    ]
