# Generated by Django 5.2.17 on 2026-09-20 12:13

from django.db import migrations, models

#: نصُّ الرؤية الافتراضيّ قبلُ وبعد التشكيل (قرارُ المالك 2026-09-20). لا يُمسّ إلّا من بقي على الافتراضيّ
#: حرفاً بحرف — فمن حرّر رؤيتَه من لوحة الإدارة يبقى نصُّه كما كتبه.
UNVOWELLED = "متعلم ريادي لتنمية مستدامة"
VOWELLED = "مُتَعَلِّمٌ رِيَادِيٌّ لِتَنْمِيَةٍ مُسْتَدَامَةٍ"


def vowel_the_untouched_default(apps, schema_editor):
    apps.get_model("core", "School").objects.filter(vision=UNVOWELLED).update(vision=VOWELLED)


def unvowel(apps, schema_editor):
    apps.get_model("core", "School").objects.filter(vision=VOWELLED).update(vision=UNVOWELLED)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_export_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="vision",
            field=models.TextField(
                blank=True,
                default="مُتَعَلِّمٌ رِيَادِيٌّ لِتَنْمِيَةٍ مُسْتَدَامَةٍ",
                help_text="يظهر في فوتر المنصّة وذيل المطبوعات الرسميّة — رؤية الوزارة كما تعتمدها المدرسة",
                verbose_name="نصّ الرؤية",
            ),
        ),
        migrations.RunPython(vowel_the_untouched_default, unvowel),
    ]
