# Generated by Django 5.2.17 on 2026-09-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_school_vision_vowelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="service_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ المباشرة"
            ),
        ),
    ]
