# Generated by Django 5.2.17 on 2026-09-24 05:40

import core.academic_calendar
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_user_service_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "ملف شخصي",
                "verbose_name_plural": "الملفات الشخصية",
            },
        ),
        migrations.AlterModelOptions(
            name="studentenrollment",
            options={
                "verbose_name": "تسجيل طالب",
                "verbose_name_plural": "تسجيلات الطلبة",
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "إنشاء"),
                    ("update", "تعديل"),
                    ("delete", "حذف"),
                    ("view", "عرض"),
                    ("export", "تصدير"),
                    ("login", "تسجيل دخول"),
                    ("logout", "تسجيل خروج"),
                    ("login_failed", "محاولة دخول فاشلة"),
                    ("mfa_failed", "رمز تحقّق خاطئ"),
                ],
                max_length=20,
                verbose_name="الإجراء",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="عنوان IP"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(
                choices=[
                    ("HealthRecord", "سجل صحي"),
                    ("BehaviorInfraction", "مخالفة سلوكية"),
                    ("StudentSubjectResult", "درجة طالب"),
                    ("ClinicVisit", "زيارة عيادة"),
                    ("CustomUser", "مستخدم"),
                    ("Membership", "عضويّة كادر"),
                    ("ParentStudentLink", "ربط ولي أمر"),
                    ("BookBorrowing", "إعارة كتاب"),
                    ("ConsentRecord", "سجل موافقة"),
                    ("StudentAssessmentGrade", "درجة تقييم"),
                    ("StaffEvaluation", "تقييم أداء موظف"),
                    ("other", "أخرى"),
                ],
                default="other",
                max_length=50,
                verbose_name="النموذج",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="معرّف السجل"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="الوقت"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.CharField(blank=True, max_length=300, verbose_name="المتصفّح"),
        ),
        migrations.AlterField(
            model_name="breachreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="breachreport",
            name="reported_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_breaches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المُبلِّغ",
            ),
        ),
        migrations.AlterField(
            model_name="breachreport",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ المعالجة"
            ),
        ),
        migrations.AlterField(
            model_name="breachreport",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breach_reports",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="breachreport",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "منخفضة"),
                    ("medium", "متوسطة"),
                    ("high", "عالية"),
                    ("critical", "حرجة"),
                ],
                default="medium",
                max_length=10,
                verbose_name="الخطورة",
            ),
        ),
        migrations.AlterField(
            model_name="breachreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("discovered", "مكتشف"),
                    ("assessing", "قيد التقييم"),
                    ("notified", "تم الإشعار"),
                    ("resolved", "محلول"),
                ],
                default="discovered",
                max_length=15,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="classgroup",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="classgroup",
            name="grade",
            field=models.CharField(
                choices=[
                    ("G7", "الصف السابع"),
                    ("G8", "الصف الثامن"),
                    ("G9", "الصف التاسع"),
                    ("G10", "الصف العاشر"),
                    ("G11", "الصف الحادي عشر"),
                    ("G12", "الصف الثاني عشر"),
                ],
                max_length=3,
                verbose_name="الصف",
            ),
        ),
        migrations.AlterField(
            model_name="classgroup",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشطة"),
        ),
        migrations.AlterField(
            model_name="classgroup",
            name="level_type",
            field=models.CharField(
                choices=[("prep", "إعدادي"), ("sec", "ثانوي")],
                default="prep",
                max_length=4,
                verbose_name="المرحلة",
            ),
        ),
        migrations.AlterField(
            model_name="classgroup",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_groups",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="classgroup",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_classes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المشرف",
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("health", "البيانات الصحية"),
                    ("behavior", "بيانات السلوك"),
                    ("grades", "الدرجات والتقييمات"),
                    ("attendance", "الحضور والغياب"),
                    ("transport", "بيانات النقل"),
                    ("photo", "الصور والمرئيات"),
                    ("all", "جميع البيانات"),
                ],
                max_length=20,
                verbose_name="نوع البيانات",
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="given_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="تاريخ الموافقة"
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="method",
            field=models.CharField(
                choices=[
                    ("form", "استمارة ورقية"),
                    ("digital", "موافقة رقمية"),
                    ("verbal", "موافقة شفهية موثقة"),
                ],
                default="digital",
                max_length=10,
                verbose_name="طريقة الموافقة",
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="وليّ الأمر",
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consents_recorded",
                to=settings.AUTH_USER_MODEL,
                verbose_name="سجّله",
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_as_student",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="withdrawn_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ السحب"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ الانضمام"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="محاولات الدخول الفاشلة"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="حساب نشط"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="دخول لوحة الإدارة"),
        ),
        migrations.AlterField(
            model_name="erasurerequest",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الاكتمال"
            ),
        ),
        migrations.AlterField(
            model_name="erasurerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="erasurerequest",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="erasure_filed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مقدّم الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="erasurerequest",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ المراجعة"
            ),
        ),
        migrations.AlterField(
            model_name="erasurerequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="erasure_reviewed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="راجعه",
            ),
        ),
        migrations.AlterField(
            model_name="erasurerequest",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="erasure_requests",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="erasurerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("approved", "تمت الموافقة"),
                    ("processing", "جارٍ التنفيذ"),
                    ("completed", "مكتمل"),
                    ("rejected", "مرفوض"),
                ],
                default="pending",
                max_length=12,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="erasurerequest",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="erasure_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="joined_at",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="تاريخ الالتحاق"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="core.role",
                verbose_name="الدور",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="parentstudentlink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="parentstudentlink",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_links",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الميلاد"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "ذكر"), ("F", "أنثى")],
                max_length=1,
                verbose_name="الجنس",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("principal", "مدير المدرسة"),
                    ("vice_admin", "النائب الإداري"),
                    ("vice_academic", "النائب الأكاديمي"),
                    ("coordinator", "منسق أكاديمي"),
                    ("admin_supervisor", "مشرف إداري"),
                    ("activities_coordinator", "منسق الأنشطة المدرسية"),
                    ("e_projects_coordinator", "منسق المشاريع الإلكترونية"),
                    ("teacher", "معلم"),
                    ("ese_teacher", "معلم تربية خاصة"),
                    ("teacher_assistant", "مساعد المعلم"),
                    ("ese_assistant", "مساعد معلم تربية خاصة"),
                    ("social_worker", "أخصائي اجتماعي"),
                    ("psychologist", "أخصائي نفسي"),
                    ("academic_advisor", "مرشد أكاديمي"),
                    ("speech_therapist", "أخصائي النطق"),
                    ("occupational_therapist", "أخصائي العلاج الوظائفي"),
                    ("support_companion", "مرافق الدعم"),
                    ("nurse", "ممرض"),
                    ("librarian", "أمين مصادر التعلم"),
                    ("it_technician", "فني تقنية معلومات"),
                    ("bus_supervisor", "مشرف نقل مدرسي"),
                    ("transport_officer", "مسؤول النقل"),
                    ("admin", "إداري"),
                    ("secretary", "سكرتير المدرسة"),
                    ("receptionist", "موظف استقبال"),
                    ("student_observer", "ملاحظ طلبة"),
                    ("lab_technician", "محضّر مختبر"),
                    ("storekeeper", "أمين مخزن"),
                    ("accountant", "محاسب"),
                    ("canteen_supervisor", "مشرف مقصف"),
                    ("services_worker", "عامل خدمات"),
                    ("messenger", "مندوب"),
                    ("specialist", "أخصائي (قديم)"),
                    ("student", "طالب"),
                    ("parent", "ولي أمر"),
                    ("platform_developer", "مطور المنصة"),
                ],
                max_length=30,
                verbose_name="اسم الدور",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="storedfile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="class_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="core.classgroup",
                verbose_name="الشعبة",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="enrolled_at",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="تاريخ التسجيل"
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="timeband",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="timeband",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_bands",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="wing",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="wing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="wing",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wings",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="wingcoverage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="wingcoverage",
            name="reason",
            field=models.CharField(
                choices=[
                    ("absence", "غيابُ المشرف"),
                    ("leave", "إجازة"),
                    ("vacancy", "جناحٌ بلا مشرف"),
                    ("other", "أخرى"),
                ],
                default="absence",
                max_length=10,
                verbose_name="سبب التغطية",
            ),
        ),
        migrations.AlterField(
            model_name="wingcoverage",
            name="wing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverages",
                to="core.wing",
                verbose_name="الجناح",
            ),
        ),
    ]
