# Generated by Django 5.2.17 on 2026-09-25 10:47

"""منحُ القدرات المفوَّضة (التذكرة SOS-20260924-1CFE، الجزء أ) — توسيعٌ فقط: جدولٌ جديد + خيارَا تدقيقٍ جديدان.

الرقمُ 0074 لا 0073: 0073 محجوزٌ لطلبٍ مفتوحٍ آخر (نهاية دوام الطلبة)، فيُعاد ضبطُ الاعتماد على ما يسبقه عند الدمج.
RLS كسائر جداول المدرسة: عزلٌ بـ`school_id = app_rls_school()`.
"""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

TABLE = "core_capabilitygrant"
PREDICATE = f"{TABLE}.school_id = public.app_rls_school()"
ENABLE = f"""
ALTER TABLE public.{TABLE} ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS school_isolation ON public.{TABLE};
CREATE POLICY school_isolation ON public.{TABLE} USING ({PREDICATE}) WITH CHECK ({PREDICATE});
"""
DISABLE = f"""
DROP POLICY IF EXISTS school_isolation ON public.{TABLE};
ALTER TABLE public.{TABLE} DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_delete_orphan_model_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("role_assigned", "تعيين دور"),
                    ("role_removed", "إزالة دور"),
                    ("dept_changed", "تغيير القسم"),
                    ("dept_head_set", "تعيين منسق"),
                    ("dept_head_removed", "إزالة منسق"),
                    ("account_disabled", "تعطيل حساب"),
                    ("account_enabled", "تفعيل حساب"),
                    ("substitute_assigned", "تعيين بديل"),
                    ("swap_approved", "موافقة تبديل"),
                    ("swap_rejected", "رفض تبديل"),
                    ("compensatory_approved", "موافقة تعويض"),
                    ("capability_granted", "منح قدرة مفوَّضة"),
                    ("capability_revoked", "سحب قدرة مفوَّضة"),
                ],
                max_length=30,
                verbose_name="نوع الإجراء",
            ),
        ),
        migrations.CreateModel(
            name="CapabilityGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[("schedule.operator", "مُشغِّل الجدول")],
                        db_index=True,
                        max_length=60,
                        verbose_name="القدرة",
                    ),
                ),
                ("reason", models.TextField(verbose_name="سببُ المنح")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="وقتُ السحب"
                    ),
                ),
                (
                    "revoke_reason",
                    models.TextField(blank=True, verbose_name="سببُ السحب"),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capability_grants_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مانحُها",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capability_grants_revoked",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ساحبُها",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حاملُ القدرة",
                    ),
                ),
            ],
            options={
                "verbose_name": "منحُ قدرةٍ مفوَّضة",
                "verbose_name_plural": "منحُ القدرات المفوَّضة",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["school", "capability", "revoked_at"],
                        name="core_capabi_school__6fff82_idx",
                    ),
                    models.Index(
                        fields=["user", "capability", "revoked_at"],
                        name="core_capabi_user_id_d5fe49_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("school", "user", "capability"),
                        name="uniq_active_capability_grant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason", ""), _negated=True),
                        name="capability_grant_has_a_reason",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("revoke_reason", ""), ("revoked_at__isnull", True)),
                            models.Q(
                                ("revoked_at__isnull", False),
                                models.Q(("revoke_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="capability_grant_revocation_has_a_reason",
                    ),
                ],
            },
        ),
        migrations.RunSQL(ENABLE, DISABLE),
    ]
