# Generated by Django 5.2.17 on 2026-09-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_capability_grant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("staff_start", "بدء دوام الموظفين"),
                    ("students_start", "بدء دوام الطلبة"),
                    ("students_end", "نهاية دوام الطلبة"),
                    ("midterm_exam", "اختبارات منتصف الفصل"),
                    ("final_exam", "اختبارات نهاية الفصل"),
                    ("makeup_exam", "ملحق الاختبارات"),
                    ("second_round", "اختبارات الدور الثاني"),
                    ("break", "إجازة"),
                    ("resume", "استئناف الدوام"),
                ],
                max_length=20,
                verbose_name="النوع",
            ),
        ),
    ]
