# Generated by Django 5.2.17 on 2026-10-01 10:51

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_calendar_students_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="employer_name",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=200,
                verbose_name="جهة العمل",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="employer_sector",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=100,
                verbose_name="قطاع جهة العمل",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="kahramaa_number",
            field=core.fields.EncryptedTextField(
                blank=True, db_default="", default="", verbose_name="رقم كهرماء"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="municipality",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=100,
                verbose_name="البلدية",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="region",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=100,
                verbose_name="المنطقة",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="uses_bus",
            field=models.BooleanField(
                db_default=False, default=False, verbose_name="يستخدم الحافلة"
            ),
        ),
    ]
