# Generated by Django 5.2.17 on 2026-10-02 19:04

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_customuser_employer_name_customuser_employer_sector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_date_encrypted",
            field=core.fields.EncryptedTextField(
                blank=True,
                db_default="",
                default="",
                verbose_name="تاريخ الميلاد (مشفّر)",
            ),
        ),
    ]
