# Generated by Django 5.2.17 on 2026-10-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_auditlog_allow_network_redaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capabilitygrant",
            name="capability",
            field=models.CharField(
                choices=[
                    ("schedule.operator", "مُشغِّل الجدول"),
                    ("wings.school_wide", "حاصرُ الغياب العامّ"),
                ],
                db_index=True,
                max_length=60,
                verbose_name="القدرة",
            ),
        ),
    ]
