# Generated by Django 5.2.17 on 2026-10-09 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_ncsa_stage(apps, schema_editor):
    """خروقٌ أُشعر بها قبل هذه الهجرة إشعارُها مكتمل (كان الزرُّ الوحيدُ «تم الإشعار»)."""
    from django.db.models import F

    BreachReport = apps.get_model("core", "BreachReport")
    BreachReport.objects.filter(ncsa_notified_at__isnull=False, ncsa_notice_stage="none").update(
        ncsa_notice_stage="complete", ncsa_completed_at=F("ncsa_notified_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_role_student_affairs_coordinator"),
    ]

    operations = [
        migrations.AddField(
            model_name="breachreport",
            name="individuals_assessed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت تقييم لزوم الإخطار"
            ),
        ),
        migrations.AddField(
            model_name="breachreport",
            name="individuals_assessment_note",
            field=models.TextField(
                blank=True, verbose_name="أساس التقدير أو سبب عدم لزوم الإخطار"
            ),
        ),
        migrations.AddField(
            model_name="breachreport",
            name="individuals_deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="موعد إخطار الأفراد"
            ),
        ),
        migrations.AddField(
            model_name="breachreport",
            name="individuals_decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="breach_individuals_decisions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="صاحب قرار إخطار الأفراد",
            ),
        ),
        migrations.AddField(
            model_name="breachreport",
            name="individuals_notified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت إخطار الأفراد الفعلي"
            ),
        ),
        migrations.AddField(
            model_name="breachreport",
            name="individuals_notified_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sms", "رسالة نصّية"),
                    ("email", "بريد إلكتروني"),
                    ("letter", "خطاب رسمي"),
                    ("portal", "إشعار عبر المنصّة"),
                    ("in_person", "إبلاغ مباشر"),
                ],
                max_length=10,
                verbose_name="قناة إخطار الأفراد",
            ),
        ),
        migrations.AddField(
            model_name="breachreport",
            name="individuals_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "لم يُقيَّم بعد"),
                    ("required", "واجب إخطارهم"),
                    ("not_required", "غير لازم"),
                    ("notified", "أُخطروا"),
                ],
                default="not_assessed",
                max_length=12,
                verbose_name="حالة إخطار الأفراد",
            ),
        ),
        migrations.AddField(
            model_name="breachreport",
            name="ncsa_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت استكمال الإشعار الفعلي"
            ),
        ),
        migrations.AddField(
            model_name="breachreport",
            name="ncsa_completion_due_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="موعد استكمال الإشعار"
            ),
        ),
        migrations.AddField(
            model_name="breachreport",
            name="ncsa_missing_reasons",
            field=models.TextField(
                blank=True, verbose_name="أسباب نقص معلومات الإشعار المبدئي"
            ),
        ),
        migrations.AddField(
            model_name="breachreport",
            name="ncsa_notice_stage",
            field=models.CharField(
                choices=[
                    ("none", "لم يُرسَل"),
                    ("initial", "إشعار مبدئي (ناقص)"),
                    ("complete", "إشعار مكتمل"),
                ],
                default="none",
                max_length=10,
                verbose_name="مرحلة إشعار NCSA",
            ),
        ),
        # توسيعٌ فقط: لا حذفَ ولا إعادةَ تسمية؛ والرجوعُ يحذف الأعمدةَ الجديدةَ وحدَها.
        migrations.RunPython(backfill_ncsa_stage, migrations.RunPython.noop),
    ]
