# Generated by Django 5.2.17 on 2026-08-31 05:36

import core.academic_calendar
import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0045_school_letterfoot_school_letterhead"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("teacher", "ملاحظات المعلمين"),
                            ("social_worker", "ملاحظات الأخصائي الاجتماعي"),
                            ("psychologist", "ملاحظات الأخصائي النفسي"),
                            ("nurse", "ملاحظات الممرض"),
                            ("student_affairs", "ملاحظات منسق شؤون الطلاب"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="الجهة",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="العنوان")),
                ("body", core.fields.EncryptedTextField(verbose_name="نصّ الملاحظة")),
                ("occurred_on", models.DateField(verbose_name="التاريخ")),
                (
                    "academic_year",
                    models.CharField(
                        default=core.academic_calendar.default_academic_year,
                        max_length=9,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_notes",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملاحظة على طالب",
                "verbose_name_plural": "الملاحظات على الطلاب",
                "ordering": ["-occurred_on", "-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["school", "student", "academic_year"],
                        name="student_inf_school__580cfc_idx",
                    ),
                    models.Index(
                        fields=["school", "category", "academic_year"],
                        name="student_inf_school__c48b32_idx",
                    ),
                ],
            },
        ),
    ]
