# Generated by Django 5.2.17 on 2026-09-24 05:40

import core.academic_calendar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_info", "0002_rls_student_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentnote",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
    ]
