# Generated by Django 5.2.12 on 2026-03-21 11:19

import behavior.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0002_violationcategory_abcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorinfraction',
            name='id',
            field=models.UUIDField(
                default=behavior.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='behaviorpointrecovery',
            name='id',
            field=models.UUIDField(
                default=behavior.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='violationcategory',
            name='id',
            field=models.UUIDField(
                default=behavior.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
