# Generated by Django 5.2.12 on 2026-03-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0003_alter_behaviorinfraction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorinfraction',
            name='action_taken',
            field=models.TextField(blank=True, max_length=2000, verbose_name='الإجراء المتخذ'),
        ),
        migrations.AlterField(
            model_name='behaviorinfraction',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='وصف المخالفة'),
        ),
        migrations.AlterField(
            model_name='behaviorinfraction',
            name='points_deducted',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='النقاط المخصومة'),
        ),
    ]
