# Generated by Django 5.2.12 on 2026-03-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0005_behavior_search_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='behaviorinfraction',
            name='infraction_date_btree_idx',
        ),
        migrations.RemoveIndex(
            model_name='behaviorinfraction',
            name='infraction_level_btree_idx',
        ),
        migrations.RemoveIndex(
            model_name='behaviorinfraction',
            name='infraction_student_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='behaviorinfraction',
            name='infraction_school_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='behaviorinfraction',
            name='infraction_description_gin_idx',
        ),
    ]
