# Generated by Django 5.2.12 on 2026-03-26 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0006_remove_behaviorinfraction_infraction_date_btree_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violationcategory',
            options={'ordering': ['degree', 'code'], 'verbose_name': 'فئة مخالفة سلوكية', 'verbose_name_plural': 'فئات المخالفات السلوكية (2025)'},
        ),
        migrations.AddField(
            model_name='behaviorinfraction',
            name='digital_evidence_notes',
            field=models.TextField(blank=True, default='', help_text='وصف الأدلة الرقمية (روابط، لقطات شاشة، إلخ)', max_length=1000, verbose_name='ملاحظات الأدلة الرقمية'),
        ),
        migrations.AddField(
            model_name='behaviorinfraction',
            name='escalation_step',
            field=models.PositiveSmallIntegerField(choices=[(0, 'لم يُتخذ إجراء بعد'), (1, 'الإجراء الأول'), (2, 'الإجراء الثاني'), (3, 'الإجراء الثالث'), (4, 'الإجراء الرابع')], default=0, help_text='أي خطوة من الإجراءات التصاعدية تم تنفيذها', verbose_name='خطوة الإجراء التصاعدي'),
        ),
        migrations.AddField(
            model_name='behaviorinfraction',
            name='parent_summon_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ استدعاء ولي الأمر'),
        ),
        migrations.AddField(
            model_name='behaviorinfraction',
            name='parent_summoned',
            field=models.BooleanField(default=False, verbose_name='تم استدعاء ولي الأمر'),
        ),
        migrations.AddField(
            model_name='behaviorinfraction',
            name='parent_undertaking_signed',
            field=models.BooleanField(default=False, verbose_name='تم توقيع تعهد ولي الأمر'),
        ),
        migrations.AddField(
            model_name='behaviorinfraction',
            name='security_agency',
            field=models.CharField(blank=True, choices=[('police', 'الشرطة'), ('prosecution', 'النيابة العامة'), ('child_protection', 'إدارة حماية الطفل'), ('cybercrime', 'إدارة مكافحة الجرائم الإلكترونية'), ('ministry', 'لجنة وزارة التربية'), ('other', 'جهة أخرى')], default='', max_length=30, verbose_name='الجهة الأمنية المُحالة إليها'),
        ),
        migrations.AddField(
            model_name='behaviorinfraction',
            name='security_notes',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='ملاحظات الإحالة الأمنية'),
        ),
        migrations.AddField(
            model_name='behaviorinfraction',
            name='security_reference_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='رقم المرجع الأمني'),
        ),
        migrations.AddField(
            model_name='behaviorinfraction',
            name='security_referral_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإحالة الأمنية'),
        ),
        migrations.AddField(
            model_name='behaviorinfraction',
            name='social_media_platform',
            field=models.CharField(blank=True, choices=[('tiktok', 'تيك توك'), ('snapchat', 'سناب شات'), ('instagram', 'إنستغرام'), ('twitter', 'تويتر (إكس)'), ('facebook', 'فيسبوك'), ('whatsapp', 'واتساب'), ('youtube', 'يوتيوب'), ('telegram', 'تيليغرام'), ('other', 'أخرى')], default='', help_text='عند تسجيل مخالفة تشهير أو تصوير رقمي', max_length=20, verbose_name='منصة التواصل الاجتماعي'),
        ),
        migrations.AddField(
            model_name='behaviorinfraction',
            name='suspension_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='أيام الإيقاف'),
        ),
        migrations.AddField(
            model_name='behaviorinfraction',
            name='suspension_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('internal', 'إيقاف داخل المدرسة'), ('external', 'إيقاف خارج المدرسة')], default='', max_length=20, verbose_name='نوع الإيقاف'),
        ),
        migrations.AddField(
            model_name='violationcategory',
            name='degree',
            field=models.PositiveSmallIntegerField(choices=[(1, 'الدرجة الأولى — بسيطة'), (2, 'الدرجة الثانية — متوسطة'), (3, 'الدرجة الثالثة — خطيرة'), (4, 'الدرجة الرابعة — جسيمة')], db_index=True, default=1, verbose_name='الدرجة الرسمية (1-4)'),
        ),
        migrations.AddField(
            model_name='violationcategory',
            name='requires_parent_summon',
            field=models.BooleanField(default=False, verbose_name='يتطلب استدعاء ولي أمر فوري'),
        ),
        migrations.AddField(
            model_name='violationcategory',
            name='requires_security_referral',
            field=models.BooleanField(default=False, verbose_name='يتطلب إحالة أمنية'),
        ),
        migrations.AddField(
            model_name='violationcategory',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='فاصل: tech,safety,law,national', max_length=100, verbose_name='تصنيفات'),
        ),
        migrations.AlterField(
            model_name='behaviorinfraction',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'الدرجة الأولى (بسيطة)'), (2, 'الدرجة الثانية (متوسطة)'), (3, 'الدرجة الثالثة (خطيرة)'), (4, 'الدرجة الرابعة (جسيمة)')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='behaviorinfraction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavior_infractions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='behaviorinfraction',
            name='violation_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infractions', to='behavior.violationcategory', verbose_name='فئة المخالفة'),
        ),
        migrations.AlterField(
            model_name='violationcategory',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'الفئة A — خفيفة'), ('B', 'الفئة B — متوسطة'), ('C', 'الفئة C — جسيمة'), ('D', 'الفئة D — حرجة')], default='', help_text='⚠ حقل قديم — يُستخدم فقط للمخالفات المحقونة قبل 2025', max_length=1, verbose_name='الفئة القديمة (ABCD)'),
        ),
        migrations.AlterField(
            model_name='violationcategory',
            name='code',
            field=models.CharField(help_text='مثال: 1-01, 2-05, 3-07, 4-13', max_length=10, unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='violationcategory',
            name='default_action',
            field=models.CharField(blank=True, max_length=500, verbose_name='الإجراء الافتراضي'),
        ),
        migrations.AlterField(
            model_name='violationcategory',
            name='name_ar',
            field=models.CharField(max_length=300, verbose_name='اسم المخالفة'),
        ),
    ]
