# Generated by Django 5.2.12 on 2026-03-30 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0007_v6_qatar_2025_behavior_fields'),
        ('core', '0028_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='behaviorinfraction',
            index=models.Index(fields=['school', 'date'], name='idx_infraction_school_date'),
        ),
        migrations.AddIndex(
            model_name='behaviorinfraction',
            index=models.Index(fields=['school', 'level', 'is_resolved'], name='idx_infraction_level_resolved'),
        ),
    ]
