# Generated by Django 5.2.17 on 2026-09-13 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("behavior", "0015_conduct_catalog_2026"),
        ("core", "0065_role_support_companion"),
        ("operations", "0047_period_confirmation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="behaviorinfraction",
            name="auto_rule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("period_tardy", "تأخّرٌ عن الحصّة (من الرصد)"),
                    ("class_escape", "هروبٌ من الحصّة (من الرصد)"),
                    ("school_escape", "هروبٌ من المدرسة (من الرصد)"),
                ],
                default="",
                max_length=16,
                verbose_name="أنشأها الرصد",
            ),
        ),
        migrations.AddField(
            model_name="behaviorinfraction",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="infractions",
                to="operations.session",
                verbose_name="الحصّة",
            ),
        ),
        migrations.AddConstraint(
            model_name="behaviorinfraction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("auto_rule", ""), _negated=True),
                fields=("student", "session", "auto_rule"),
                name="unique_auto_infraction_per_session",
            ),
        ),
    ]
