"""علامةُ «أُرسل» لمخالفات الرصد — ومعها عزلُ المدرسة.

الجدولُ يُنشأ بعد `core/0037`، فلا يرث سياسةَ العزل: تُكتب هنا صراحةً كما في
`operations/0047`. و`behavior_autoinfractionnotice` يحمل `school_id` بنفسه.
"""

# Generated by Django 5.2.17 on 2026-09-16 19:01

import behavior.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

TABLE = "behavior_autoinfractionnotice"
CURRENT = "public.app_rls_school()"
PREDICATE = f"{TABLE}.school_id = {CURRENT}"

ENABLE = f"""
ALTER TABLE public.{TABLE} ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS school_isolation ON public.{TABLE};

CREATE POLICY school_isolation ON public.{TABLE}
    USING ({PREDICATE})
    WITH CHECK ({PREDICATE});
"""

DISABLE = f"""
DROP POLICY IF EXISTS school_isolation ON public.{TABLE};
ALTER TABLE public.{TABLE} DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("behavior", "0016_infraction_session_auto_rule"),
        ("core", "0066_auditlog_failed_login_actions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoInfractionNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=behavior.models._uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="يومُ الحصّة")),
                (
                    "auto_rule",
                    models.CharField(
                        choices=[
                            ("period_tardy", "تأخّرٌ عن الحصّة (من الرصد)"),
                            ("class_escape", "هروبٌ من الحصّة (من الرصد)"),
                            ("school_escape", "هروبٌ من المدرسة (من الرصد)"),
                        ],
                        max_length=16,
                        verbose_name="القاعدة",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="بدءُ الحصّة")),
                (
                    "message_id",
                    models.UUIDField(db_index=True, default=behavior.models._uuid),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("immediate", "فوريّ"),
                            ("digest", "الملخّص اليوميّ"),
                            ("supplement", "إضافةٌ إلى الملخّص"),
                        ],
                        max_length=10,
                    ),
                ),
                ("recipients", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "infraction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices",
                        to="behavior.behaviorinfraction",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_infraction_notices",
                        to="core.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_infraction_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "إبلاغٌ بمخالفة رصد",
                "verbose_name_plural": "الإبلاغُ بمخالفات الرصد",
                "ordering": ["-date", "student", "start_time"],
                "indexes": [
                    models.Index(fields=["school", "date"], name="auto_notice_school_date")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "date", "auto_rule", "start_time"),
                        name="unique_auto_infraction_notice",
                    )
                ],
            },
        ),
        migrations.RunSQL(sql=ENABLE, reverse_sql=DISABLE),
    ]
