# Generated by Django 5.2.17 on 2026-09-24 05:40

import behavior.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behavior", "0018_auto_notice_baseline"),
        ("core", "0071_arabic_field_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoinfractionnotice",
            name="infraction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notices",
                to="behavior.behaviorinfraction",
                verbose_name="المخالفة",
            ),
        ),
        migrations.AlterField(
            model_name="autoinfractionnotice",
            name="kind",
            field=models.CharField(
                choices=[
                    ("immediate", "فوريّ"),
                    ("digest", "الملخّص اليوميّ"),
                    ("supplement", "إضافةٌ إلى الملخّص"),
                    ("baseline", "سابقٌ للإطلاق — لم يُرسَل"),
                ],
                max_length=10,
                verbose_name="نوع الإشعار",
            ),
        ),
        migrations.AlterField(
            model_name="autoinfractionnotice",
            name="message_id",
            field=models.UUIDField(
                db_index=True,
                default=behavior.models._uuid,
                verbose_name="معرّف الرسالة",
            ),
        ),
        migrations.AlterField(
            model_name="autoinfractionnotice",
            name="recipients",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="عدد المستلمين"
            ),
        ),
        migrations.AlterField(
            model_name="autoinfractionnotice",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_infraction_notices",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="autoinfractionnotice",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإرسال"),
        ),
        migrations.AlterField(
            model_name="autoinfractionnotice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_infraction_notices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="behaviorinfraction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاريخ الإنشاء"
            ),
        ),
        migrations.AlterField(
            model_name="behaviorinfraction",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="تاريخ المخالفة"),
        ),
        migrations.AlterField(
            model_name="behaviorinfraction",
            name="is_resolved",
            field=models.BooleanField(default=False, verbose_name="معالَجة"),
        ),
        migrations.AlterField(
            model_name="behaviorinfraction",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "الدرجة الأولى (بسيطة)"),
                    (2, "الدرجة الثانية (متوسطة)"),
                    (3, "الدرجة الثالثة (خطيرة)"),
                    (4, "الدرجة الرابعة (جسيمة)"),
                ],
                db_index=True,
                default=1,
                verbose_name="الدرجة",
            ),
        ),
        migrations.AlterField(
            model_name="behaviorinfraction",
            name="reported_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_infractions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المُبلِّغ",
            ),
        ),
        migrations.AlterField(
            model_name="behaviorinfraction",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="behaviorinfraction",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="behavior_infractions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="behaviorpointrecovery",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمده",
            ),
        ),
        migrations.AlterField(
            model_name="behaviorpointrecovery",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="تاريخ الاستعادة"),
        ),
        migrations.AlterField(
            model_name="behaviorpointrecovery",
            name="infraction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recovery",
                to="behavior.behaviorinfraction",
                verbose_name="المخالفة",
            ),
        ),
        migrations.AlterField(
            model_name="behaviorpointrecovery",
            name="points_restored",
            field=models.PositiveIntegerField(
                default=0, verbose_name="النقاط المستعادة"
            ),
        ),
        migrations.AlterField(
            model_name="violationcategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
    ]
