# Generated by Django 5.2.17 on 2026-10-02 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behavior", "0021_violation_ladder_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorCommitteeVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decision", models.CharField(max_length=10, verbose_name="القرار")),
                (
                    "action_taken",
                    models.TextField(blank=True, verbose_name="الإجراء المقترح"),
                ),
                (
                    "suspension_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="نوع الإيقاف"
                    ),
                ),
                (
                    "suspension_days",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="أيام الإيقاف"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "مفتوح"),
                            ("applied", "نُفِّذ"),
                            ("dropped", "أُسقط"),
                        ],
                        default="open",
                        max_length=8,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التصويت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل للصوت"),
                ),
                (
                    "infraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_votes",
                        to="behavior.behaviorinfraction",
                        verbose_name="المخالفة",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="behavior_committee_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="العضو",
                    ),
                ),
            ],
            options={
                "verbose_name": "صوت لجنة الضبط",
                "verbose_name_plural": "أصوات لجنة الضبط",
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("infraction", "voter"),
                        name="one_open_committee_vote_per_member",
                    )
                ],
            },
        ),
    ]
