# Generated by Django 5.2.12 on 2026-03-21 11:19

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicvisit',
            name='id',
            field=models.UUIDField(
                default=clinic.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='id',
            field=models.UUIDField(
                default=clinic.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
