# Generated by Django 5.2.15 on 2026-06-22 10:53

from django.db import migrations

import core.fields

_COLS = ("reason", "symptoms", "treatment")


def _update(cursor, rid, updates):
    set_clause = ", ".join(f"{c} = %s" for c in updates)
    cursor.execute(
        f"UPDATE core_clinicvisit SET {set_clause} WHERE id = %s",  # noqa: S608 (أسماء أعمدة ثابتة)
        list(updates.values()) + [rid],
    )


def encrypt_existing(apps, schema_editor):
    """تشفير سجلّات العيادة الموجودة (نصّ صريح → Fernet). حارس ضدّ التشفير المزدوج."""
    from core.models import decrypt_field, encrypt_field

    with schema_editor.connection.cursor() as cur:
        cur.execute("SELECT id, reason, symptoms, treatment FROM core_clinicvisit")
        rows = cur.fetchall()
        for rid, *vals in rows:
            updates = {}
            for col, val in zip(_COLS, vals, strict=False):
                # decrypt_field يُعيد المُدخَل عند الفشل (fail-open) → قيمة == المُدخَل تعني نصّاً صريحاً
                if val and decrypt_field(val) == val:
                    updates[col] = encrypt_field(val)
            if updates:
                _update(cur, rid, updates)


def decrypt_existing(apps, schema_editor):
    """عكس: فكّ تشفير السجلّات (لإرجاع الحقول إلى نصّ صريح)."""
    from core.models import decrypt_field

    with schema_editor.connection.cursor() as cur:
        cur.execute("SELECT id, reason, symptoms, treatment FROM core_clinicvisit")
        rows = cur.fetchall()
        for rid, *vals in rows:
            updates = {}
            for col, val in zip(_COLS, vals, strict=False):
                if val:
                    dec = decrypt_field(val)
                    if dec != val:  # كان مشفّراً
                        updates[col] = dec
            if updates:
                _update(cur, rid, updates)


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0002_alter_clinicvisit_id_alter_healthrecord_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicvisit",
            name="reason",
            field=core.fields.EncryptedTextField(verbose_name="سبب الزيارة"),
        ),
        migrations.AlterField(
            model_name="clinicvisit",
            name="symptoms",
            field=core.fields.EncryptedTextField(blank=True, verbose_name="الأعراض"),
        ),
        migrations.AlterField(
            model_name="clinicvisit",
            name="treatment",
            field=core.fields.EncryptedTextField(blank=True, verbose_name="الإجراء المتخذ"),
        ),
        migrations.RunPython(encrypt_existing, decrypt_existing),
    ]
