# Generated by Django 5.2.17 on 2026-09-24 05:40

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_unify_medical_field_encryption"),
        ("core", "0071_arabic_field_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicvisit",
            name="nurse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nurse_visits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الممرّض",
            ),
        ),
        migrations.AlterField(
            model_name="clinicvisit",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="clinicvisit",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_visits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="clinicvisit",
            name="temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="درجة الحرارة",
            ),
        ),
        migrations.AlterField(
            model_name="clinicvisit",
            name="visit_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="وقت الزيارة"),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
                verbose_name="فصيلة الدم",
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="emergency_contact_name",
            field=core.fields.EncryptedTextField(
                blank=True, verbose_name="اسم جهة الطوارئ"
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="emergency_contact_phone",
            field=core.fields.EncryptedTextField(
                blank=True, verbose_name="هاتف جهة الطوارئ"
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_record",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
    ]
