# Generated by Django 5.2.17 on 2026-10-01 10:51

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0008_backfill_blood_type_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="hamad_hospital_number",
            field=core.fields.EncryptedTextField(
                blank=True, db_default="", default="", verbose_name="رقم مستشفى حمد"
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="health_card_number",
            field=core.fields.EncryptedTextField(
                blank=True,
                db_default="",
                default="",
                verbose_name="رقم الرعاية الصحية الرئيسي",
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="health_center_name",
            field=core.fields.EncryptedTextField(
                blank=True,
                db_default="",
                default="",
                verbose_name="اسم المركز الصحي الرئيسي",
            ),
        ),
    ]
