# Generated by Django 5.2.17 on 2026-10-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0009_healthrecord_hamad_hospital_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="needs_care",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="علامةٌ محايدةٌ تظهر للمعلّم في جدول رصد شعبته فقط، بلا سبب. يضعها الممرّض صراحةً.",
                verbose_name="يحتاج مراعاةً",
            ),
        ),
    ]
