# Generated by Django 5.2.12 on 2026-03-21 11:19

import django.db.models.deletion
import exam_control.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examenvelope',
            options={
                'ordering': ['timestamp'],
                'verbose_name': 'محضر مظروف',
                'verbose_name_plural': 'محاضر المظاريف',
            },
        ),
        migrations.AlterModelOptions(
            name='examgradesheet',
            options={'verbose_name': 'ورقة رصد', 'verbose_name_plural': 'أوراق الرصد'},
        ),
        migrations.AlterModelOptions(
            name='examincident',
            options={
                'ordering': ['-incident_time'],
                'verbose_name': 'حادث اختبار',
                'verbose_name_plural': 'حوادث الاختبارات',
            },
        ),
        migrations.AlterModelOptions(
            name='examroom',
            options={
                'ordering': ['name'],
                'verbose_name': 'قاعة اختبار',
                'verbose_name_plural': 'قاعات الاختبار',
            },
        ),
        migrations.AlterModelOptions(
            name='examschedule',
            options={
                'ordering': ['exam_date', 'start_time'],
                'verbose_name': 'جدول اختبار',
                'verbose_name_plural': 'جداول الاختبارات',
            },
        ),
        migrations.AlterModelOptions(
            name='examsession',
            options={
                'ordering': ['-start_date'],
                'verbose_name': 'دورة اختبار',
                'verbose_name_plural': 'دورات الاختبارات',
            },
        ),
        migrations.AlterModelOptions(
            name='examsupervisor',
            options={'verbose_name': 'مشرف كنترول', 'verbose_name_plural': 'مشرفو الكنترول'},
        ),
        migrations.AlterField(
            model_name='examenvelope',
            name='action',
            field=models.CharField(
                choices=[
                    ('received', 'استُلمت'),
                    ('opened', 'فُتحت'),
                    ('distributed', 'وُزِّعت'),
                    ('returned', 'أُعيدت'),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name='examenvelope',
            name='copies',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد النسخ'),
        ),
        migrations.AlterField(
            model_name='examenvelope',
            name='id',
            field=models.UUIDField(
                default=exam_control.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='examgradesheet',
            name='id',
            field=models.UUIDField(
                default=exam_control.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='examgradesheet',
            name='papers_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد الأوراق المستلمة'),
        ),
        migrations.AlterField(
            model_name='examgradesheet',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'في انتظار الرصد'),
                    ('graded', 'مُصحَّحة'),
                    ('submitted', 'مُسلَّمة'),
                ],
                default='pending',
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name='examincident',
            name='action_taken',
            field=models.TextField(blank=True, verbose_name='الإجراء الفوري'),
        ),
        migrations.AlterField(
            model_name='examincident',
            name='attachments',
            field=models.TextField(blank=True, verbose_name='المرفقات/الشهود'),
        ),
        migrations.AlterField(
            model_name='examincident',
            name='description',
            field=models.TextField(verbose_name='وصف الحادث التفصيلي'),
        ),
        migrations.AlterField(
            model_name='examincident',
            name='id',
            field=models.UUIDField(
                default=exam_control.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='examincident',
            name='incident_type',
            field=models.CharField(
                choices=[
                    ('cheating', 'غش مؤكد'),
                    ('misconduct', 'سوء سلوك'),
                    ('medical', 'حالة طبية'),
                    ('technical', 'عطل تقني'),
                    ('other', 'أخرى'),
                ],
                default='other',
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name='examincident',
            name='injuries',
            field=models.TextField(blank=True, verbose_name='الإصابات والأضرار'),
        ),
        migrations.AlterField(
            model_name='examincident',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='التوصيات'),
        ),
        migrations.AlterField(
            model_name='examincident',
            name='severity',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'بسيطة'), (2, 'متوسطة'), (3, 'جسيمة')], default=1
            ),
        ),
        migrations.AlterField(
            model_name='examincident',
            name='status',
            field=models.CharField(
                choices=[('open', 'مفتوحة'), ('referred', 'محالة'), ('resolved', 'منتهية')],
                default='open',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='examincident',
            name='student',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='exam_incidents',
                to=settings.AUTH_USER_MODEL,
                verbose_name='الطالب المعني',
            ),
        ),
        migrations.AlterField(
            model_name='examroom',
            name='id',
            field=models.UUIDField(
                default=exam_control.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='examroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم القاعة / الرقم'),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='id',
            field=models.UUIDField(
                default=exam_control.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='id',
            field=models.UUIDField(
                default=exam_control.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم دورة الاختبار'),
        ),
        migrations.AlterField(
            model_name='examsupervisor',
            name='id',
            field=models.UUIDField(
                default=exam_control.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='examsupervisor',
            name='role',
            field=models.CharField(
                choices=[
                    ('head', 'رئيس الكنترول'),
                    ('deputy', 'نائب الرئيس'),
                    ('secretary', 'أمين السر'),
                    ('print', 'مسؤول الطباعة'),
                    ('safe', 'مسؤول الخزائن'),
                    ('delivery', 'مسؤول التسليم'),
                    ('grading', 'مسؤول الرصد'),
                    ('audit', 'مسؤول التدقيق'),
                    ('supervisor', 'مشرف قاعة'),
                    ('observer', 'مراقب'),
                ],
                default='supervisor',
                max_length=15,
            ),
        ),
    ]
