# Generated by Django 5.2.12 on 2026-03-26 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_control', '0002_alter_examenvelope_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsupervisor',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='examsupervisor',
            constraint=models.UniqueConstraint(fields=('session', 'staff'), name='unique_exam_supervisor'),
        ),
    ]
