# Generated by Django 5.2.17 on 2026-08-28 08:05

import core.academic_calendar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_control", "0004_rls_parent_derived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsession",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=20
            ),
        ),
    ]
