# Generated by Django 5.2.17 on 2026-09-24 05:40

import core.academic_calendar
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behavior", "0019_arabic_field_labels"),
        ("core", "0071_arabic_field_labels"),
        ("exam_control", "0005_alter_examsession_academic_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="examenvelope",
            name="action",
            field=models.CharField(
                choices=[
                    ("received", "استُلمت"),
                    ("opened", "فُتحت"),
                    ("distributed", "وُزِّعت"),
                    ("returned", "أُعيدت"),
                ],
                max_length=15,
                verbose_name="الإجراء على المظروف",
            ),
        ),
        migrations.AlterField(
            model_name="examenvelope",
            name="done_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="المنفِّذ",
            ),
        ),
        migrations.AlterField(
            model_name="examenvelope",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="examenvelope",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="envelopes",
                to="exam_control.examschedule",
                verbose_name="موعد الاختبار",
            ),
        ),
        migrations.AlterField(
            model_name="examenvelope",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="الوقت"),
        ),
        migrations.AlterField(
            model_name="examenvelope",
            name="witness",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="witnessed_envelopes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الشاهد",
            ),
        ),
        migrations.AlterField(
            model_name="examgradesheet",
            name="grader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grade_sheets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المصحّح",
            ),
        ),
        migrations.AlterField(
            model_name="examgradesheet",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="examgradesheet",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_sheets",
                to="exam_control.examschedule",
                verbose_name="موعد الاختبار",
            ),
        ),
        migrations.AlterField(
            model_name="examgradesheet",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "في انتظار الرصد"),
                    ("graded", "مُصحَّحة"),
                    ("submitted", "مُسلَّمة"),
                ],
                default="pending",
                max_length=12,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="examgradesheet",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الإرسال"
            ),
        ),
        migrations.AlterField(
            model_name="examincident",
            name="behavior_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_incidents",
                to="behavior.behaviorinfraction",
                verbose_name="المخالفة السلوكيّة المرتبطة",
            ),
        ),
        migrations.AlterField(
            model_name="examincident",
            name="incident_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="وقت الحادثة"),
        ),
        migrations.AlterField(
            model_name="examincident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("cheating", "غش مؤكد"),
                    ("misconduct", "سوء سلوك"),
                    ("medical", "حالة طبية"),
                    ("technical", "عطل تقني"),
                    ("other", "أخرى"),
                ],
                default="other",
                max_length=15,
                verbose_name="نوع الحادثة",
            ),
        ),
        migrations.AlterField(
            model_name="examincident",
            name="reported_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_exam_incidents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المُبلِّغ",
            ),
        ),
        migrations.AlterField(
            model_name="examincident",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت المعالجة"
            ),
        ),
        migrations.AlterField(
            model_name="examincident",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="exam_control.examroom",
                verbose_name="اللجنة",
            ),
        ),
        migrations.AlterField(
            model_name="examincident",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="exam_control.examsession",
                verbose_name="دورة الاختبارات",
            ),
        ),
        migrations.AlterField(
            model_name="examincident",
            name="severity",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "بسيطة"), (2, "متوسطة"), (3, "جسيمة")],
                default=1,
                verbose_name="الخطورة",
            ),
        ),
        migrations.AlterField(
            model_name="examincident",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "مفتوحة"),
                    ("referred", "محالة"),
                    ("resolved", "منتهية"),
                ],
                default="open",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="examroom",
            name="capacity",
            field=models.PositiveSmallIntegerField(default=30, verbose_name="السعة"),
        ),
        migrations.AlterField(
            model_name="examroom",
            name="floor",
            field=models.CharField(blank=True, max_length=20, verbose_name="الطابق"),
        ),
        migrations.AlterField(
            model_name="examroom",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="examroom",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="exam_control.examsession",
                verbose_name="دورة الاختبارات",
            ),
        ),
        migrations.AlterField(
            model_name="examschedule",
            name="end_time",
            field=models.TimeField(verbose_name="وقت النهاية"),
        ),
        migrations.AlterField(
            model_name="examschedule",
            name="exam_date",
            field=models.DateField(verbose_name="تاريخ الاختبار"),
        ),
        migrations.AlterField(
            model_name="examschedule",
            name="grade_level",
            field=models.CharField(max_length=20, verbose_name="الصف"),
        ),
        migrations.AlterField(
            model_name="examschedule",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="exam_control.examroom",
                verbose_name="اللجنة",
            ),
        ),
        migrations.AlterField(
            model_name="examschedule",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="exam_control.examsession",
                verbose_name="دورة الاختبارات",
            ),
        ),
        migrations.AlterField(
            model_name="examschedule",
            name="start_time",
            field=models.TimeField(verbose_name="وقت البداية"),
        ),
        migrations.AlterField(
            model_name="examschedule",
            name="students_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="عدد الطلبة"
            ),
        ),
        migrations.AlterField(
            model_name="examschedule",
            name="subject",
            field=models.CharField(max_length=100, verbose_name="المادّة"),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=20,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_exam_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأه",
            ),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="end_date",
            field=models.DateField(verbose_name="تاريخ النهاية"),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_sessions",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("mid", "منتصف الفصل"),
                    ("final", "نهاية الفصل"),
                    ("makeup", "الدور الثاني"),
                ],
                default="final",
                max_length=10,
                verbose_name="نوع الدورة",
            ),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="start_date",
            field=models.DateField(verbose_name="تاريخ البداية"),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "مُخطَّطة"),
                    ("active", "جارية"),
                    ("completed", "منتهية"),
                ],
                default="planned",
                max_length=15,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="examsupervisor",
            name="assigned_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ التكليف"),
        ),
        migrations.AlterField(
            model_name="examsupervisor",
            name="role",
            field=models.CharField(
                choices=[
                    ("head", "رئيس الكنترول"),
                    ("deputy", "نائب الرئيس"),
                    ("secretary", "أمين السر"),
                    ("print", "مسؤول الطباعة"),
                    ("safe", "مسؤول الخزائن"),
                    ("delivery", "مسؤول التسليم"),
                    ("grading", "مسؤول الرصد"),
                    ("audit", "مسؤول التدقيق"),
                    ("supervisor", "مشرف قاعة"),
                    ("observer", "مراقب"),
                ],
                default="supervisor",
                max_length=15,
                verbose_name="المهمّة",
            ),
        ),
        migrations.AlterField(
            model_name="examsupervisor",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervisors",
                to="exam_control.examroom",
                verbose_name="اللجنة",
            ),
        ),
        migrations.AlterField(
            model_name="examsupervisor",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisors",
                to="exam_control.examsession",
                verbose_name="دورة الاختبارات",
            ),
        ),
        migrations.AlterField(
            model_name="examsupervisor",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الموظّف",
            ),
        ),
    ]
