# Generated by Django 5.0.6 on 2026-03-19 02:40

import quality.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_executor_mapping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operationalprocedure',
            new_name='quality_ope_school__126654_idx',
            old_name='quality_op__school__status_idx',
        ),
        migrations.RenameIndex(
            model_name='operationalprocedure',
            new_name='quality_ope_executo_275f02_idx',
            old_name='quality_op__exec_idx',
        ),
        migrations.RenameIndex(
            model_name='operationalprocedure',
            new_name='quality_ope_school__413866_idx',
            old_name='quality_op__year_idx',
        ),
        migrations.AlterField(
            model_name='executormapping',
            name='executor_norm',
            field=models.CharField(db_index=True, max_length=100, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='executormapping',
            name='id',
            field=models.UUIDField(
                default=quality.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
