# Generated by Django 5.0.6 on 2026-03-19 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_security_and_consent_fields'),
        (
            'quality',
            '0003_rename_quality_op__school__status_idx_quality_ope_school__126654_idx_and_more',
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalPlanExecutorCommittee',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('academic_year', models.CharField(default='2025-2026', max_length=9)),
                ('name', models.CharField(default='لجنة منفذي الخطة التشغيلية', max_length=100)),
                ('can_execute_plan', models.BooleanField(default=True)),
                ('can_review_plan', models.BooleanField(default=True)),
                ('can_report_progress', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'members',
                    models.ManyToManyField(
                        related_name='executor_committee_memberships', to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='executor_committees',
                        to='core.school',
                    ),
                ),
            ],
            options={
                'verbose_name': 'لجنة منفذي الخطة التشغيلية',
                'verbose_name_plural': 'لجان منفذي الخطة التشغيلية',
                'unique_together': {('school', 'academic_year')},
            },
        ),
    ]
