# Generated by Django 5.0.6 on 2026-03-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_add_committee_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualitycommitteemember',
            options={
                'ordering': ['committee_type', 'responsibility', 'job_title'],
                'verbose_name': 'عضو لجنة جودة',
                'verbose_name_plural': 'أعضاء لجنة الجودة',
            },
        ),
        migrations.RenameIndex(
            model_name='operationalprocedure',
            new_name='quality_ope_deadlin_39aa05_idx',
            old_name='quality_ope_deadlin_idx',
        ),
        migrations.AlterField(
            model_name='operationalprocedure',
            name='status',
            field=models.CharField(
                choices=[
                    ('Not Started', 'لم يبدأ'),
                    ('In Progress', 'قيد التنفيذ'),
                    ('Pending Review', 'بانتظار المراجعة'),
                    ('Completed', 'مكتمل'),
                    ('Cancelled', 'ملغى'),
                ],
                db_index=True,
                default='In Progress',
                max_length=20,
            ),
        ),
    ]
