# Generated by Django 5.2.12 on 2026-03-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_employee_evaluation'),
        ('quality', '0007_alter_qualitycommitteemember_options_and_more'),
    ]

    operations = []
