# Generated by Django 5.2.12 on 2026-03-21 11:19

import quality.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_merge_20260320_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeevaluation',
            name='id',
            field=models.UUIDField(
                default=quality.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='evaluationcycle',
            name='id',
            field=models.UUIDField(
                default=quality.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
