# Generated by Django 5.2.12 on 2026-03-23 06:07

import django.db.models.deletion
import quality.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_alter_employeeevaluation_id_alter_evaluationcycle_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalprocedure',
            name='evidence_request_note',
            field=models.TextField(blank=True, verbose_name='ملاحظات طلب الدليل'),
        ),
        migrations.AddField(
            model_name='operationalprocedure',
            name='evidence_request_status',
            field=models.CharField(choices=[('not_requested', 'غير مطلوب'), ('requested', 'مطلوب'), ('submitted', 'تم الرفع')], default='not_requested', max_length=20, verbose_name='حالة طلب الدليل'),
        ),
        migrations.AddField(
            model_name='operationalprocedure',
            name='quality_rating',
            field=models.CharField(blank=True, choices=[('', 'بدون تقييم'), ('متحقق', 'متحقق'), ('متحقق جزئيا', 'متحقق جزئياً'), ('غير متحقق', 'غير متحقق')], default='', max_length=20, verbose_name='التقييم النوعي للأداء'),
        ),
        migrations.CreateModel(
            name='ProcedureStatusLog',
            fields=[
                ('id', models.UUIDField(default=quality.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=20, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(max_length=20, verbose_name='الحالة الجديدة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_status_changes', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='quality.operationalprocedure')),
            ],
            options={
                'verbose_name': 'سجل تغيير حالة',
                'verbose_name_plural': 'سجل تغييرات الحالة',
                'ordering': ['-created_at'],
            },
        ),
    ]
