# Generated by Django 5.2.12 on 2026-03-25 00:03

import django.db.models.deletion
import quality.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_postgresql_rls_policies'),
        ('quality', '0010_add_evidence_request_quality_rating_status_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeevaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='المقيِّم الرئيسي'),
        ),
        migrations.CreateModel(
            name='RoleEvaluationTemplate',
            fields=[
                ('id', models.UUIDField(default=quality.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(help_text='يطابق Role.name — مثل teacher, nurse, librarian', max_length=30, verbose_name='الدور الوظيفي')),
                ('academic_year', models.CharField(default='2025-2026', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_templates', to='core.school')),
            ],
            options={
                'verbose_name': 'قالب تقييم دور',
                'verbose_name_plural': 'قوالب تقييم الأدوار',
            },
        ),
        migrations.CreateModel(
            name='EvaluationAxis',
            fields=[
                ('id', models.UUIDField(default=quality.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='معرّف برمجي — مثل professional, commitment, teaching_skills', max_length=50, verbose_name='معرّف المحور')),
                ('label', models.CharField(max_length=200, verbose_name='اسم المحور')),
                ('weight', models.PositiveSmallIntegerField(default=25, verbose_name='الوزن (من 100)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='quality.roleevaluationtemplate')),
            ],
            options={
                'verbose_name': 'محور تقييم',
                'verbose_name_plural': 'محاور التقييم',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.AddField(
            model_name='employeeevaluation',
            name='template',
            field=models.ForeignKey(blank=True, help_text='يُحدَّد تلقائياً حسب دور الموظف. null = المحاور الافتراضية', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='quality.roleevaluationtemplate', verbose_name='قالب التقييم'),
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.UUIDField(default=quality.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='وزن هذا المقيِّم — مثل 40 للمدير، 35 للنائب، 25 للمنسق', verbose_name='الوزن (%)')),
                ('axis_professional', models.PositiveSmallIntegerField(default=0)),
                ('axis_commitment', models.PositiveSmallIntegerField(default=0)),
                ('axis_teamwork', models.PositiveSmallIntegerField(default=0)),
                ('axis_development', models.PositiveSmallIntegerField(default=0)),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('custom_axes', models.JSONField(blank=True, default=dict, help_text='{"teaching_skills": 20, "classroom_mgmt": 22, ...}', verbose_name='محاور مخصصة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات المقيِّم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quality.employeeevaluation')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_scores_given', to=settings.AUTH_USER_MODEL, verbose_name='المقيِّم')),
            ],
            options={
                'verbose_name': 'تقييم مقيِّم',
                'verbose_name_plural': 'تقييمات المقيِّمين',
                'ordering': ['-weight'],
                'constraints': [models.UniqueConstraint(fields=('evaluation', 'evaluator'), name='unique_score_per_evaluator')],
            },
        ),
        migrations.AddConstraint(
            model_name='roleevaluationtemplate',
            constraint=models.UniqueConstraint(fields=('school', 'role_name', 'academic_year'), name='unique_eval_template_per_role_year'),
        ),
        migrations.AddConstraint(
            model_name='evaluationaxis',
            constraint=models.UniqueConstraint(fields=('template', 'key'), name='unique_axis_per_template'),
        ),
    ]
