# Generated by Django 5.2.14 on 2026-06-21 14:00

import django.db.models.deletion
import django.utils.timezone
import quality.observation_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_parentstudentlink_can_view_behavior_and_more'),
        ('operations', '0016_add_excuse_file_validator'),
        ('quality', '0011_add_role_templates_multi_evaluator_and_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomObservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('id', models.UUIDField(default=quality.observation_models._uuid, editable=False, primary_key=True, serialize=False)),
                ('observation_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الحصة')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='الموضوع')),
                ('follow_up_mode', models.CharField(blank=True, choices=[('field', 'ميدانيّة'), ('remote', 'عن بُعد')], max_length=10, verbose_name='نوع المتابعة')),
                ('follow_up_scope', models.CharField(blank=True, choices=[('partial', 'جزئيّة'), ('full', 'كلّيّة')], max_length=10)),
                ('broadcast_note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات البث')),
                ('general_notes', models.TextField(blank=True, verbose_name='ملاحظات وتوصيات عامّة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُرسَلة للمعلّم'), ('acknowledged', 'مُقَرّة من المعلّم')], default='draft', max_length=15)),
                ('score_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='النسبة الإجماليّة')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True, verbose_name='تعليق المعلّم')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classgroup', verbose_name='الصّف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations_made', to=settings.AUTH_USER_MODEL, verbose_name='الزائر')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_observations', to='core.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.subject', verbose_name='المادّة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations_received', to=settings.AUTH_USER_MODEL, verbose_name='المعلّم')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عدّله')),
            ],
            options={
                'verbose_name': 'ملاحظة صفّية',
                'verbose_name_plural': 'الملاحظات الصفّية',
                'ordering': ['-observation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationCriterion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('id', models.UUIDField(default=quality.observation_models._uuid, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('planning', 'التخطيط'), ('execution', 'تنفيذ الدرس'), ('assessment', 'التقويم'), ('management', 'الإدارة الصفية وبيئة التعلم')], max_length=20, verbose_name='المجال')),
                ('text', models.TextField(verbose_name='معيار الأداء')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_criteria', to='core.school')),
            ],
            options={
                'verbose_name': 'معيار ملاحظة صفّية',
                'verbose_name_plural': 'معايير الملاحظة الصفّية',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ObservationScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('id', models.UUIDField(default=quality.observation_models._uuid, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(blank=True, choices=[('complete', 'الأدلة مستكملة وفاعلة'), ('most', 'تتوفر معظم الأدلة'), ('some', 'تتوفر بعض الأدلة'), ('limited', 'الأدلة غير متوفرة أو محدودة'), ('not_measured', 'لم يتم قياسه')], max_length=15)),
                ('recommendation', models.TextField(blank=True, verbose_name='التوصية')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='quality.observationcriterion')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quality.classroomobservation')),
            ],
            options={
                'verbose_name': 'تقييم معيار',
                'verbose_name_plural': 'تقييمات المعايير',
                'ordering': ['criterion__order'],
            },
        ),
        migrations.AddIndex(
            model_name='classroomobservation',
            index=models.Index(fields=['school', 'teacher', 'observation_date'], name='quality_cla_school__9223eb_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomobservation',
            index=models.Index(fields=['school', 'status'], name='quality_cla_school__357d33_idx'),
        ),
        migrations.AddConstraint(
            model_name='observationcriterion',
            constraint=models.UniqueConstraint(fields=('school', 'domain', 'text'), name='uniq_observation_criterion'),
        ),
        migrations.AddConstraint(
            model_name='observationscore',
            constraint=models.UniqueConstraint(fields=('observation', 'criterion'), name='uniq_observation_score'),
        ),
    ]
