# Generated by Django 5.2.14 on 2026-06-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0012_classroomobservation_observationcriterion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomobservation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='classroomobservation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محذوف'),
        ),
        migrations.AddField(
            model_name='classroomobservation',
            name='submission_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
