# Generated by Django 5.2.14 on 2026-06-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0013_classroomobservation_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomobservation',
            name='kind',
            field=models.CharField(choices=[('supervision', 'زيارة إشرافية'), ('self', 'تقييم ذاتي')], default='supervision', max_length=12, verbose_name='نوع التقييم'),
        ),
    ]
