# Generated by Django 5.2.17 on 2026-08-28 08:05

import core.academic_calendar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0015_rls_parent_derived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeevaluation",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="evaluationcycle",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="executormapping",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="operationaldomain",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="operationalprocedure",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="qualitycommitteemember",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="roleevaluationtemplate",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
    ]
