# Generated by Django 5.2.17 on 2026-08-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0016_alter_employeeevaluation_academic_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroomobservation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("supervision", "زيارة إشرافية"),
                    ("self", "تقييم ذاتي"),
                    ("peer", "زيارة زميل"),
                ],
                default="supervision",
                max_length=12,
                verbose_name="نوع التقييم",
            ),
        ),
    ]
