# Generated by Django 5.2.17 on 2026-09-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0021_employeeevaluation_approved_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeevaluation",
            name="grievance_outcome",
            field=models.CharField(
                blank=True,
                choices=[("rejected", "رفضُ التظلّم"), ("modified", "تعديلُ التقرير")],
                db_default="",
                max_length=10,
                verbose_name="قرار اللجنة في التظلّم",
            ),
        ),
        migrations.AddField(
            model_name="employeeevaluation",
            name="grievance_reason",
            field=models.TextField(
                blank=True, db_default="", verbose_name="سبب التظلّم"
            ),
        ),
    ]
