# Generated by Django 5.2.17 on 2026-09-24 05:40

import core.academic_calendar
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_arabic_field_labels"),
        ("quality", "0022_employeeevaluation_grievance_reason_outcome"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroomobservation",
            name="follow_up_scope",
            field=models.CharField(
                blank=True,
                choices=[("partial", "جزئيّة"), ("full", "كلّيّة")],
                max_length=10,
                verbose_name="نطاق المتابعة",
            ),
        ),
        migrations.AlterField(
            model_name="classroomobservation",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_observations",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="classroomobservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("submitted", "مُرسَلة للمعلّم"),
                    ("acknowledged", "مُقَرّة من المعلّم"),
                ],
                default="draft",
                max_length=15,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="classroomobservation",
            name="submission_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="مرّات الإرسال"
            ),
        ),
        migrations.AlterField(
            model_name="classroomobservation",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الإرسال"
            ),
        ),
        migrations.AlterField(
            model_name="classroomobservation",
            name="teacher_acknowledged_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ اطّلاع المعلّم"
            ),
        ),
        migrations.AlterField(
            model_name="employeeevaluation",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="employeeevaluation",
            name="acknowledged_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ اطّلاع الموظّف"
            ),
        ),
        migrations.AlterField(
            model_name="employeeevaluation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="employeeevaluation",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "ممتاز (100–90)"),
                    ("very_good", "جيد جداً (89–76)"),
                    ("good", "جيد (75–66)"),
                    ("acceptable", "مقبول (65–50)"),
                    ("weak", "ضعيف (أقل من 50)"),
                ],
                max_length=15,
                verbose_name="التقدير",
            ),
        ),
        migrations.AlterField(
            model_name="employeeevaluation",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="employeeevaluation",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("submitted", "مُقدَّم"),
                    ("approved", "مُعتمد"),
                    ("acknowledged", "مُستلم من الموظف"),
                ],
                default="draft",
                max_length=15,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="employeeevaluation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="evaluationaxis",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
        ),
        migrations.AlterField(
            model_name="evaluationaxis",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="axes",
                to="quality.roleevaluationtemplate",
                verbose_name="قالب التقييم",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationcycle",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationcycle",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="evaluationcycle",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأه",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationcycle",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="مغلقة"),
        ),
        migrations.AlterField(
            model_name="evaluationcycle",
            name="period",
            field=models.CharField(
                choices=[
                    ("S1", "متابعة منتصف العام (داخليّة، غير وزاريّة)"),
                    ("S2", "التقرير السنويّ (الوزاريّ)"),
                ],
                max_length=2,
                verbose_name="الفترة",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationcycle",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eval_cycles",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationlevelbackup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="evaluationscore",
            name="axis_commitment",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="محور الالتزام"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationscore",
            name="axis_development",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="محور التطوير"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationscore",
            name="axis_professional",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="المحور المهنيّ"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationscore",
            name="axis_teamwork",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="محور العمل الجماعيّ"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationscore",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="evaluationscore",
            name="evaluation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="quality.employeeevaluation",
                verbose_name="التقييم",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationscore",
            name="total_score",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="المجموع"),
        ),
        migrations.AlterField(
            model_name="evaluationscore",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="executormapping",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="executormapping",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="executormapping",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executor_mappings",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="executormapping",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="observationcriterion",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="observationcriterion",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
        ),
        migrations.AlterField(
            model_name="observationcriterion",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observation_criteria",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="observationscore",
            name="criterion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scores",
                to="quality.observationcriterion",
                verbose_name="المعيار",
            ),
        ),
        migrations.AlterField(
            model_name="observationscore",
            name="observation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="quality.classroomobservation",
                verbose_name="الزيارة الصفّيّة",
            ),
        ),
        migrations.AlterField(
            model_name="observationscore",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("complete", "الأدلة مستكملة وفاعلة"),
                    ("most", "تتوفر معظم الأدلة"),
                    ("some", "تتوفر بعض الأدلة"),
                    ("limited", "الأدلة غير متوفرة أو محدودة"),
                    ("not_measured", "لم يتم قياسه"),
                ],
                max_length=15,
                verbose_name="التقدير",
            ),
        ),
        migrations.AlterField(
            model_name="operationaldomain",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="operationaldomain",
            name="order",
            field=models.IntegerField(default=0, verbose_name="الترتيب"),
        ),
        migrations.AlterField(
            model_name="operationaldomain",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="op_domains",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="operationalindicator",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicators",
                to="quality.operationaltarget",
                verbose_name="الهدف",
            ),
        ),
        migrations.AlterField(
            model_name="operationalprocedure",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="operationalprocedure",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="operationalprocedure",
            name="evidence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("وصفي", "وصفي"),
                    ("كمي", "كمي"),
                    ("كمي/وصفي", "كمي/وصفي"),
                    ("", "—"),
                ],
                max_length=20,
                verbose_name="نوع الشاهد",
            ),
        ),
        migrations.AlterField(
            model_name="operationalprocedure",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedures",
                to="quality.operationalindicator",
                verbose_name="المؤشّر",
            ),
        ),
        migrations.AlterField(
            model_name="operationalprocedure",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedures",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="operationalprocedure",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Started", "لم يبدأ"),
                    ("In Progress", "قيد التنفيذ"),
                    ("Pending Review", "بانتظار المراجعة"),
                    ("Completed", "مكتمل"),
                    ("Cancelled", "ملغى"),
                ],
                db_index=True,
                default="In Progress",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="operationalprocedure",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="operationaltarget",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="quality.operationaldomain",
                verbose_name="المجال",
            ),
        ),
        migrations.AlterField(
            model_name="procedureevidence",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="procedureevidence",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف"),
        ),
        migrations.AlterField(
            model_name="procedureevidence",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="evidence/%Y/%m/", verbose_name="الملف"
            ),
        ),
        migrations.AlterField(
            model_name="procedureevidence",
            name="procedure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidences",
                to="quality.operationalprocedure",
                verbose_name="الإجراء التشغيلي",
            ),
        ),
        migrations.AlterField(
            model_name="procedureevidence",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_evidences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رفعه",
            ),
        ),
        migrations.AlterField(
            model_name="procedurestatuslog",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procedure_status_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="غيّر الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="procedurestatuslog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="procedurestatuslog",
            name="procedure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="quality.operationalprocedure",
                verbose_name="الإجراء التشغيلي",
            ),
        ),
        migrations.AlterField(
            model_name="qualitycommitteemember",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="qualitycommitteemember",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="qualitycommitteemember",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_members",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="qualitycommitteemember",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="roleevaluationtemplate",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="roleevaluationtemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="roleevaluationtemplate",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="roleevaluationtemplate",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eval_templates",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
    ]
