# Generated by Django 5.2.13 on 2026-08-31 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0045_school_letterfoot_school_letterhead'),
        ('operations', '0020_remove_scheduleslot_no_class_period_overlap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWorkloadPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('academic_year', models.CharField(max_length=9, verbose_name='العام الدراسي')),
                ('plan_version', models.PositiveIntegerField(default=1, verbose_name='نسخة الخطة')),
                ('required_weekly_periods', models.PositiveIntegerField(verbose_name='النصاب الأسبوعي المعتمد')),
                ('required_source_kind', models.CharField(choices=[('policy', 'سياسةُ نصابٍ مسجّلة'), ('previous_plan', 'نسخٌ من خطّةٍ سابقة'), ('manual', 'إدخالٌ إداريٌّ موثَّق')], default='manual', max_length=14, verbose_name='منبع النصاب')),
                ('required_source_reference', models.CharField(blank=True, help_text='رقمُ التعميم أو المحضر أو رمزُ السياسة', max_length=200, verbose_name='مرجع النصاب')),
                ('required_policy_key', models.CharField(blank=True, max_length=60, verbose_name='رمز سياسة النصاب')),
                ('reduction_periods', models.PositiveIntegerField(default=0, verbose_name='حصص التخفيض')),
                ('reduction_reason', models.CharField(blank=True, max_length=200, verbose_name='سبب التخفيض')),
                ('reduction_source', models.CharField(blank=True, choices=[('ministry', 'قرارُ الوزارة'), ('school', 'قرارُ إدارة المدرسة'), ('department', 'قرارُ القسم الأكاديميّ'), ('other', 'أخرى')], max_length=12, verbose_name='جهة قرار التخفيض')),
                ('reduction_source_reference', models.CharField(blank=True, max_length=200, verbose_name='مرجع قرار التخفيض')),
                ('status', models.CharField(choices=[('draft', 'مسودّة'), ('submitted', 'قيد المراجعة'), ('reviewed', 'روجعت — بانتظار الاعتماد'), ('approved', 'معتمدة'), ('locked', 'مقفلة للجدولة')], default='draft', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفع')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_comment', models.CharField(blank=True, max_length=400, verbose_name='ملاحظة المراجع')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('self_approval_override', models.BooleanField(default=False, verbose_name='اعتُمدت بمن راجعها')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workload_plans', to=settings.AUTH_USER_MODEL, verbose_name='اعتمدها')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('required_source_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_into', to='academic_management.teacherworkloadplan', verbose_name='منسوخٌ عن خطّة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_workload_plans', to=settings.AUTH_USER_MODEL, verbose_name='راجعها')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_plans', to='core.school')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_workload_plans', to=settings.AUTH_USER_MODEL, verbose_name='رفعها للمراجعة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_plans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عدّله')),
            ],
            options={
                'verbose_name': 'خطة نصاب معلم',
                'verbose_name_plural': 'خطط أنصبة المعلمين',
                'ordering': ['teacher__full_name', '-plan_version'],
            },
        ),
        migrations.CreateModel(
            name='TeacherWorkloadAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('prep', 'إعدادي'), ('sec', 'ثانوي')], max_length=4, verbose_name='المرحلة')),
                ('target_periods', models.PositiveIntegerField(verbose_name='الحصص المستهدفة')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('workload_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academic_management.teacherworkloadplan')),
            ],
            options={
                'verbose_name': 'توزيع نصاب حسب المرحلة',
                'verbose_name_plural': 'توزيعات النصاب حسب المرحلة',
                'ordering': ['level_type'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadGovernance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_roles', models.JSONField(blank=True, default=list, verbose_name='أدوار الإدخال')),
                ('review_roles', models.JSONField(blank=True, default=list, verbose_name='أدوار المراجعة')),
                ('approve_roles', models.JSONField(blank=True, default=list, verbose_name='أدوار الاعتماد')),
                ('allow_self_approval', models.BooleanField(default=False, verbose_name='يجوز أن يعتمدها من راجعها')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workload_governance', to='core.school')),
            ],
            options={
                'verbose_name': 'حوكمة أنصبة المدرسة',
                'verbose_name_plural': 'حوكمة أنصبة المدارس',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('level_type', models.CharField(blank=True, choices=[('prep', 'إعدادي'), ('sec', 'ثانوي')], max_length=4, verbose_name='المرحلة')),
                ('qualification_status', models.CharField(choices=[('primary', 'تخصّصٌ أساسيّ'), ('qualified', 'مؤهَّل'), ('allowed', 'مسموحٌ به'), ('not_approved', 'غيرُ معتمَد')], default='qualified', max_length=12)),
                ('is_primary', models.BooleanField(default=False, verbose_name='تخصّصه الأساسي؟')),
                ('source', models.CharField(choices=[('ministry', 'قرارُ الوزارة'), ('school', 'قرارُ إدارة المدرسة'), ('department', 'قرارُ القسم الأكاديميّ'), ('other', 'أخرى')], default='school', max_length=12)),
                ('source_reference', models.CharField(blank=True, max_length=200, verbose_name='مرجع القرار')),
                ('valid_from', models.DateField(verbose_name='سارٍ من')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='سارٍ حتى')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_qualifications', to='core.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_qualifications', to='operations.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_qualifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عدّله')),
            ],
            options={
                'verbose_name': 'مؤهل معلم لمادة',
                'verbose_name_plural': 'مؤهلات المعلمين للمواد',
                'ordering': ['teacher__full_name', 'subject__name_ar'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'level_type'), name='unique_qualification_per_level')],
            },
        ),
        migrations.AddConstraint(
            model_name='teacherworkloadplan',
            constraint=models.UniqueConstraint(fields=('school', 'teacher', 'academic_year', 'plan_version'), name='unique_workload_plan_version'),
        ),
        migrations.AddConstraint(
            model_name='teacherworkloadplan',
            constraint=models.CheckConstraint(condition=models.Q(('reduction_periods__lte', models.F('required_weekly_periods'))), name='reduction_within_required_load'),
        ),
        migrations.AddConstraint(
            model_name='teacherworkloadallocation',
            constraint=models.UniqueConstraint(fields=('workload_plan', 'level_type'), name='unique_allocation_per_level'),
        ),
    ]
