"""بصمةُ ما فُحص لحظةَ الاعتماد.

المعاملةُ تمنع التغيّرَ أثناء الاعتماد ولا تحفظ ما كان قائماً حينه. وبدون
هذه الحقول لا نستطيع بعد أشهرٍ أن نفرّق بين خطّةٍ صحّت ثمّ تباعد عنها
الإسناد، وخطّةٍ وُلدت خاطئة.
"""

# Generated by Django 5.2.13 on 2026-08-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_management', '0002_rls_workload_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherworkloadplan',
            name='validated_assignment_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الإسنادات المفحوصة'),
        ),
        migrations.AddField(
            model_name='teacherworkloadplan',
            name='validated_assignment_periods',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حصص الإسنادات المفحوصة'),
        ),
        migrations.AddField(
            model_name='teacherworkloadplan',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='لحظة الفحص'),
        ),
        migrations.AddField(
            model_name='teacherworkloadplan',
            name='validation_fingerprint',
            field=models.CharField(blank=True, max_length=64, verbose_name='بصمة الإسنادات المفحوصة'),
        ),
    ]
