"""الخطّةُ الدراسيّةُ مصدرَ الطلب، وحذفُ المؤهّلات، ونصابٌ مرجعيٌّ وعبءُ تحضير.

ثلاثةُ تغييراتٍ في ترحيلٍ واحدٍ لأنّها قرارٌ واحد: أن يصير للطلب مصدرٌ يُقاس
عليه، وأن يُرفع عن الخطّة شرطٌ لا تملك المدرسةُ بياناتِه.

وحذفُ `TeacherSubjectQualification` قرارُ الإدارة (2026-09-05): في مدرسةٍ
واحدةٍ يعرف المنسّقُ والنائبُ من يدرّس ماذا، وسجلُّ مؤهّلٍ بمرجعٍ لكلّ
(معلّم، مادّة) عبءُ إدخالٍ بلا قرارٍ إداريٍّ يقابله. والجدولُ فارغٌ على
الإنتاج، فلا بيانَ يضيع. وكان شرطاه في بوّابة الاعتماد يمنعان اعتمادَ أيّ
خطّةِ نصابٍ ما دام لا مؤهّلَ مسجَّلاً — أي دائماً.

وسياسةُ العزل على الجدول الجديد في `0005`، وتذهب سياسةُ المؤهّلات مع جدولها.
"""

# Generated by Django 5.2.17 on 2026-09-05 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_management", "0003_validation_fingerprint"),
        ("core", "0052_classgroup_has_own_timetable"),
        ("operations", "0034_rls_schedulebaseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workloadgovernance",
            name="preparation_weight",
            field=models.PositiveIntegerField(
                default=2,
                help_text="عددُ الحصص التي يُحتسب بها تحضيرُ مقرّرٍ واحد",
                verbose_name="عبء تحضير المقرّر",
            ),
        ),
        migrations.AddField(
            model_name="workloadgovernance",
            name="reference_load",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="يُقاس عليه من لا خطّةَ معتمَدةً له — فارغٌ يعني لا مقارنة",
                null=True,
                verbose_name="النصاب المرجعيّ",
            ),
        ),
        migrations.CreateModel(
            name="CurriculumPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=9, verbose_name="العام الدراسي"),
                ),
                ("grade", models.CharField(max_length=3, verbose_name="الصف")),
                (
                    "track",
                    models.CharField(blank=True, max_length=12, verbose_name="المسار"),
                ),
                (
                    "weekly_periods",
                    models.PositiveIntegerField(verbose_name="الحصص الأسبوعية"),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("ministry_guide", "دليلُ الخطط الدراسيّة الوزاريّ"),
                            ("pilot", "تجربةٌ وزاريّةٌ على مدارسَ مختارة"),
                            ("school_decision", "قرارُ إدارة المدرسة"),
                        ],
                        default="ministry_guide",
                        max_length=16,
                        verbose_name="منبع الرقم",
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="مثال: دليل الخطط الدراسية 2025-2026 ص14",
                        max_length=200,
                        verbose_name="المرجع",
                    ),
                ),
                (
                    "is_pilot",
                    models.BooleanField(default=False, verbose_name="تجريبيّة"),
                ),
                (
                    "elective_group",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="فارغٌ للمادّة الإلزاميّة؛ والبدائلُ تتقاسم وسماً واحداً",
                        max_length=40,
                        verbose_name="مجموعة الاختيار",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curriculum_rows",
                        to="core.department",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_plans",
                        to="core.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_rows",
                        to="operations.subject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "صفّ خطة دراسية",
                "verbose_name_plural": "الخطة الدراسية",
                "ordering": ["grade", "track", "subject__name_ar"],
            },
        ),
        migrations.DeleteModel(
            name="TeacherSubjectQualification",
        ),
        migrations.AddIndex(
            model_name="curriculumplan",
            index=models.Index(
                fields=["school", "academic_year", "grade"],
                name="academic_ma_school__06898a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumplan",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year", "grade", "track", "subject"),
                name="unique_curriculum_row",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekly_periods__gt", 0)),
                name="curriculum_periods_positive",
            ),
        ),
    ]
