"""إسنادُ التحضير، وصرامةُ المدرسة في نتائج الإسناد.

`CoursePreparation`: من يحضّر هذا المقرّرَ للجميع — مسؤوليّةٌ واحدةٌ لمقرّرٍ
واحدٍ في العام (صفّ × مسار × مادّة). وكانت تُوزَّع شفاهاً ولا يحملها النظام،
فلا تظهر في حمل المعلّم ولا في كشفه ولا يُبلَّغ بها.

    PreparationLoad = PreparedCourses × preparation_weight
    TotalLoad       = TeachingLoad + PreparationLoad

و`strict_codes`: ما ترفعه المدرسةُ من تحذيرات الإسناد إلى موانع — تهيئةٌ لا
شرطٌ محفورٌ في الكود، فمدرسةٌ تمنع تجاوزَ الهدف وأخرى تكتفي بالتحذير.

وسياسةُ العزل للجدول الجديد في `0007`.
"""

# Generated by Django 5.2.17 on 2026-09-05 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_management", "0005_rls_curriculum_plan"),
        ("core", "0053_ese_own_timetable"),
        ("operations", "0035_assignment_audited"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workloadgovernance",
            name="strict_codes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="رموزُ نتائج الإسناد التي ترفعها المدرسةُ من تحذيرٍ إلى منع",
                verbose_name="تحذيراتٌ تُعدّ موانع",
            ),
        ),
        migrations.CreateModel(
            name="CoursePreparation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=9, verbose_name="العام الدراسي"),
                ),
                ("grade", models.CharField(max_length=3, verbose_name="الصف")),
                (
                    "track",
                    models.CharField(
                        blank=True, default="", max_length=12, verbose_name="المسار"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_preparations",
                        to="core.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_preparations",
                        to="operations.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_preparations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّله",
                    ),
                ),
            ],
            options={
                "verbose_name": "إسناد تحضير مقرّر",
                "verbose_name_plural": "إسنادات تحضير المقرّرات",
                "ordering": ["grade", "track", "subject__name_ar"],
                "indexes": [
                    models.Index(
                        fields=["school", "academic_year", "teacher"],
                        name="academic_ma_school__6e2251_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "academic_year", "grade", "track", "subject"),
                        name="unique_preparer_per_course",
                    )
                ],
            },
        ),
    ]
