# Generated by Django 5.2.17 on 2026-09-24 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_management", "0008_coordinator_entry_pause"),
        ("core", "0071_arabic_field_labels"),
        ("operations", "0057_arabic_field_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepreparation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="coursepreparation",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_preparations",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="coursepreparation",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_preparations",
                to="operations.subject",
                verbose_name="المادّة",
            ),
        ),
        migrations.AlterField(
            model_name="coursepreparation",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_preparations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المعلّم",
            ),
        ),
        migrations.AlterField(
            model_name="curriculumplan",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="curriculumplan",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curriculum_plans",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="curriculumplan",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="curriculum_rows",
                to="operations.subject",
                verbose_name="المادّة",
            ),
        ),
        migrations.AlterField(
            model_name="teacherworkloadallocation",
            name="workload_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="academic_management.teacherworkloadplan",
                verbose_name="خطّة النصاب",
            ),
        ),
        migrations.AlterField(
            model_name="teacherworkloadplan",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workload_plans",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="teacherworkloadplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودّة"),
                    ("submitted", "قيد المراجعة"),
                    ("reviewed", "روجعت — بانتظار الاعتماد"),
                    ("approved", "معتمدة"),
                    ("locked", "مقفلة للجدولة"),
                ],
                default="draft",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="teacherworkloadplan",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workload_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المعلّم",
            ),
        ),
        migrations.AlterField(
            model_name="workloadgovernance",
            name="entry_changed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت آخر تبديل للوقف"
            ),
        ),
        migrations.AlterField(
            model_name="workloadgovernance",
            name="entry_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="آخر من بدّل الوقف",
            ),
        ),
        migrations.AlterField(
            model_name="workloadgovernance",
            name="school",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workload_governance",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
    ]
