# Generated by Django 5.2.17 on 2026-09-24 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_arabic_field_labels"),
        ("staging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importlog",
            options={
                "ordering": ["-started_at"],
                "verbose_name": "سجل استيراد",
                "verbose_name_plural": "سجلات الاستيراد",
            },
        ),
        migrations.AlterField(
            model_name="importlog",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الاكتمال"
            ),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="error_log",
            field=models.JSONField(
                blank=True, default=list, verbose_name="سجلّ الأخطاء"
            ),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="failed_rows",
            field=models.IntegerField(default=0, verbose_name="الصفوف الفاشلة"),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="file_name",
            field=models.CharField(max_length=255, verbose_name="اسم الملف"),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="imported_rows",
            field=models.IntegerField(default=0, verbose_name="الصفوف المستوردة"),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="وقت البدء"),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المعالجة"),
                    ("validating", "جاري التحقق"),
                    ("importing", "جاري الاستيراد"),
                    ("completed", "مكتمل"),
                    ("failed", "فشل"),
                ],
                default="pending",
                max_length=15,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="total_rows",
            field=models.IntegerField(default=0, verbose_name="إجمالي الصفوف"),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="رفعه",
            ),
        ),
    ]
