# Generated by Django 5.2.12 on 2026-03-29 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_alter_role_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('activity_type', models.CharField(choices=[('club', 'نادٍ / جماعة'), ('competition', 'مسابقة'), ('award', 'جائزة / تكريم'), ('certificate', 'شهادة'), ('volunteer', 'عمل تطوعي'), ('sports', 'رياضة'), ('cultural', 'نشاط ثقافي'), ('scientific', 'نشاط علمي'), ('other', 'أخرى')], max_length=20, verbose_name='نوع النشاط')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='الوصف')),
                ('scope', models.CharField(choices=[('school', 'مستوى المدرسة'), ('district', 'مستوى المنطقة'), ('national', 'مستوى وطني'), ('international', 'مستوى دولي')], default='school', max_length=15, verbose_name='النطاق')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('academic_year', models.CharField(default='2025-2026', max_length=9, verbose_name='العام الدراسي')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='student_activities/%Y/%m/', verbose_name='مرفق')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_activities', to=settings.AUTH_USER_MODEL, verbose_name='سُجّل بواسطة')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.school', verbose_name='المدرسة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'نشاط طلابي',
                'verbose_name_plural': 'أنشطة طلابية',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['school', 'student', 'activity_type'], name='student_aff_school__98960e_idx'), models.Index(fields=['school', 'academic_year'], name='student_aff_school__181e3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('direction', models.CharField(choices=[('in', 'وارد'), ('out', 'صادر')], max_length=3, verbose_name='اتجاه الانتقال')),
                ('other_school_name', models.CharField(max_length=200, verbose_name='المدرسة الأخرى')),
                ('from_grade', models.CharField(blank=True, max_length=3, verbose_name='الصف (من)')),
                ('to_grade', models.CharField(blank=True, max_length=3, verbose_name='الصف (إلى)')),
                ('transfer_date', models.DateField(verbose_name='تاريخ الانتقال')),
                ('reason', models.TextField(blank=True, max_length=1000, verbose_name='سبب الانتقال')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], db_index=True, default='pending', max_length=15, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('academic_year', models.CharField(default='2025-2026', max_length=9, verbose_name='العام الدراسي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_transfers', to='core.school', verbose_name='المدرسة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عدّله')),
            ],
            options={
                'verbose_name': 'انتقال طالب',
                'verbose_name_plural': 'انتقالات الطلاب',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'student', 'status'], name='student_aff_school__21a443_idx'), models.Index(fields=['school', 'direction', 'status'], name='student_aff_school__0ac4a2_idx')],
            },
        ),
    ]
