# Generated by Django 5.2.17 on 2026-08-28 08:05

import core.academic_calendar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_affairs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentactivity",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="studenttransfer",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
    ]
