# Generated by Django 5.2.17 on 2026-10-10 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_role_student_affairs_coordinator"),
        ("student_affairs", "0002_alter_studentactivity_academic_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenttransfer",
            name="to_class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_internal_transfers",
                to="core.classgroup",
                verbose_name="الشعبة المنقول إليها",
            ),
        ),
        migrations.AlterField(
            model_name="studenttransfer",
            name="direction",
            field=models.CharField(
                choices=[
                    ("in", "وارد"),
                    ("out", "صادر"),
                    ("internal", "داخلي (بين شعب المدرسة)"),
                ],
                max_length=10,
                verbose_name="اتجاه الانتقال",
            ),
        ),
    ]
