# Generated by Django 5.2.12 on 2026-03-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operations_search_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='session_date_btree_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='session_teacher_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='session_class_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='session_status_btree_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentattendance',
            name='attendance_student_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentattendance',
            name='attendance_session_status_idx',
        ),
    ]
