# Generated by Django 5.2.12 on 2026-03-24 01:15

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_erasure_request_model'),
        ('operations', '0004_remove_session_session_date_btree_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleGeneration',
            fields=[
                ('id', models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('archived', 'مؤرشف')], default='draft', max_length=10)),
                ('quality_score', models.FloatField(default=0, verbose_name='نقاط الجودة (0-100)')),
                ('hard_violations', models.IntegerField(default=0, verbose_name='انتهاكات صلبة')),
                ('soft_violations', models.JSONField(default=dict, verbose_name='انتهاكات مرنة')),
                ('total_slots_created', models.IntegerField(default=0)),
                ('generation_time_ms', models.IntegerField(default=0, verbose_name='زمن التوليد (مللي ثانية)')),
                ('config_snapshot', models.JSONField(default=dict, verbose_name='نسخة الإعدادات')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_generations', to='core.school')),
            ],
            options={
                'verbose_name': 'عملية توليد جدول',
                'verbose_name_plural': 'عمليات توليد الجدول',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectClassAssignment',
            fields=[
                ('id', models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('weekly_periods', models.PositiveIntegerField(verbose_name='عدد الحصص الأسبوعية')),
                ('academic_year', models.CharField(default='2025-2026', max_length=9)),
                ('requires_lab', models.BooleanField(default=False, verbose_name='يحتاج معمل؟')),
                ('preferred_periods', models.JSONField(blank=True, default=list, verbose_name='حصص مفضلة')),
                ('is_active', models.BooleanField(default=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='core.classgroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='core.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='operations.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'توزيع مادة على فصل',
                'verbose_name_plural': 'توزيع المواد على الفصول',
                'ordering': ['class_group__grade', 'class_group__section', 'subject__name_ar'],
                'constraints': [models.UniqueConstraint(fields=('class_group', 'subject', 'academic_year'), name='unique_subject_per_class_year')],
            },
        ),
        migrations.CreateModel(
            name='TeacherPreference',
            fields=[
                ('id', models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(default='2025-2026', max_length=9)),
                ('max_daily_periods', models.PositiveIntegerField(default=5, verbose_name='أقصى حصص يومية')),
                ('max_consecutive', models.PositiveIntegerField(default=3, verbose_name='أقصى حصص متتالية')),
                ('free_day', models.IntegerField(blank=True, choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], null=True, verbose_name='يوم التفريغ المفضل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_preferences', to='core.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تفضيلات معلم',
                'verbose_name_plural': 'تفضيلات المعلمين',
                'unique_together': {('teacher', 'school', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlotConfig',
            fields=[
                ('id', models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('period_number', models.PositiveIntegerField(verbose_name='رقم الحصة')),
                ('start_time', models.TimeField(verbose_name='وقت البدء')),
                ('end_time', models.TimeField(verbose_name='وقت الانتهاء')),
                ('day_type', models.CharField(choices=[('regular', 'عادي (أحد-أربعاء)'), ('thursday', 'خميس'), ('ramadan', 'رمضان')], default='regular', max_length=10)),
                ('is_break', models.BooleanField(default=False, verbose_name='استراحة؟')),
                ('break_label', models.CharField(blank=True, max_length=50, verbose_name='نوع الاستراحة')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots_config', to='core.school')),
            ],
            options={
                'verbose_name': 'إعداد حصة زمنية',
                'verbose_name_plural': 'إعدادات الحصص الزمنية',
                'ordering': ['day_type', 'period_number'],
                'unique_together': {('school', 'period_number', 'day_type')},
            },
        ),
    ]
