# Generated by Django 5.2.12 on 2026-03-25 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_postgresql_rls_policies'),
        ('operations', '0006_teacher_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherpreference',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='timeslotconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='المعلم'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'name_ar'], name='idx_subject_school_name'),
        ),
        migrations.AddConstraint(
            model_name='teacherpreference',
            constraint=models.UniqueConstraint(fields=('teacher', 'school', 'academic_year'), name='unique_teacher_schedule_pref'),
        ),
        migrations.AddConstraint(
            model_name='timeslotconfig',
            constraint=models.UniqueConstraint(fields=('school', 'period_number', 'day_type'), name='unique_timeslot_config'),
        ),
    ]
