# Generated by Django 5.2.12 on 2026-03-25 17:13

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_membership_department_alter_role_name_and_more'),
        ('operations', '0007_add_notes_to_scheduleslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensatorySession',
            fields=[
                ('id', models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('compensatory_date', models.DateField(verbose_name='تاريخ التعويض')),
                ('compensatory_period', models.IntegerField(verbose_name='رقم حصة التعويض')),
                ('week_offset', models.PositiveSmallIntegerField(default=0, help_text='0 = نفس الأسبوع, 1 = الأسبوع التالي (الحد الأقصى)', verbose_name='أسبوع التعويض')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('approved', 'معتمدة'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة'), ('expired', 'انتهت المهلة')], db_index=True, default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensatory_sessions', to='operations.teacherabsence', verbose_name='الغياب المرتبط')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensatory_approvals', to=settings.AUTH_USER_MODEL, verbose_name='المعتمِد')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensatory_sessions', to='core.classgroup', verbose_name='الشعبة')),
                ('original_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensatory_originals', to='operations.scheduleslot', verbose_name='الحصة الأصلية (الفائتة)')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensatory_sessions', to='core.school')),
                ('session_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensatory_source', to='operations.session', verbose_name='الحصة المنشأة')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensatory_sessions', to='operations.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensatory_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'حصة تعويضية',
                'verbose_name_plural': 'الحصص التعويضية',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='operations__school__9b46eb_idx'), models.Index(fields=['teacher', 'status'], name='operations__teacher_cb8770_idx'), models.Index(fields=['compensatory_date'], name='operations__compens_551a7f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'expired']), _negated=True), fields=('teacher', 'compensatory_date', 'compensatory_period'), name='unique_compensatory_slot'), models.CheckConstraint(condition=models.Q(('week_offset__lte', 1)), name='compensatory_max_one_week')],
            },
        ),
        migrations.CreateModel(
            name='FreeSlotRegistry',
            fields=[
                ('id', models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], verbose_name='اليوم')),
                ('period_number', models.IntegerField(verbose_name='رقم الحصة')),
                ('academic_year', models.CharField(default='2025-2026', max_length=9)),
                ('is_available', models.BooleanField(default=True, help_text='False = محجوز مؤقتاً (تعويض أو مهمة)', verbose_name='متاح؟')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_slots', to='core.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_slots', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'حصة حرة',
                'verbose_name_plural': 'سجل الحصص الحرة',
                'ordering': ['day_of_week', 'period_number'],
                'indexes': [models.Index(fields=['school', 'day_of_week', 'period_number'], name='operations__school__6f62c3_idx'), models.Index(fields=['teacher', 'is_available'], name='operations__teacher_9e3eee_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'day_of_week', 'period_number', 'academic_year'), name='unique_free_slot_entry')],
            },
        ),
        migrations.CreateModel(
            name='TeacherSwap',
            fields=[
                ('id', models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('swap_date_a', models.DateField(verbose_name='تاريخ حصة أ')),
                ('swap_date_b', models.DateField(verbose_name='تاريخ حصة ب')),
                ('swap_type', models.CharField(choices=[('same_day', 'تبديل نفس اليوم'), ('cross_day', 'تبديل بين يومين')], default='same_day', max_length=10)),
                ('status', models.CharField(choices=[('pending_b', 'بانتظار موافقة المعلم'), ('accepted_b', 'المعلم وافق — بانتظار المنسق'), ('rejected_b', 'المعلم رفض'), ('pending_coordinator', 'بانتظار المنسق'), ('pending_vp', 'بانتظار النائب (تخصصات مختلفة)'), ('approved', 'معتمد'), ('executed', 'تم التنفيذ'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], db_index=True, default='pending_b', max_length=25)),
                ('b_responded_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, verbose_name='سبب التبديل')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_swaps', to='operations.teacherabsence', verbose_name='الغياب المرتبط')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_approvals', to=settings.AUTH_USER_MODEL, verbose_name='المعتمِد')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='مُنشئ الطلب')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_swaps', to='core.school')),
                ('slot_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_as_slot_a', to='operations.scheduleslot', verbose_name='حصة المعلم أ')),
                ('slot_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_as_slot_b', to='operations.scheduleslot', verbose_name='حصة المعلم ب')),
                ('teacher_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_as_requester', to=settings.AUTH_USER_MODEL, verbose_name='المعلم الطالب')),
                ('teacher_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_as_target', to=settings.AUTH_USER_MODEL, verbose_name='المعلم المستهدف')),
            ],
            options={
                'verbose_name': 'طلب تبديل',
                'verbose_name_plural': 'طلبات التبديل',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='operations__school__ece681_idx'), models.Index(fields=['teacher_a', 'status'], name='operations__teacher_3ccb1b_idx'), models.Index(fields=['teacher_b', 'status'], name='operations__teacher_9b6a1d_idx'), models.Index(fields=['swap_date_a'], name='operations__swap_da_b0dbef_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('teacher_a', models.F('teacher_b')), _negated=True), name='swap_different_teachers')],
            },
        ),
    ]
