# Generated by Django 5.2.12 on 2026-03-25 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_compensatorysession_freeslotregistry_teacherswap'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeslotregistry',
            name='reserved_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_slots', to='operations.compensatorysession', verbose_name='محجوز لحصة تعويضية'),
        ),
    ]
