# Generated by Django 5.2.12 on 2026-03-27 06:54

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customuser_professional_license_expiry_and_more'),
        ('operations', '0009_freeslotregistry_reserved_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEvaluation',
            fields=[
                ('id', models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(db_index=True, default='2025-2026', max_length=9, verbose_name='العام الأكاديمي')),
                ('evaluation_date', models.DateField(verbose_name='تاريخ التقييم')),
                ('professional_knowledge', models.PositiveSmallIntegerField(help_text='1 = ضعيف، 5 = ممتاز', verbose_name='المعرفة المهنية')),
                ('teaching_effectiveness', models.PositiveSmallIntegerField(help_text='1 = ضعيف، 5 = ممتاز', verbose_name='فاعلية التدريس')),
                ('student_assessment', models.PositiveSmallIntegerField(help_text='1 = ضعيف، 5 = ممتاز', verbose_name='تقييم الطلاب')),
                ('professional_development', models.PositiveSmallIntegerField(help_text='1 = ضعيف، 5 = ممتاز', verbose_name='التطوير المهني')),
                ('school_community', models.PositiveSmallIntegerField(help_text='1 = ضعيف، 5 = ممتاز', verbose_name='المجتمع المدرسي')),
                ('overall_score', models.DecimalField(decimal_places=2, editable=False, help_text='متوسط المعايير الخمسة — يُحسب تلقائياً عند الحفظ', max_digits=3, verbose_name='الدرجة الكلية')),
                ('recommendation', models.CharField(choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جداً'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('needs_improvement', 'يحتاج تحسين'), ('unsatisfactory', 'غير مُرضٍ')], max_length=20, verbose_name='التوصية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُقدَّم'), ('approved', 'معتمد')], db_index=True, default='draft', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_evaluator', to=settings.AUTH_USER_MODEL, verbose_name='المقيّم')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_evaluations', to='core.school', verbose_name='المدرسة')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_staff', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تقييم أداء موظف',
                'verbose_name_plural': 'تقييمات أداء الموظفين',
                'ordering': ['-evaluation_date'],
                'indexes': [models.Index(fields=['school', 'academic_year'], name='operations__school__2eadae_idx'), models.Index(fields=['staff', 'academic_year'], name='operations__staff_i_a67928_idx'), models.Index(fields=['evaluator', 'academic_year'], name='operations__evaluat_22423b_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff', 'academic_year', 'school'), name='unique_staff_evaluation_per_year'), models.CheckConstraint(condition=models.Q(('professional_knowledge__gte', 1), ('professional_knowledge__lte', 5)), name='eval_knowledge_range_1_5'), models.CheckConstraint(condition=models.Q(('teaching_effectiveness__gte', 1), ('teaching_effectiveness__lte', 5)), name='eval_teaching_range_1_5'), models.CheckConstraint(condition=models.Q(('student_assessment__gte', 1), ('student_assessment__lte', 5)), name='eval_assessment_range_1_5'), models.CheckConstraint(condition=models.Q(('professional_development__gte', 1), ('professional_development__lte', 5)), name='eval_development_range_1_5'), models.CheckConstraint(condition=models.Q(('school_community__gte', 1), ('school_community__lte', 5)), name='eval_community_range_1_5')],
            },
        ),
    ]
