# Generated by Django 5.2.12 on 2026-03-31 02:43

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_teacher_exemption_and_double_period'),
        ('operations', '0011_temporary_permission_audit_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherExemption',
            fields=[
                ('id', models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(default='2025-2026', max_length=9)),
                ('exemption_type', models.CharField(choices=[('full_day', 'يوم كامل'), ('specific_period', 'حصة محددة')], max_length=20, verbose_name='نوع التفريغ')),
                ('day_of_week', models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], verbose_name='اليوم')),
                ('period_number', models.IntegerField(blank=True, null=True, verbose_name='رقم الحصة (إذا حصة محددة)')),
                ('reason', models.CharField(max_length=200, verbose_name='السبب')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تفريغ معلم',
                'verbose_name_plural': 'تفريغات المعلمين',
                'ordering': ['day_of_week', 'period_number'],
            },
        ),
        migrations.RenameIndex(
            model_name='temporarypermission',
            new_name='operations__school__aa2844_idx',
            old_name='idx_tempperm_school_status',
        ),
        migrations.RenameIndex(
            model_name='temporarypermission',
            new_name='operations__teacher_3ab859_idx',
            old_name='idx_tempperm_teacher_status',
        ),
        migrations.RenameIndex(
            model_name='temporarypermission',
            new_name='operations__class_g_b2905d_idx',
            old_name='idx_tempperm_class_status',
        ),
        migrations.RenameIndex(
            model_name='temporarypermission',
            new_name='operations__valid_u_6cf4de_idx',
            old_name='idx_tempperm_expiry_status',
        ),
        migrations.AddField(
            model_name='subject',
            name='requires_double_period',
            field=models.BooleanField(default=False, help_text='يتطلب حصتين متتاليتين بدون استراحة', verbose_name='حصة مزدوجة'),
        ),
        migrations.AlterField(
            model_name='permissionauditlog',
            name='id',
            field=models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temporarypermission',
            name='id',
            field=models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='teacherexemption',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='teacherexemption',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_exemptions', to='core.school'),
        ),
        migrations.AddField(
            model_name='teacherexemption',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exemptions', to=settings.AUTH_USER_MODEL, verbose_name='المعلم/المنسق'),
        ),
    ]
