# Generated by Django 5.2.12 on 2026-05-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0012_add_teacher_exemption_and_double_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendance",
            name="tardiness_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="عدد دقائق التأخير الصباحي (يُسجَّل فقط عند status=late)",
                null=True,
                verbose_name="دقائق التأخير",
            ),
        ),
    ]
