# Generated by Django 5.2.12 on 2026-05-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0013_add_tardiness_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendance",
            name="excuse_file",
            field=models.FileField(
                blank=True,
                upload_to="tardiness_excuses/%Y/%m/",
                verbose_name="ملف إذن ولي الأمر",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="tardiness_recorded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="توقيت تسجيل التأخير"
            ),
        ),
    ]
