# Generated by Django 5.2.12 on 2026-05-07 23:07

import operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0014_add_tardiness_recorded_at_and_excuse_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentattendance",
            name="excuse_file",
            field=models.FileField(
                blank=True,
                upload_to=operations.models._excuse_upload_path,
                verbose_name="ملف إذن ولي الأمر",
            ),
        ),
    ]
