# Generated by Django 5.2.12 on 2026-05-07 23:14

import core.validators
import operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0015_change_excuse_upload_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentattendance",
            name="excuse_file",
            field=models.FileField(
                blank=True,
                upload_to=operations.models._excuse_upload_path,
                validators=[
                    core.validators.FileTypeValidator(
                        allowed_types="excuse", max_size_mb=10
                    )
                ],
                verbose_name="ملف إذن ولي الأمر",
            ),
        ),
    ]
