# Generated by Django 5.2.17 on 2026-08-28 08:05

import core.academic_calendar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0017_rls_parent_derived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freeslotregistry",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="scheduleslot",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="staffevaluation",
            name="academic_year",
            field=models.CharField(
                db_index=True,
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الأكاديمي",
            ),
        ),
        migrations.AlterField(
            model_name="subjectclassassignment",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="teacherexemption",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="teacherpreference",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year, max_length=9
            ),
        ),
    ]
