# Generated by Django 5.2.17 on 2026-08-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0018_alter_freeslotregistry_academic_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="absencealert",
            name="gate",
            field=models.CharField(blank=True, max_length=20, verbose_name="العتبة"),
        ),
    ]
