# Generated by Django 5.2.17 on 2026-08-30 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_classgroup_track"),
        ("operations", "0019_absencealert_gate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scheduleslot",
            name="no_class_period_overlap",
        ),
        migrations.AddField(
            model_name="scheduleslot",
            name="elective_group",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="مجموعة الاختيار"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=(
                    "class_group",
                    "day_of_week",
                    "period_number",
                    "academic_year",
                    "elective_group",
                ),
                name="no_class_period_overlap",
            ),
        ),
    ]
