"""مرجعُ قرار التفريغ.

تفريغُ يومٍ كاملٍ يُخرج المعلّمَ من الجدول يوماً في الأسبوع كلَّه، وكان يُقبل
بسببٍ نصّيٍّ حرٍّ بلا جهةٍ ولا مرجع. وقد ألزمنا خطّةَ النصاب والمؤهّلَ
بمصدرهما، فالتفريغُ أولى.

والحقلُ `blank=True` عمداً: القيدُ في `clean()` كي يبلغ الخطأُ الحقلَ نفسه في
الاستمارة، ولئلّا تسقط صفوفٌ قديمةٌ عند الترحيل.
"""

# Generated by Django 5.2.13 on 2026-09-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_remove_scheduleslot_no_class_period_overlap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherexemption',
            name='source',
            field=models.CharField(choices=[('ministry', 'قرارُ الوزارة'), ('school', 'قرارُ إدارة المدرسة'), ('department', 'قرارُ القسم الأكاديميّ'), ('other', 'أخرى')], default='school', max_length=12, verbose_name='جهة القرار'),
        ),
        migrations.AddField(
            model_name='teacherexemption',
            name='source_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='مرجع القرار'),
        ),
    ]
