# Generated by Django 5.2.13 on 2026-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_exemption_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclassassignment',
            name='parallel_group',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='مجموعة التوازي'),
        ),
    ]
