# Generated by Django 5.2.13 on 2026-09-01 16:00

import django.db.models.deletion
import operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_membership_joined_at'),
        ('operations', '0022_assignment_parallel_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingResource',
            fields=[
                ('id', models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='المورد')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='كم حصّةً معاً')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_resources', to='core.school')),
                ('subjects', models.ManyToManyField(related_name='scheduling_resources', to='operations.subject', verbose_name='المواد التي تستعمله')),
            ],
            options={
                'verbose_name': 'مورد جدولة',
                'verbose_name_plural': 'موارد الجدولة',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_resource_per_school')],
            },
        ),
    ]
