# Generated by Django 5.2.13 on 2026-09-01 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_membership_joined_at'),
        ('operations', '0024_rls_resource_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulegeneration',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='سبب الفشل'),
        ),
        migrations.AddField(
            model_name='schedulegeneration',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انتهى في'),
        ),
        migrations.AlterField(
            model_name='schedulegeneration',
            name='status',
            field=models.CharField(choices=[('queued', 'في الانتظار'), ('running', 'قيد التوليد'), ('draft', 'مسودة'), ('approved', 'معتمد'), ('archived', 'مؤرشف'), ('failed', 'فشل')], default='draft', max_length=10),
        ),
        migrations.AddIndex(
            model_name='schedulegeneration',
            index=models.Index(fields=['school', 'academic_year', 'status'], name='schedgen_school_year_stat'),
        ),
    ]
