# Generated by Django 5.2.13 on 2026-09-01 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_schedulegeneration_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='operations.schedulegeneration', verbose_name='التوليد المصدر'),
        ),
    ]
