# Generated by Django 5.2.13 on 2026-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_scheduleslot_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclassassignment',
            name='double_period',
            field=models.BooleanField(blank=True, help_text='فارغٌ = اتبع إعداد المادّة', null=True, verbose_name='حصّة مزدوجة لهذه الشعبة'),
        ),
    ]
