# Generated by Django 5.2.13 on 2026-09-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_assignment_double_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpreference',
            name='max_gap',
            field=models.PositiveIntegerField(blank=True, help_text='بعدد الحصص الفارغة — اتركه فارغاً لبقاء الفجوة ترجيحاً مرناً', null=True, verbose_name='أقصى فجوة بين حصتين'),
        ),
    ]
