# Generated by Django 5.2.17 on 2026-09-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_timeslotconfig_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherexemption',
            name='source_reference',
        ),
    ]
