# Generated by Django 5.2.17 on 2026-09-04 16:55

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_rls_timeband'),
        ('operations', '0032_remove_teacherexemption_source_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulegeneration',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='مؤشرات الجودة'),
        ),
        migrations.AddField(
            model_name='subject',
            name='pedagogy',
            field=models.CharField(choices=[('heavy', 'ثقيلة (رياضيات، علوم، لغات)'), ('activity', 'نشاط (بدنية، فنون، تكنولوجيا)'), ('regular', 'عادية')], default='regular', max_length=10, verbose_name='طبيعة المادة'),
        ),
        migrations.CreateModel(
            name='ScheduleBaseline',
            fields=[
                ('id', models.UUIDField(default=operations.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('label', models.CharField(max_length=60, verbose_name='الاسم')),
                ('metrics', models.JSONField(default=dict, verbose_name='المؤشرات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_baselines', to='core.school')),
            ],
            options={
                'verbose_name': 'أساس مرجعي للجدول',
                'verbose_name_plural': 'الأسس المرجعية للجدول',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_year', 'label'), name='unique_schedule_baseline')],
            },
        ),
    ]
