"""الإسنادُ يصير قراراً موثَّقاً: من أنشأه ومن عدّله ومن حذفه ولماذا.

كان يُكتب ويُمحى بلا أثر، فمن غيّر معلّمَ شعبةٍ في نوفمبر لم يترك ما يدلّ
عليه. وبعد هذا الترحيل يحمل السجلُّ تاريخَه وفاعلَه، ويحمل `updated_at` الذي
تحرس به `assignment_service` التزامنَ فلا يُطمَس عملُ زميلٍ سبق.

وثلاثةُ حقولٍ للحذف الناعم: من حذف ومتى ولماذا. فإسنادٌ اختفى بلا سببٍ يُقرأ
بعد شهرٍ خللاً في البيانات لا قراراً اتُّخذ.

و`periods_override_reason` يُلزَم حين يخالف عددُ الحصص الخطّةَ الدراسيّة —
والمخالفةُ مشروعةٌ إن كُتب سببُها، ممنوعةٌ إن لم يُكتب.

وتغييرُ `id` تبديلُ اسمِ الدالّة المولّدة (`_uuid` ← `uuid.uuid4`) لا أكثر:
كلتاهما UUID4 تُولَّد في بايثون لا في القاعدة، فلا مساسَ ببيانات.
"""

# Generated by Django 5.2.17 on 2026-09-05 20:00

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0034_rls_schedulebaseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectclassassignment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 9, 5, 20, 0, 30, 306656, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاريخ الإنشاء",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subjectclassassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأه",
            ),
        ),
        migrations.AddField(
            model_name="subjectclassassignment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="subjectclassassignment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_subject_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حذفه",
            ),
        ),
        migrations.AddField(
            model_name="subjectclassassignment",
            name="deletion_reason",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="سبب الحذف"
            ),
        ),
        migrations.AddField(
            model_name="subjectclassassignment",
            name="periods_override_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="يُلزَم حين يخالف عددُ الحصص الخطّةَ الدراسيّة",
                max_length=200,
                verbose_name="سبب مخالفة الخطّة",
            ),
        ),
        migrations.AddField(
            model_name="subjectclassassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AddField(
            model_name="subjectclassassignment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="عدّله",
            ),
        ),
        migrations.AlterField(
            model_name="subjectclassassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
