# Generated by Django 5.2.17 on 2026-09-06 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auditlog_allow_actor_detach'),
        ('operations', '0035_assignment_audited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectclassassignment',
            options={'ordering': ['class_group__grade', 'class_group__section', 'subject__name_ar', 'parallel_group'], 'verbose_name': 'توزيع مادة على فصل', 'verbose_name_plural': 'توزيع المواد على الفصول'},
        ),
        migrations.RemoveConstraint(
            model_name='subjectclassassignment',
            name='unique_subject_per_class_year',
        ),
        migrations.AddConstraint(
            model_name='subjectclassassignment',
            constraint=models.UniqueConstraint(fields=('class_group', 'subject', 'academic_year', 'parallel_group'), name='unique_subject_per_class_year_group'),
        ),
    ]
