# Generated by Django 5.2.17 on 2026-09-06 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auditlog_allow_actor_detach'),
        ('operations', '0036_assignment_parallel_group_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subjectclassassignment',
            name='unique_subject_per_class_year_group',
        ),
        migrations.AddConstraint(
            model_name='subjectclassassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('class_group', 'subject', 'academic_year', 'teacher'), name='unique_subject_per_class_year_teacher'),
        ),
    ]
