# Generated by Django 5.2.17 on 2026-09-10 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.academic_calendar
import operations.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_auditlog_allow_actor_detach"),
        ("operations", "0038_subject_spread_days_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleConstraintOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=operations.models._uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        default=core.academic_calendar.default_academic_year, max_length=9
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="رمز القيد")),
                (
                    "break_at",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="للقيود الصلبة — فارغٌ يعني افتراضَ الكود",
                        max_length=10,
                        verbose_name="متى يُكسَر",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True,
                        help_text="للقيود المرنة — فارغٌ يعني افتراضَ الكود",
                        null=True,
                        verbose_name="الوزن",
                    ),
                ),
                ("reason", models.CharField(max_length=200, verbose_name="سبب المخالفة")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constraint_overrides",
                        to="core.school",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "استثناء قيد جدول",
                "verbose_name_plural": "استثناءات قيود الجدول",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "academic_year", "code"),
                        name="unique_constraint_override",
                    )
                ],
            },
        ),
    ]
