# Generated by Django 5.2.17 on 2026-09-10 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auditlog_allow_actor_detach'),
        ('operations', '0040_rls_constraint_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulebaseline',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='مرجعٌ معتمَد'),
        ),
        migrations.AddConstraint(
            model_name='schedulebaseline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_pinned', True)), fields=('school', 'academic_year'), name='one_pinned_baseline_per_year'),
        ),
    ]
