# Generated by Django 5.2.17 on 2026-09-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0041_pinned_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherexemption',
            name='source',
            field=models.CharField(choices=[('ministry', 'قرارُ الوزارة'), ('school', 'قرارُ إدارة المدرسة'), ('department', 'قرارُ القسم الأكاديميّ'), ('generation', 'لتوليد الجدول'), ('other', 'أخرى')], default='school', max_length=12, verbose_name='جهة القرار'),
        ),
    ]
