# Generated by Django 5.2.17 on 2026-09-11 14:31

from django.db import migrations


class Migration(migrations.Migration):
    """يسقط وسمُ «أيّامٌ مختلفة» — التباعدُ نتيجةٌ تحسبها القسمةُ لا قرارٌ يُكتب.

    HC6 يعطي سقفَ المادّة في اليوم `⌈النصاب ÷ الأيّام⌉`: فمادّةُ خمسِ حصصٍ
    فأقلَّ حصّةٌ في اليوم من نفسها، ومادّةُ ستٍّ يومٌ واحدٌ بحصّتين. فلم يكن
    الوسمُ يضيف شيئاً حيث يسع النصابُ الأيّام، وكان يعطي استحالةً مطلقةً حيث
    لا يسعها — وهو سببُ ستٍّ وعشرين «تعذّر وضع» ورسالةِ استحالةٍ كاذبةِ الدلالة.
    """

    dependencies = [
        ("operations", "0042_exemption_source_generation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="spread_days_scope",
        ),
    ]
