# Generated by Django 5.2.17 on 2026-09-11 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """أثرُ التبديل على حصّة اليوم، وتوقيعُ منسّقِ كلِّ مادّة.

    التبديلُ كان يقع على `ScheduleSlot` — قالبِ الأسبوع كلِّه — فلا يعود
    الجدولُ كما كان أبداً. فصار يقع على `Session` ليومه، و`original_teacher`
    يحفظ صاحبَها الأوّلَ ويُلوّن خانتَها.

    والاعتمادُ كان توقيعاً واحداً يملكه أيُّ منسّق. وصار توقيعَ منسّقِ كلِّ
    مادّةٍ عن مادّته، والنائبُ بديلٌ عن الغائب منهما لا متجاوزٌ عليهما.
    """

    dependencies = [
        ("operations", "0043_drop_spread_days_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="original_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions_swapped_away",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المعلّم الأصليّ",
            ),
        ),
        migrations.AddField(
            model_name="teacherswap",
            name="approved_a_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacherswap",
            name="approved_a_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="swap_approvals_side_a",
                to=settings.AUTH_USER_MODEL,
                verbose_name="موافقةُ منسّق المادّة الأولى",
            ),
        ),
        migrations.AddField(
            model_name="teacherswap",
            name="approved_a_by_substitute",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacherswap",
            name="approved_b_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacherswap",
            name="approved_b_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="swap_approvals_side_b",
                to=settings.AUTH_USER_MODEL,
                verbose_name="موافقةُ منسّق المادّة الثانية",
            ),
        ),
        migrations.AddField(
            model_name="teacherswap",
            name="approved_b_by_substitute",
            field=models.BooleanField(default=False),
        ),
    ]
