# Generated by Django 5.2.17 on 2026-09-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0045_supervisor_attendance_pilot"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendance",
            name="late_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="دقائقُ التأخّر عن الحصّة"
            ),
        ),
    ]
