"""تثبيتُ رصد الحصّة — ومعه عزلُ المدرسة.

الجدولُ يُنشأ بعد `core/0037`، فلا يرث سياسةَ العزل: تُكتب هنا صراحةً كما في
`0045`. و`operations_periodconfirmation` يحمل `school_id` بنفسه.
"""

# Generated by Django 5.2.17 on 2026-09-13 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import operations.models

TABLE = "operations_periodconfirmation"
CURRENT = "public.app_rls_school()"
PREDICATE = f"{TABLE}.school_id = {CURRENT}"

ENABLE = f"""
ALTER TABLE public.{TABLE} ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS school_isolation ON public.{TABLE};

CREATE POLICY school_isolation ON public.{TABLE}
    USING ({PREDICATE})
    WITH CHECK ({PREDICATE});
"""

DISABLE = f"""
DROP POLICY IF EXISTS school_isolation ON public.{TABLE};
ALTER TABLE public.{TABLE} DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_role_support_companion"),
        ("operations", "0046_period_late_minutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodConfirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=operations.models._uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField(verbose_name="بدءُ الخانة")),
                ("end_time", models.TimeField(verbose_name="نهايةُ الخانة")),
                ("first_confirmed_at", models.DateTimeField(verbose_name="أوّلُ تثبيت")),
                ("confirmed_at", models.DateTimeField(auto_now=True, verbose_name="آخرُ تثبيت")),
                (
                    "confirmed_late",
                    models.BooleanField(default=False, verbose_name="ثُبّتت بعد مهلتها"),
                ),
                ("present_count", models.PositiveSmallIntegerField(default=0)),
                ("absent_count", models.PositiveSmallIntegerField(default=0)),
                ("late_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_confirmations",
                        to="core.classgroup",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="period_confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_confirmations",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "تثبيتُ رصدِ حصّة",
                "verbose_name_plural": "تثبيتاتُ رصد الحصص",
                "ordering": ["-date", "class_group", "start_time"],
                "indexes": [
                    models.Index(fields=["school", "date"], name="operations__school__34e294_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("class_group", "date", "start_time"),
                        name="unique_period_confirmation",
                    )
                ],
            },
        ),
        migrations.RunSQL(sql=ENABLE, reverse_sql=DISABLE),
    ]
