# Generated by Django 5.2.17 on 2026-09-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0053_excuse_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendance",
            name="exit",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounted_attendances",
                to="operations.classexit",
                verbose_name="الخروجُ المحسوب",
            ),
        ),
    ]
