# Generated by Django 5.2.17 on 2026-09-24 05:40

import core.academic_calendar
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_arabic_field_labels"),
        ("operations", "0056_delete_staffevaluation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="absencealert",
            name="absence_count",
            field=models.IntegerField(verbose_name="عدد أيّام الغياب"),
        ),
        migrations.AlterField(
            model_name="absencealert",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
            ),
        ),
        migrations.AlterField(
            model_name="absencealert",
            name="period_end",
            field=models.DateField(verbose_name="نهاية الفترة"),
        ),
        migrations.AlterField(
            model_name="absencealert",
            name="period_start",
            field=models.DateField(verbose_name="بداية الفترة"),
        ),
        migrations.AlterField(
            model_name="absencealert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="عالجه",
            ),
        ),
        migrations.AlterField(
            model_name="absencealert",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="absencealert",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("notified", "تم الإبلاغ"),
                    ("resolved", "تم الحل"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="absencealert",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="absence_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="absenceexcuse",
            name="after_deadline",
            field=models.BooleanField(default=False, verbose_name="بعد انقضاء المهلة"),
        ),
        migrations.AlterField(
            model_name="absenceexcuse",
            name="granted_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ التسجيل"),
        ),
        migrations.AlterField(
            model_name="absenceexcuse",
            name="granted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="absence_excuses_granted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="سجّل العذر",
            ),
        ),
        migrations.AlterField(
            model_name="absenceexcuse",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ قرار النائب"
            ),
        ),
        migrations.AlterField(
            model_name="absenceexcuse",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="absence_excuses",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="absenceexcuse",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="absence_excuses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="classexit",
            name="allowed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_exits_allowed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أذِن به",
            ),
        ),
        migrations.AlterField(
            model_name="classexit",
            name="destination",
            field=models.CharField(
                choices=[
                    ("clinic", "العيادة"),
                    ("admin", "الإدارة / المشرف"),
                    ("restroom", "دورة المياه"),
                    ("other", "أخرى"),
                ],
                default="restroom",
                max_length=10,
                verbose_name="الوجهة",
            ),
        ),
        migrations.AlterField(
            model_name="classexit",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_exits",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="classexit",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_exits",
                to="operations.session",
                verbose_name="الحصّة",
            ),
        ),
        migrations.AlterField(
            model_name="classexit",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_exits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="compensatorysession",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الاعتماد"
            ),
        ),
        migrations.AlterField(
            model_name="compensatorysession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="compensatorysession",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compensatory_sessions",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="compensatorysession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "بانتظار الموافقة"),
                    ("approved", "معتمدة"),
                    ("completed", "مكتملة"),
                    ("cancelled", "ملغاة"),
                    ("expired", "انتهت المهلة"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="compensatorysession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="freeslotregistry",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="freeslotregistry",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="free_slots",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="guardiancontact",
            name="channel",
            field=models.CharField(
                choices=[("phone", "هاتف"), ("sms", "رسالة نصّيّة")],
                default="phone",
                max_length=6,
                verbose_name="وسيلة التواصل",
            ),
        ),
        migrations.AlterField(
            model_name="guardiancontact",
            name="contacted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guardian_contacts_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="القائم بالتواصل",
            ),
        ),
        migrations.AlterField(
            model_name="guardiancontact",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guardian_contacts",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="guardiancontact",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guardian_contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="periodconfirmation",
            name="absent_count",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="الغائبون"),
        ),
        migrations.AlterField(
            model_name="periodconfirmation",
            name="class_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="period_confirmations",
                to="core.classgroup",
                verbose_name="الشعبة",
            ),
        ),
        migrations.AlterField(
            model_name="periodconfirmation",
            name="confirmed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="period_confirmations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أكّده",
            ),
        ),
        migrations.AlterField(
            model_name="periodconfirmation",
            name="date",
            field=models.DateField(db_index=True, verbose_name="التاريخ"),
        ),
        migrations.AlterField(
            model_name="periodconfirmation",
            name="late_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="المتأخّرون"
            ),
        ),
        migrations.AlterField(
            model_name="periodconfirmation",
            name="present_count",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="الحاضرون"),
        ),
        migrations.AlterField(
            model_name="periodconfirmation",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="period_confirmations",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="schedulebaseline",
            name="academic_year",
            field=models.CharField(max_length=9, verbose_name="العام الدراسي"),
        ),
        migrations.AlterField(
            model_name="schedulebaseline",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="schedulebaseline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأه",
            ),
        ),
        migrations.AlterField(
            model_name="schedulebaseline",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_baselines",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleconstraintoverride",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleconstraintoverride",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constraint_overrides",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleconstraintoverride",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="scheduleconstraintoverride",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="عدّله",
            ),
        ),
        migrations.AlterField(
            model_name="schedulegeneration",
            name="academic_year",
            field=models.CharField(max_length=9, verbose_name="العام الدراسي"),
        ),
        migrations.AlterField(
            model_name="schedulegeneration",
            name="generated_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="وقت التوليد"),
        ),
        migrations.AlterField(
            model_name="schedulegeneration",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ولّده",
            ),
        ),
        migrations.AlterField(
            model_name="schedulegeneration",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_generations",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="schedulegeneration",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "في الانتظار"),
                    ("running", "قيد التوليد"),
                    ("draft", "مسودة"),
                    ("approved", "معتمد"),
                    ("archived", "مؤرشف"),
                    ("failed", "فشل"),
                ],
                default="draft",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="schedulegeneration",
            name="total_slots_created",
            field=models.IntegerField(default=0, verbose_name="الحصص المولَّدة"),
        ),
        migrations.AlterField(
            model_name="scheduleslot",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleslot",
            name="class_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_slots",
                to="core.classgroup",
                verbose_name="الشعبة",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleslot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="scheduleslot",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="scheduleslot",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_slots",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleslot",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="operations.subject",
                verbose_name="المادّة",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleslot",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedule_slots",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المعلّم",
            ),
        ),
        migrations.AlterField(
            model_name="schedulingresource",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="schedulingresource",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduling_resources",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="sectiondayconfirmation",
            name="absent_count",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="الغائبون"),
        ),
        migrations.AlterField(
            model_name="sectiondayconfirmation",
            name="class_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day_confirmations",
                to="core.classgroup",
                verbose_name="الشعبة",
            ),
        ),
        migrations.AlterField(
            model_name="sectiondayconfirmation",
            name="confirmed_at",
            field=models.DateTimeField(auto_now=True, verbose_name="وقت التأكيد"),
        ),
        migrations.AlterField(
            model_name="sectiondayconfirmation",
            name="confirmed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="day_confirmations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أكّده",
            ),
        ),
        migrations.AlterField(
            model_name="sectiondayconfirmation",
            name="date",
            field=models.DateField(db_index=True, verbose_name="التاريخ"),
        ),
        migrations.AlterField(
            model_name="sectiondayconfirmation",
            name="late_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="المتأخّرون"
            ),
        ),
        migrations.AlterField(
            model_name="sectiondayconfirmation",
            name="note",
            field=models.TextField(blank=True, verbose_name="ملاحظة"),
        ),
        migrations.AlterField(
            model_name="sectiondayconfirmation",
            name="periods_written",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="الحصص المرصودة"
            ),
        ),
        migrations.AlterField(
            model_name="sectiondayconfirmation",
            name="present_count",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="الحاضرون"),
        ),
        migrations.AlterField(
            model_name="sectiondayconfirmation",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day_confirmations",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="class_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="core.classgroup",
                verbose_name="الشعبة",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="session",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="session",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "مجدولة"),
                    ("in_progress", "جارية"),
                    ("completed", "مكتملة"),
                    ("cancelled", "ملغاة"),
                ],
                db_index=True,
                default="scheduled",
                max_length=15,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="operations.subject",
                verbose_name="المادّة",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="excuse_notes",
            field=models.TextField(blank=True, verbose_name="بيان العذر"),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="excuse_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("medical", "مرضٌ بتقريرٍ طبّيّ"),
                    ("bereavement", "وفاةٌ في القرابة الأولى"),
                    ("family", "ظرفٌ عائليٌّ طارئٌ بكتابٍ رسميّ"),
                    ("state_representation", "تمثيلُ الدولة في لقاءٍ خارجيّ"),
                    (
                        "official",
                        "موعدُ محكمةٍ أو هيئةٍ حكوميّة، أو مقابلةٌ للثاني عشر",
                    ),
                    ("other", "أخرى (قبل القائمة المغلقة)"),
                ],
                max_length=20,
                verbose_name="نوع العذر",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="marked_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="وقت الرصد"),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="marked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_attendances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رصده",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="operations.session",
                verbose_name="الحصّة",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "حاضر"),
                    ("absent", "غائب"),
                    ("late", "متأخر"),
                    ("excused", "معذور"),
                ],
                db_index=True,
                default="present",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="رمز المادّة"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="subjectclassassignment",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="subjectclassassignment",
            name="class_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="core.classgroup",
                verbose_name="الشعبة",
            ),
        ),
        migrations.AlterField(
            model_name="subjectclassassignment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="subjectclassassignment",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="subjectclassassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_assignments",
                to="operations.subject",
                verbose_name="المادّة",
            ),
        ),
        migrations.AlterField(
            model_name="substituteassignment",
            name="absence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="operations.teacherabsence",
                verbose_name="غياب المعلّم",
            ),
        ),
        migrations.AlterField(
            model_name="substituteassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="كلّفه",
            ),
        ),
        migrations.AlterField(
            model_name="substituteassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="substituteassignment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="substituteassignment",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitute_assignments",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="substituteassignment",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitute_assignments",
                to="operations.scheduleslot",
                verbose_name="حصّة الجدول",
            ),
        ),
        migrations.AlterField(
            model_name="substituteassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "مُعيَّن"),
                    ("confirmed", "قبِل"),
                    ("declined", "رفض"),
                ],
                default="assigned",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="substituteassignment",
            name="substitute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitute_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="البديل",
            ),
        ),
        migrations.AlterField(
            model_name="teacherabsence",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="teacherabsence",
            name="reason",
            field=models.CharField(
                choices=[
                    ("sick", "إجازة مرضية"),
                    ("official", "مهمة رسمية"),
                    ("emergency", "ظرف طارئ"),
                    ("training", "تدريب"),
                    ("other", "أخرى"),
                ],
                default="other",
                max_length=20,
                verbose_name="سبب الغياب",
            ),
        ),
        migrations.AlterField(
            model_name="teacherabsence",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_absences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="سجّله",
            ),
        ),
        migrations.AlterField(
            model_name="teacherabsence",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_absences",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="teacherabsence",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "بانتظار البديل"),
                    ("covered", "مغطّى"),
                    ("uncovered", "غير مغطّى"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="teacherabsence",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="absences_as_teacher",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المعلّم",
            ),
        ),
        migrations.AlterField(
            model_name="teacherexemption",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="teacherexemption",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="teacherexemption",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="teacherexemption",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_exemptions",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="teacherpreference",
            name="academic_year",
            field=models.CharField(
                default=core.academic_calendar.default_academic_year,
                max_length=9,
                verbose_name="العام الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="teacherpreference",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_preferences",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="teacherpreference",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_preferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المعلّم",
            ),
        ),
        migrations.AlterField(
            model_name="teacherswap",
            name="approved_a_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت موافقة منسّق المادّة الأولى"
            ),
        ),
        migrations.AlterField(
            model_name="teacherswap",
            name="approved_a_by_substitute",
            field=models.BooleanField(
                default=False, verbose_name="وقّع عن منسّق المادّة الأولى بديلٌ"
            ),
        ),
        migrations.AlterField(
            model_name="teacherswap",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ إتمام الاعتماد"
            ),
        ),
        migrations.AlterField(
            model_name="teacherswap",
            name="approved_b_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت موافقة منسّق المادّة الثانية"
            ),
        ),
        migrations.AlterField(
            model_name="teacherswap",
            name="approved_b_by_substitute",
            field=models.BooleanField(
                default=False, verbose_name="وقّع عن منسّق المادّة الثانية بديلٌ"
            ),
        ),
        migrations.AlterField(
            model_name="teacherswap",
            name="b_responded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت ردّ المعلّم الثاني"
            ),
        ),
        migrations.AlterField(
            model_name="teacherswap",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="teacherswap",
            name="executed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت التنفيذ"
            ),
        ),
        migrations.AlterField(
            model_name="teacherswap",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_swaps",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="teacherswap",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_b", "بانتظار موافقة المعلم"),
                    ("accepted_b", "المعلم وافق — بانتظار المنسق"),
                    ("rejected_b", "المعلم رفض"),
                    ("pending_coordinator", "بانتظار المنسق"),
                    ("pending_vp", "بانتظار النائب (تخصصات مختلفة)"),
                    ("approved", "معتمد"),
                    ("executed", "تم التنفيذ"),
                    ("rejected", "مرفوض"),
                    ("cancelled", "ملغى"),
                ],
                db_index=True,
                default="pending_b",
                max_length=25,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="teacherswap",
            name="swap_type",
            field=models.CharField(
                choices=[
                    ("same_day", "تبديل نفس اليوم"),
                    ("cross_day", "تبديل بين يومين"),
                ],
                default="same_day",
                max_length=10,
                verbose_name="نوع التبديل",
            ),
        ),
        migrations.AlterField(
            model_name="teacherswap",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="temporarypermission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="timeslotconfig",
            name="day_type",
            field=models.CharField(
                choices=[
                    ("regular", "عادي (أحد-أربعاء)"),
                    ("thursday", "خميس"),
                    ("ramadan", "رمضان"),
                ],
                default="regular",
                max_length=10,
                verbose_name="نوع اليوم",
            ),
        ),
        migrations.AlterField(
            model_name="timeslotconfig",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_slots_config",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
    ]
