# Generated by Django 5.2.17 on 2026-09-24 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0057_arabic_field_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="compensatorysession",
            name="colleague",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compensatory_hosted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الزميل صاحب الحصّة",
            ),
        ),
        migrations.AddField(
            model_name="compensatorysession",
            name="colleague_responded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="وقت ردّ الزميل"),
        ),
        migrations.AlterField(
            model_name="compensatorysession",
            name="status",
            field=models.CharField(
                choices=[
                    ("colleague", "بانتظار موافقة الزميل"),
                    ("pending", "بانتظار الاعتماد"),
                    ("approved", "معتمدة"),
                    ("completed", "مكتملة"),
                    ("cancelled", "ملغاة"),
                    ("expired", "انتهت المهلة"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
    ]
