# Generated by Django 5.2.17 on 2026-09-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0059_session_period_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleslot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AddField(
            model_name="teacherpreference",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AddField(
            model_name="teacherpreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="تاريخ التعديل"),
        ),
    ]
