# Generated by Django 5.2.17 on 2026-10-02 09:59

import django.db.models.deletion
import django.utils.timezone
import operations.models.common
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_customuser_employer_name_customuser_employer_sector_and_more"),
        ("operations", "0061_hard_violations_from_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=operations.models.common._uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("absent", "غائب"),
                            ("late", "متأخّر"),
                        ],
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "tardiness_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="دقائق التأخّر"
                    ),
                ),
                (
                    "entered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="وقتُ الإدخال"
                    ),
                ),
                (
                    "correction_reason",
                    models.TextField(blank=True, verbose_name="سببُ التصحيح"),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_entries_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أدخله",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_entries",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_entries",
                        to="operations.session",
                        verbose_name="الحصّة",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="operations.attendanceentry",
                        verbose_name="يصحّح",
                    ),
                ),
            ],
            options={
                "verbose_name": "إدخالُ رصدٍ مبدئيّ",
                "verbose_name_plural": "إدخالاتُ الرصد المبدئيّ",
                "ordering": ["entered_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=operations.models.common._uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "اعتماد"), ("rejected", "رفض")],
                        max_length=10,
                        verbose_name="القرار",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="وقتُ القرار"
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("wing_holder", "حاملُ جناح الشعبة"),
                            ("leadership_no_holder", "القيادةُ — لا حاملَ للجناح"),
                            (
                                "leadership_holder_is_teacher",
                                "القيادةُ — حاملُ الجناح هو معلّمُ الحصّة",
                            ),
                            (
                                "leadership_holder_inactive",
                                "القيادةُ — حاملُ الجناح بلا عضويّةٍ نشطة",
                            ),
                            ("supervisor_record", "كُتب رصدُ مشرفٍ فوق الإدخال"),
                            (
                                "special_ed_self",
                                "التربيةُ الخاصّة — اعتمادٌ ذاتيٌّ بالتصميم",
                            ),
                        ],
                        max_length=40,
                        verbose_name="أساسُ الصلاحيّة",
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(blank=True, default=dict, verbose_name="الدليل"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="السبب")),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_decisions_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="قرّره",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_decisions",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision",
                        to="operations.attendanceentry",
                        verbose_name="الإدخال",
                    ),
                ),
            ],
            options={
                "verbose_name": "قرارُ رصد",
                "verbose_name_plural": "قراراتُ الرصد",
                "ordering": ["decided_at"],
            },
        ),
        migrations.AddIndex(
            model_name="attendanceentry",
            index=models.Index(
                fields=["session", "student"], name="idx_attentry_session_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("supersedes__isnull", True)),
                fields=("session", "student"),
                name="unique_root_attendance_entry",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("supersedes__isnull", True),
                    models.Q(("correction_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="attendance_entry_correction_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancedecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decision", "approved"),
                    models.Q(("reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="attendance_decision_rejection_has_reason",
            ),
        ),
    ]
