# Generated by Django 5.2.17 on 2026-10-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0065_teacherpreference_max_last_periods"),
    ]

    operations = [
        migrations.AddField(
            model_name="classexit",
            name="continued_from",
            field=models.ForeignKey(
                blank=True,
                help_text="الخروجُ الذي لم يعد صاحبُه بنهاية حصّته يُرحَّل إلى الحصّة التالية بسطرٍ جديد يشير إلى أصله؛ فالسطرُ بلا أصلٍ خروجٌ جديدٌ يُعدّ مرّةً، والامتدادُ يزيد المدّةَ ولا يزيد العدد.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="continuations",
                to="operations.classexit",
                verbose_name="امتدادٌ لخروجٍ سابق",
            ),
        ),
    ]
