# Generated by Django 5.2.17 on 2026-10-04 16:03

import django.db.models.deletion
import operations.models.common
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_auditlog_allow_network_redaction"),
        ("operations", "0065_teacherpreference_max_last_periods"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classexit",
            name="continued_from",
            field=models.ForeignKey(
                blank=True,
                help_text="الخروجُ الذي لم يعد صاحبُه بنهاية حصّته يُرحَّل إلى الحصّة التالية بسطرٍ جديد يشير إلى أصله؛ فالسطرُ بلا أصلٍ خروجٌ جديدٌ يُعدّ مرّةً، والامتدادُ يزيد المدّةَ ولا يزيد العدد.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="continuations",
                to="operations.classexit",
                verbose_name="امتدادٌ لخروجٍ سابق",
            ),
        ),
        migrations.CreateModel(
            name="DailyExitTally",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=operations.models.common._uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "exit_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عددُ مرّات الخروج"
                    ),
                ),
                (
                    "total_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مجموعُ مدّة الخروج (ثوانٍ)"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرُ تحديث"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_exit_tallies",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_exit_tallies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملخّصُ خروجٍ يوميّ",
                "verbose_name_plural": "ملخّصاتُ الخروج اليوميّة",
                "indexes": [
                    models.Index(
                        fields=["school", "date"], name="operations__school__c725fe_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "date"), name="uniq_exit_tally_student_day"
                    )
                ],
            },
        ),
    ]
