# Generated by Django 5.2.17 on 2026-10-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0066_class_exit_continuation_and_daily_tally"),
    ]

    operations = [
        migrations.AddField(
            model_name="classexit",
            name="system_closed",
            field=models.BooleanField(
                default=False,
                help_text="أغلقه جرسُ آخر حصّةٍ للطالب أو مهمّةُ نهاية اليوم والطالبُ لم يعد: علامةٌ صريحةٌ يقرؤها مؤشّرُ «لم يعد» للمشرف، فلا يكون الإغلاقُ صامتاً ولا يُخفي أنّه لم يعد.",
                verbose_name="أُغلق بالنظام بلا عودة",
            ),
        ),
    ]
