# Generated by Django 5.2.17 on 2026-10-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0067_class_exit_system_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyexittally",
            name="by_destination",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"clinic": {"count": 1, "seconds": 300}, ...} — عددُ المرّات ومجموعُ الأجزاء المغلقة لكلّ وجهةٍ (العيادة، الإدارة/المشرف، دورة المياه، أخرى).',
                verbose_name="التفصيل بالوجهة",
            ),
        ),
    ]
