# Generated by Django 5.2.17 on 2026-10-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0071_session_overlap_real_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancedecision",
            name="basis",
            field=models.CharField(
                choices=[
                    ("wing_holder", "حاملُ جناح الشعبة"),
                    ("leadership_no_holder", "القيادةُ — لا حاملَ للجناح"),
                    (
                        "leadership_holder_is_teacher",
                        "القيادةُ — حاملُ الجناح هو معلّمُ الحصّة",
                    ),
                    (
                        "leadership_holder_inactive",
                        "القيادةُ — حاملُ الجناح بلا عضويّةٍ نشطة",
                    ),
                    ("school_wide", "حاصرُ الغياب العامّ — اعتمادٌ ثانٍ بجانب الحامل"),
                    ("supervisor_record", "كُتب رصدُ مشرفٍ فوق الإدخال"),
                    ("special_ed_self", "التربيةُ الخاصّة — اعتمادٌ ذاتيٌّ بالتصميم"),
                ],
                max_length=40,
                verbose_name="أساسُ الصلاحيّة",
            ),
        ),
    ]
