# Generated by Django 5.2.17 on 2026-10-10 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0076_teacherpreference_max_consecutive_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherpreference",
            name="max_first_periods",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="قرارٌ إداريّ في حقّ هذا المعلّم — فارغٌ يعني السقفَ العامّ (اثنتان)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="أقصى حصص أولى أسبوعيّاً",
            ),
        ),
    ]
