# Generated by Django 5.2.17 on 2026-10-10 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0077_teacherpreference_max_first_periods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherpreference",
            name="max_first_periods",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="قرارٌ إداريّ في حقّ هذا المعلّم: أقصى عدد الحصص الأولى في الأسبوع، من 2 إلى 5 — فارغٌ يعني السقفَ العامّ (اثنتان)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="أقصى حصص أولى أسبوعيّاً",
            ),
        ),
        migrations.AlterField(
            model_name="teacherpreference",
            name="max_last_periods",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="قرارٌ إداريّ في حقّ هذا المعلّم: أقصى عدد حصص السابعة في الأسبوع، من 2 إلى 5 — فارغٌ يعني السقفَ العامّ (اثنتان)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="أقصى سابعات أسبوعيّاً",
            ),
        ),
    ]
