# Generated by Django 5.2.12 on 2026-04-11 04:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_rename_breach_school_status_idx_core_breach_school__aa7243_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(help_text='صيغة: SOS-YYYYMMDD-XXXX', max_length=20, unique=True, verbose_name='رقم التذكرة')),
                ('user_id_hash', models.CharField(help_text='تُستخدم في إيميل المطوّر بدلاً من معرّف المستخدم الفعلي', max_length=64, verbose_name='بصمة المستخدم (SHA-256)')),
                ('message_type', models.CharField(choices=[('bug', 'عطل / مشكلة'), ('feature', 'اقتراح ميزة'), ('question', 'سؤال'), ('complaint', 'شكوى'), ('praise', 'شكر / ثناء'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع الرسالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('subject', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(200)], verbose_name='الموضوع')),
                ('body', models.TextField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(4000)], verbose_name='نصّ الرسالة')),
                ('context_json', models.JSONField(blank=True, default=dict, help_text='url_path, view_name, viewport, role — لا tokens ولا IP ولا UA', verbose_name='السياق التقني')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('seen', 'تمّت القراءة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تمّ الحل'), ('closed', 'مغلقة')], default='new', max_length=15, verbose_name='الحالة')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت إعطاء الموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئت في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('deletion_scheduled_at', models.DateTimeField(help_text='يُحسب تلقائياً = created_at + 90 يوم', verbose_name='موعد الحذف المجدول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_feedback_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رسالة إلى المطوّر',
                'verbose_name_plural': 'رسائل المطوّر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view_inbox', 'عرض صندوق الوارد'), ('view_message', 'عرض رسالة'), ('update_status', 'تحديث الحالة'), ('delete_message', 'حذف رسالة')], max_length=30, verbose_name='الإجراء')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإجراء')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_feedback_audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='الفاعل')),
                ('target_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='developer_feedback.developermessage', verbose_name='الرسالة المستهدفة')),
            ],
            options={
                'verbose_name': 'سجل تدقيق الوصول',
                'verbose_name_plural': 'سجلات تدقيق الوصول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperMessageNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('smtp', 'بريد إلكتروني'), ('inapp', 'داخل التطبيق')], max_length=15, verbose_name='القناة')),
                ('recipient', models.CharField(max_length=200, verbose_name='المستلِم')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sent', 'أُرسلت'), ('failed', 'فشل الإرسال'), ('retry', 'إعادة محاولة')], default='pending', max_length=15, verbose_name='حالة الإشعار')),
                ('error_detail', models.TextField(blank=True, verbose_name='تفاصيل الخطأ')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='developer_feedback.developermessage', verbose_name='الرسالة')),
            ],
            options={
                'verbose_name': 'إشعار رسالة مطوّر',
                'verbose_name_plural': 'إشعارات رسائل المطوّر',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalOnboardingConsent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('consent_version', models.CharField(default='1.0', max_length=10, verbose_name='إصدار الموافقة')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت القبول')),
                ('quiz_passed', models.BooleanField(default=False, verbose_name='اجتاز الاختبار؟')),
                ('quiz_score', models.PositiveSmallIntegerField(default=0, verbose_name='درجة الاختبار')),
                ('admin_authorization_doc', models.CharField(blank=True, max_length=255, verbose_name='مرجع التفويض الإداري الكتابي')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإلغاء')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dev_feedback_consent', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'Legal Onboarding Consent',
                'verbose_name_plural': 'Legal Onboarding Consents',
            },
        ),
        migrations.CreateModel(
            name='MessageStatusLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('new', 'جديدة'), ('seen', 'تمّت القراءة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تمّ الحل'), ('closed', 'مغلقة')], max_length=15, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(choices=[('new', 'جديدة'), ('seen', 'تمّت القراءة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تمّ الحل'), ('closed', 'مغلقة')], max_length=15, verbose_name='الحالة الجديدة')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التغيير')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_feedback_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='غيّرها')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='developer_feedback.developermessage', verbose_name='الرسالة')),
            ],
            options={
                'verbose_name': 'سجل تغيير حالة رسالة',
                'verbose_name_plural': 'سجلات تغيير الحالات',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='developermessage',
            index=models.Index(fields=['status', 'created_at'], name='devfb_msg_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='developermessage',
            index=models.Index(fields=['user', 'created_at'], name='devfb_msg_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='developermessage',
            index=models.Index(fields=['priority', 'status'], name='devfb_msg_priority_status_idx'),
        ),
    ]
