# Generated by Django 5.2.12 on 2026-04-11 06:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developermessagenotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار رسالة مطوّر', 'verbose_name_plural': 'إشعارات رسائل المطوّر'},
        ),
        migrations.AlterModelOptions(
            name='legalonboardingconsent',
            options={'verbose_name': 'موافقة الإعداد القانوني', 'verbose_name_plural': 'موافقات الإعداد القانوني'},
        ),
        migrations.AddField(
            model_name='developermessagenotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developermessage',
            name='deletion_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='يُحسب تلقائياً = created_at + 90 يوم (بعد أول حفظ)', null=True, verbose_name='موعد الحذف المجدول'),
        ),
    ]
