# Generated by Django 5.2.12 on 2026-04-21 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "developer_feedback",
            "0002_alter_developermessagenotification_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("view_inbox", "عرض صندوق الوارد"),
                    ("view_message", "عرض رسالة"),
                    ("update_status", "تحديث الحالة"),
                    ("edit_message", "تعديل رسالة"),
                    ("delete_message", "حذف رسالة"),
                ],
                max_length=30,
                verbose_name="الإجراء",
            ),
        ),
        migrations.CreateModel(
            name="MessageEditHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "old_subject",
                    models.CharField(max_length=200, verbose_name="الموضوع السابق"),
                ),
                ("old_body", models.TextField(verbose_name="النص السابق")),
                (
                    "old_message_type",
                    models.CharField(
                        choices=[
                            ("bug", "عطل / مشكلة"),
                            ("feature", "اقتراح ميزة"),
                            ("question", "سؤال"),
                            ("complaint", "شكوى"),
                            ("praise", "شكر / ثناء"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع الرسالة السابق",
                    ),
                ),
                (
                    "old_priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("normal", "عادية"),
                            ("high", "عالية"),
                        ],
                        max_length=10,
                        verbose_name="الأولوية السابقة",
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التعديل"),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dev_feedback_edits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدّلها",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_history",
                        to="developer_feedback.developermessage",
                        verbose_name="الرسالة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تعديل رسالة",
                "verbose_name_plural": "سجلات تعديل الرسائل",
                "ordering": ["-edited_at"],
                "indexes": [
                    models.Index(
                        fields=["message", "edited_at"], name="devfb_edit_msg_time_idx"
                    )
                ],
            },
        ),
    ]
