# Generated by Django 5.2.17 on 2026-09-30 19:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developer_feedback", "0003_alter_auditlog_action_messageedithistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "subject",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(200),
                        ],
                        verbose_name="الموضوع",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.MaxLengthValidator(4000),
                        ],
                        verbose_name="نصّ الرسالة",
                    ),
                ),
                (
                    "audience_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الفئة المستهدفة"
                    ),
                ),
                (
                    "recipient_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المستلِمين"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُرسلت في"),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dev_feedback_broadcasts_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أرسلها",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالةٌ من المطوّر",
                "verbose_name_plural": "رسائل المطوّر الصادرة",
                "ordering": ["-created_at"],
            },
        ),
    ]
