# Generated by Django 5.2.12 on 2026-03-21 11:19

import transport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='id',
            field=models.UUIDField(
                default=transport.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='schoolbus',
            name='id',
            field=models.UUIDField(
                default=transport.models._uuid, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
