# Generated by Django 5.2.17 on 2026-09-24 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_arabic_field_labels"),
        ("transport", "0004_rls_parent_derived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busroute",
            name="bus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="transport.schoolbus",
                verbose_name="الحافلة",
            ),
        ),
        migrations.AlterField(
            model_name="schoolbus",
            name="capacity",
            field=models.PositiveIntegerField(default=30, verbose_name="السعة"),
        ),
        migrations.AlterField(
            model_name="schoolbus",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buses",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
    ]
