# Generated by Django 5.0.6 on 2026-03-19 02:40

import django.db.models.deletion
import notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_school__75db48_idx',
            old_name='notif_school_type_idx',
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='body',
            field=models.TextField(verbose_name='نص الرسالة'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='id',
            field=models.UUIDField(
                default=notifications.models._uuid,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='recipient',
            field=models.CharField(max_length=200, verbose_name='المستلم (email/رقم)'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='student',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='notification_logs',
                to=settings.AUTH_USER_MODEL,
                verbose_name='الطالب',
            ),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='absence_threshold',
            field=models.IntegerField(default=3, verbose_name='حد الغياب (حصص)'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sms_provider',
            field=models.CharField(
                choices=[('twilio', 'Twilio'), ('local', 'محلي')], default='twilio', max_length=20
            ),
        ),
    ]
