# Generated by Django 5.2.12 on 2026-03-21 11:19

import django.db.models.deletion
import notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_breach_school_status_idx_core_breach_school__aa7243_idx_and_more'),
        (
            'notifications',
            '0002_rename_notif_school_type_idx_notificatio_school__75db48_idx_and_more',
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=notifications.models._uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('endpoint', models.TextField(unique=True, verbose_name='Push Endpoint')),
                ('p256dh', models.TextField(verbose_name='p256dh key')),
                ('auth', models.TextField(verbose_name='auth secret')),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='push_subscriptions',
                        to='core.school',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='push_subscriptions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'اشتراك Push',
                'verbose_name_plural': 'اشتراكات Push',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'in_app_enabled',
                    models.BooleanField(default=True, verbose_name='إشعارات المنصة'),
                ),
                (
                    'push_enabled',
                    models.BooleanField(default=True, verbose_name='Push Notifications'),
                ),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='WhatsApp')),
                (
                    'email_enabled',
                    models.BooleanField(default=True, verbose_name='البريد الإلكتروني'),
                ),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS')),
                (
                    'event_channels',
                    models.JSONField(blank=True, default=dict, verbose_name='قنوات حسب نوع الحدث'),
                ),
                (
                    'quiet_hours_start',
                    models.TimeField(blank=True, null=True, verbose_name='بداية ساعات الهدوء'),
                ),
                (
                    'quiet_hours_end',
                    models.TimeField(blank=True, null=True, verbose_name='نهاية ساعات الهدوء'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notification_preferences',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'تفضيلات إشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=notifications.models._uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('body', models.TextField(blank=True, verbose_name='النص')),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('behavior', 'مخالفة سلوكية'),
                            ('absence', 'غياب متكرر'),
                            ('grade', 'درجات جديدة'),
                            ('fail', 'نتيجة رسوب'),
                            ('clinic', 'زيارة عيادة'),
                            ('sent_home', 'إرسال للمنزل'),
                            ('meeting', 'اجتماع أولياء أمور'),
                            ('plan_update', 'تحديث الخطة التشغيلية'),
                            ('plan_deadline', 'اقتراب موعد نهائي'),
                            ('plan_overdue', 'تأخر إجراء'),
                            ('review_cycle', 'دورة مراجعة ذاتية'),
                            ('general', 'إشعار عام'),
                        ],
                        db_index=True,
                        default='general',
                        max_length=20,
                    ),
                ),
                (
                    'priority',
                    models.CharField(
                        choices=[
                            ('low', 'منخفض'),
                            ('medium', 'متوسط'),
                            ('high', 'عالي'),
                            ('urgent', 'عاجل'),
                        ],
                        default='medium',
                        max_length=10,
                    ),
                ),
                (
                    'related_object_id',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='معرّف الكائن المرتبط'
                    ),
                ),
                (
                    'related_url',
                    models.CharField(blank=True, max_length=500, verbose_name='رابط مباشر'),
                ),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='in_app_notifications',
                        to='core.school',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='in_app_notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'إشعار داخلي',
                'verbose_name_plural': 'الإشعارات الداخلية',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['user', 'is_read', '-created_at'],
                        name='notificatio_user_id_df358f_idx',
                    ),
                    models.Index(
                        fields=['school', 'event_type'], name='notificatio_school__f0b796_idx'
                    ),
                ],
            },
        ),
    ]
