# Generated by Django 5.2.12 on 2026-03-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushsubscription_usernotificationpreference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='twilio_account_sid',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='twilio_auth_token',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='auth',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='_twilio_account_sid',
            field=models.TextField(blank=True, db_column='twilio_account_sid', default=''),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='_twilio_auth_token',
            field=models.TextField(blank=True, db_column='twilio_auth_token', default=''),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='_auth',
            field=models.TextField(db_column='auth', default='', verbose_name='auth secret (encrypted)'),
        ),
    ]
