# Generated by Django 5.2.12 on 2026-03-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_role_templates_multi_evaluator_and_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='event_type',
            field=models.CharField(choices=[('behavior', 'مخالفة سلوكية'), ('absence', 'غياب متكرر'), ('grade', 'درجات جديدة'), ('fail', 'نتيجة رسوب'), ('clinic', 'زيارة عيادة'), ('sent_home', 'إرسال للمنزل'), ('meeting', 'اجتماع أولياء أمور'), ('plan_update', 'تحديث الخطة التشغيلية'), ('plan_deadline', 'اقتراب موعد نهائي'), ('plan_overdue', 'تأخر إجراء'), ('review_cycle', 'دورة مراجعة ذاتية'), ('swap_request', 'طلب تبديل حصة'), ('swap_response', 'رد على طلب تبديل'), ('swap_approved', 'موافقة على تبديل'), ('compensatory', 'حصة تعويضية'), ('general', 'إشعار عام')], db_index=True, default='general', max_length=20),
        ),
    ]
