# Generated by Django 5.2.12 on 2026-03-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_inappnotification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='event_type',
            field=models.CharField(choices=[('behavior', 'مخالفة سلوكية'), ('absence', 'غياب متكرر'), ('grade', 'درجات جديدة'), ('fail', 'نتيجة رسوب'), ('clinic', 'زيارة عيادة'), ('sent_home', 'إرسال للمنزل'), ('meeting', 'اجتماع أولياء أمور'), ('parent_summon', 'استدعاء ولي أمر'), ('plan_update', 'تحديث الخطة التشغيلية'), ('plan_deadline', 'اقتراب موعد نهائي'), ('plan_overdue', 'تأخر إجراء'), ('review_cycle', 'دورة مراجعة ذاتية'), ('swap_request', 'طلب تبديل حصة'), ('swap_response', 'رد على طلب تبديل'), ('swap_approved', 'موافقة على تبديل'), ('compensatory', 'حصة تعويضية'), ('general', 'إشعار عام')], db_index=True, default='general', max_length=20),
        ),
    ]
