# Generated by Django 5.2.16 on 2026-08-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_dlq_tenant_boundary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deadlettermessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("email", "بريد"),
                    ("sms", "SMS"),
                    ("push", "Push"),
                    ("whatsapp", "WhatsApp"),
                ],
                max_length=10,
            ),
        ),
    ]
