# Generated by Django 5.2.17 on 2026-09-24 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_arabic_field_labels"),
        ("notifications", "0016_delivery_attempt_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="deadlettermessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="deadlettermessage",
            name="error",
            field=models.TextField(blank=True, verbose_name="الخطأ"),
        ),
        migrations.AlterField(
            model_name="deadlettermessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("email", "بريد"),
                    ("sms", "SMS"),
                    ("push", "Push"),
                    ("whatsapp", "WhatsApp"),
                ],
                max_length=10,
                verbose_name="نوع الرسالة",
            ),
        ),
        migrations.AlterField(
            model_name="deadlettermessage",
            name="payload",
            field=models.JSONField(default=dict, verbose_name="المحتوى"),
        ),
        migrations.AlterField(
            model_name="deadlettermessage",
            name="resolved",
            field=models.BooleanField(default=False, verbose_name="عولِجت"),
        ),
        migrations.AlterField(
            model_name="inappnotification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
            ),
        ),
        migrations.AlterField(
            model_name="inappnotification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("behavior", "مخالفة سلوكية"),
                    ("absence", "غياب متكرر"),
                    ("grade", "درجات جديدة"),
                    ("fail", "نتيجة رسوب"),
                    ("clinic", "زيارة عيادة"),
                    ("sent_home", "إرسال للمنزل"),
                    ("meeting", "اجتماع أولياء أمور"),
                    ("parent_summon", "استدعاء ولي أمر"),
                    ("plan_update", "تحديث الخطة التشغيلية"),
                    ("plan_deadline", "اقتراب موعد نهائي"),
                    ("plan_overdue", "تأخر إجراء"),
                    ("review_cycle", "دورة مراجعة ذاتية"),
                    ("swap_request", "طلب تبديل حصة"),
                    ("swap_response", "رد على طلب تبديل"),
                    ("swap_approved", "موافقة على تبديل"),
                    ("compensatory", "حصة تعويضية"),
                    ("general", "إشعار عام"),
                ],
                db_index=True,
                default="general",
                max_length=20,
                verbose_name="نوع الحدث",
            ),
        ),
        migrations.AlterField(
            model_name="inappnotification",
            name="is_read",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="مقروء"
            ),
        ),
        migrations.AlterField(
            model_name="inappnotification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "منخفض"),
                    ("medium", "متوسط"),
                    ("high", "عالي"),
                    ("urgent", "عاجل"),
                ],
                default="medium",
                max_length=10,
                verbose_name="الأولويّة",
            ),
        ),
        migrations.AlterField(
            model_name="inappnotification",
            name="read_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت القراءة"
            ),
        ),
        migrations.AlterField(
            model_name="inappnotification",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_app_notifications",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="inappnotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_app_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="notificationdispatch",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
            ),
        ),
        migrations.AlterField(
            model_name="notificationenqueueintent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="notificationenqueueintent",
            name="enqueue_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="انتهاء مهلة الإدراج"
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "بريد إلكتروني"),
                    ("sms", "SMS"),
                    ("whatsapp", "WhatsApp"),
                    ("push", "Push"),
                ],
                default="email",
                max_length=10,
                verbose_name="القناة",
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="error_msg",
            field=models.TextField(blank=True, verbose_name="رسالة الخطأ"),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("absence_alert", "تنبيه غياب"),
                    ("fail_alert", "تنبيه رسوب"),
                    ("grade_report", "تقرير درجات"),
                    ("custom", "رسالة مخصصة"),
                ],
                default="custom",
                max_length=20,
                verbose_name="نوع الإشعار",
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_logs",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="sent_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاريخ الإرسال"
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="sent_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أرسله",
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                choices=[("sent", "أُرسل"), ("failed", "فشل"), ("pending", "معلّق")],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="_twilio_account_sid",
            field=models.TextField(
                blank=True,
                db_column="twilio_account_sid",
                default="",
                verbose_name="معرّف حساب Twilio (مشفّر)",
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="_twilio_auth_token",
            field=models.TextField(
                blank=True,
                db_column="twilio_auth_token",
                default="",
                verbose_name="رمز مصادقة Twilio (مشفّر)",
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="absence_email_enabled",
            field=models.BooleanField(default=True, verbose_name="بريد الغياب مفعّل"),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="absence_email_subject",
            field=models.CharField(
                default="تنبيه: غياب متكرر للطالب {student_name}",
                max_length=200,
                verbose_name="عنوان بريد الغياب",
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="email_enabled",
            field=models.BooleanField(
                default=True, verbose_name="البريد الإلكترونيّ مفعّل"
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="fail_email_enabled",
            field=models.BooleanField(default=True, verbose_name="بريد النتيجة مفعّل"),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="fail_email_subject",
            field=models.CharField(
                default="إشعار: نتيجة الطالب {student_name}",
                max_length=200,
                verbose_name="عنوان بريد النتيجة",
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="from_name",
            field=models.CharField(
                default="إدارة المدرسة", max_length=100, verbose_name="اسم المرسِل"
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="reply_to",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="عنوان الردّ"
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="school",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notif_settings",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="sms_enabled",
            field=models.BooleanField(
                default=False, verbose_name="الرسائل النصّيّة مفعّلة"
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="sms_from_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="رقم المرسِل"
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="sms_provider",
            field=models.CharField(
                choices=[("twilio", "Twilio"), ("local", "محلي")],
                default="twilio",
                max_length=20,
                verbose_name="مزوّد الرسائل النصّيّة",
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="_auth",
            field=models.TextField(
                db_column="auth", default="", verbose_name="مفتاح المصادقة"
            ),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="endpoint",
            field=models.TextField(unique=True, verbose_name="عنوان الاشتراك"),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="last_used",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخر استخدام"
            ),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="p256dh",
            field=models.TextField(verbose_name="مفتاح التشفير (p256dh)"),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_subscriptions",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="user_agent",
            field=models.CharField(blank=True, max_length=300, verbose_name="المتصفّح"),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="push_enabled",
            field=models.BooleanField(default=True, verbose_name="إشعارات المتصفّح"),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="sms_enabled",
            field=models.BooleanField(default=False, verbose_name="الرسائل النصّيّة"),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="whatsapp_enabled",
            field=models.BooleanField(default=False, verbose_name="واتساب"),
        ),
    ]
