# Generated by Django 5.2.17 on 2026-10-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0018_alter_inappnotification_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inappnotification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("behavior", "مخالفة سلوكية"),
                    ("absence", "غياب متكرر"),
                    ("grade", "درجات جديدة"),
                    ("fail", "نتيجة رسوب"),
                    ("clinic", "زيارة عيادة"),
                    ("sent_home", "إرسال للمنزل"),
                    ("meeting", "اجتماع أولياء أمور"),
                    ("parent_summon", "استدعاء ولي أمر"),
                    ("plan_update", "تحديث الخطة التشغيلية"),
                    ("plan_deadline", "اقتراب موعد نهائي"),
                    ("plan_overdue", "تأخر إجراء"),
                    ("review_cycle", "دورة مراجعة ذاتية"),
                    ("swap_request", "طلب تبديل حصة"),
                    ("swap_response", "رد على طلب تبديل"),
                    ("swap_approved", "موافقة على تبديل"),
                    ("compensatory", "حصة تعويضية"),
                    ("exit_not_returned", "طالب خرج ولم يعد"),
                    ("session_unmarked", "حصة بلا رصد"),
                    ("general", "إشعار عام"),
                    ("developer_message", "رسالة من المطوّر"),
                ],
                db_index=True,
                default="general",
                max_length=20,
                verbose_name="نوع الحدث",
            ),
        ),
    ]
